### ISSUE TITLE
Support MP Config 2.0 for MP Reactive Messaging 1.0

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-reactive-messaging#1002]
I'd like to make Reactive Messaging 1.0 work with MP Config 2.0. I think `ConnectorConfig` would be the only class which would need updating to be compatible since it implements the `Config` interface.

Ideally I'd have liked to make a new version which works with both MP Config 2.0 and 1.x, but I don't think that's easily done since 2.0 adds methods to the `Config` interface which reference classes which didn't exist in 1.x.

**Comment by cescoffier** [comment]
One of the issues I faced in the implementation of these new methods. Not necessarily easy or happy with what I have in SR RM 3.x.

**Comment by Azquelt** [comment]
There were a few bits I wondered about. If I end up making changes to `ConnectorConfig`, I'll be sure to open a PR for those changes in the 3.x branch as well.

**Comment by Azquelt** [comment]
Upon further investigation, I don't think this is actually possible.

The `1.1.0` release has changes which make it incompatible with the Reactive Messaging 1.0 API (in particular, `Message` implementations need to override the default `getAck()` for acknowledgement to work correctly.)

We can't branch off from the `1.0.8` release either because we can't support both MP Config 1.x and 2.0 with one implementation of `ConnectorConfig`. (The 2.0 interface references `ConfigValue` which is a new interface not present in 1.x. A valid 2.0 implementation of `ConnectorConfig` therefore can't be loaded or compiled against the 1.x API). We couldn't put out a `1.0.9` release which required users to update to MP Config 2.0.
