### ISSUE TITLE
How to handle exceptions/errors when using Emitter and smallrye-http

### ISSUE THREAD

**Issue by anaray** [smallrye/smallrye-reactive-messaging#1076]
How can I handle and recover my application if the downstream HTTP service is down? In my case case I am getting 
```
Request failed: java.lang.IllegalStateException: SRMSG00028: The subscription to events has been cancelled
```
Even after the downstream service comes back, I am getting above exception. Is there a way to re-subscribe? Documentation doesn't contain resiliency section https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/http/http.html#http-outbound

I have an Emitter and channel (events) and in the application.properties it is using 
```
mp.messaging.outgoing.events.connector=smallrye-http
mp.messaging.outgoing.events.method=POST
mp.messaging.outgoing.events.url=http://localhost:9090/events
```

My code which sends http request is as below
```
@ApplicationScoped
@Path("/events")
@Retry(maxRetries = 2)
@Tag(name = "Ingestion Gateway for events", description = "The REST API endpoint for events")
public class EventsGatewayResource {

    private static final Logger LOGGER = Logger.getLogger("EventsGatewayResource");
    @Inject
    @Channel("events")
    Emitter<byte[]> eventsEmitter;

    @POST
    @Consumes("application/x-protobuf")
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(responseCode = "200", description = "{response : success}")
    @APIResponse(responseCode = "500", description = "{response : failure}")
    public CompletionStage<Response> enqueuePayload(byte[] payload,
                                                    @RestHeader("X-Service") String service,
                                                    @RestHeader("X-Env") String environment,
                                                    @RestHeader("X-Type") String type) {
        LOGGER.infof("Sending http body payload %s to test http application, headers %s",
                payload.length, service
        );

        return eventsEmitter.send(payload).thenApply(response -> Response.ok(success).build()).exceptionally(throwable -> Response.serverError().build());
    }
```

Please advice. I am creating a prototype and I am not able to make progress without this. A section on "How to handle exceptions, errors and failures would be of great help!

**Comment by cescoffier** [comment]
Which version are you using?

If you are using Quarkus, there is a dedicated connector for Http which is
more advanced than this one.

**Comment by anaray** [comment]
@cescoffier I created a ticket in Quarkus too https://github.com/quarkusio/quarkus/issues/15344 . 
The Quarkus version is Quarkus 1.11.1.Final.

**Comment by cescoffier** [comment]
In Quarkus, you should not use this smallrye-http connector. See https://quarkus.io/guides/reactive-messaging-http.html

**Comment by anaray** [comment]
Thank you @cescoffier . Using quarkus-http solved my issue.
