### ISSUE TITLE
Unable to send tombstone message

### ISSUE THREAD

**Issue by ferencbeutel4711** [smallrye/smallrye-reactive-messaging#1078]
Hello there,

we have the requirement that we need to send a kafka message programatically (so using the channel-based approach with the annotations would not work for us)
To get it to work we used the Emitter coming from the org.eclipse.microprofile.reactive.messaging package. However, that emitter expects a Message, which cannot have a null payload.

How are we supposed to send a tombstone record through the emitter? Alternatively, if the emitter is not the correct approach, how could we trigger the sending of a message programatically not using the annotation-based approach?

Thanks :)

**Comment by cescoffier** [comment]
First, even on _channel_, you can customize the destination using message metadata.

Then, to send a tombstone, send:

```
Record.of(key, null); 
```

**Comment by ferencbeutel4711** [comment]
Hi, thank you for your swift response. I understand that when using the channel-based approach with the annotations, you can send a tombstone record by the way specified by you. However, we cannot use the annotation-based approach.
We have a scheduled method like this:

```
@Scheduled
fun execute() {
  database.fetchNextEntries(batchSize = 100).forEach { entry ->
    emitter.send(Message.of(entry).addMetadata(buildMetadata(entry)))
    if(needsTombstone(entry)) emitter.send(Message.of(null).addMetadata(buildTombstoneMetadata(entry)))
  }
}
```

This piece of code is integrated into a bigger job-framework which is responsible for orchestration of this code over multiple instances, synchronization etc. Therefore it is crucial for us to programatically trigger the sending of a new event, like with the emitter. However, the Message.of() function does not permit null value, we always get an exception at this piece of code:

```
Message.of(null)
```

**Comment by cescoffier** [comment]
Ah, sorry, I misunderstood! 

Instead of `Message.of(null)`, use `Message.of(Record.of(key, null))`

Your emitter would need to be:

```
@Inject Emitter<Record<K, V>> emitter
```

**Comment by ferencbeutel4711** [comment]
Thanks again for your response and help. I can confirm that this is working and am happily closing the issue :)
