### ISSUE TITLE
stop using `@Named`

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-reactive-messaging#1096]
While I understand the desire to use stringly-typed injection from time to time (and I think it's OK), the `@Named` qualifier is a wrong way to do it. In CDI, `@Named` doesn't work as all other normal qualifiers do.

Imagine this:

```java
@ApplicationScoped
public class MapProducer {
    @Produces
    @Named("my-name")
    Map<String, Object> map() {
        Map<String, Object> result = new HashMap<>();
        result.put("foo", "bar");
        result.put("baz", "quux");
        return result;
    }
}

@ApplicationScoped
public class MapConsumer {
    @Inject
    Map<String, Object> map;

    void init(@Observes @Initialized(ApplicationScoped.class) Object event) {
        System.out.println(map);
    }
}
```

Note that the injection point in `MapConsumer` doesn't declare a qualifier -- yet the `init` method prints `{foo=bar, baz=quux}`.

I'm pretty sure we (in SRye RM) didn't intend this, but that's what happens.

I'm currently aware of these usages of `@Named`:

- if you create a bean of type `KafkaConsumerRebalanceListener` qualified with `@Named("some-name")`, it's used as a consumer rebalance listener for consumers of channels that declare `mp.messaging.incoming.*.consumer-rebalance- listener.name=some-name`, or alternatively, for consumers in the consumer group `some-name`;
- if you create a bean of type `Map<String, Object>` qualified with `@Named("default-kafka-broker")`, it's used as a default config for all Kafka-based channels;
- this [PR](https://github.com/smallrye/smallrye-reactive-messaging/pull/1092) proposes that if you create a bean of type `Map<String, Object>` qualified with `@Named("some-name")`, it's used as a default config for those Kafka-based channels that declare `mp.messaging.incoming.*.kafka-configuration-name=some-name`.

There might be more that I'm not aware of, but I hope not :-)

My suggestion would be to create dedicated qualifier annotations. For the 3 cases listed above, respectively:

- `@[Kafka]ConsumerRebalanceListenerName("...")`
- `@DefaultKafkaConfiguration` (or `@KafkaDefaultConfiguration`)
- `@KafkaConfiguration("...")`

WDYT?

CC @mkouba as the tireless fighter against `@Named` misuse :-)

**Comment by Ladicek** [comment]
Also, for the cases where we use `Map<String, Object>`, we might want to create an extra type for this, but not exactly sure how much is it worth. The Kafka client API also uses `Map`s (or `Properties`).

**Comment by mkouba** [comment]
> Also, for the cases where we use `Map<String, Object>`, we might want to create an extra type for this, but not exactly sure how much is it worth. The Kafka client API also uses `Map`s (or `Properties`).

I think that a qualifier works better here.

The general problem with JDK types is that other extensions can produce a bean of the same type and if you only use the `@Named` qualifier then the `@Inject Map<String, Object>`  would result in an ambiguous resolution exception.

**Comment by cescoffier** [comment]
I'm not against using another qualifier, but it would need to be shared between Quarkus and SmallRye Reactive Messaging. I guess something for smallrye-annotations. 

We used @Named because we wanted to disambiguate the injection and the user can only pass an id. Types won't work as 

1. we are not in control of them
2.  we may have multiple candidates

So we need a way to identify the "one".

**Comment by Ladicek** [comment]
As I said, I'm totally fine with disambiguating based on string ID. I'm not in the camp of "must be 100% type-based".

As you point out, another option would be to invent a generic alternative to `@Named`, that would behave like a proper qualifier. I think I'd prefer using specific qualifiers for each use case (instead of one generic `@BetterNamed`), but I can't quite articulate why, it's just a feeling.

(For items 2 and 3 in the list above, one qualifier might be enough. `@KafkaConfiguration("default")` would probably be an OK alternative to `@DefaultKafkaConfiguration`.)

**Comment by cescoffier** [comment]
We would have the same issue in the AMQP connector. So, better not bind it to Kafka.
What about `@Id` or `@BeanName`?

**Comment by mkouba** [comment]
`@Id` may be confused with `@javax.persistence.Id` and `@BeanName` can be confused with `Bean.getName()` (for which `@Named` is used ;-). Maybe something like `@Identified`?

**Comment by cescoffier** [comment]
Good point! 
I've nothing against `@Identified`. @Ladicek WDYT?

**Comment by Ladicek** [comment]
I don't think `@Identified` works as is. Something is _named_ "foo", but it's not _identified_ "foo", it's _identified by_ "foo". That would lead to `@IdentifiedBy`, which is a bit ugly in my eyes. `@Identifier` would be better in my opinion.

Both are quite long, too, which I don't like, so I went and found that you can ask Google for synonyms of a word :-) I think JUnit Jupiter already grabbed `@Tag` (all nice names are already taken!). Another option is "label", but apparently both `@Labeled` and `@Labelled` are correct, which is itself a reason to avoid this option. Then, there are things like handle, title or moniker, which are probably all just bad (frankly, I'd really dig `@Moniker`! :-) ), so ... useless excersise.

`@Identifier` or `@IdentifiedBy` are fine with me.

**Comment by mkouba** [comment]
Well, the `@Identified` was an attempt to abbreviate "identified by the string value". `@IdentifiedBy` does not help much - it merely says that it's identified by something... not necessarily the `value` of the annotation. `@Identifier` looks ok. There's also: `@StringId` `@StrId`, `@StringIdentifier`.

**Comment by Ladicek** [comment]
We can call it `@StringlyTyped` :-D

For `@IdentifiedBy`, remember there's a mandatory `value` attribute, so it always looks like `@IdentifiedBy("foobar")`. Which I think makes sense.

In an unrelated project, I once came up with `@WithName`.

Or `@Designated` :-D

**Comment by mkouba** [comment]
`@IdentifiedBy("foo")` reads well. `@WithName("foo")` is also OK, I also used similar approach in several projects.

**Comment by Ladicek** [comment]
Alright, I'll submit a PR to SRye Common and we can discuss there.

**Comment by Ladicek** [comment]
I just found that some injection points for `Instance<Something>` actually rely on this behavior (that `@Named` isn't a proper qualifier and if there's no other qualifier, the bean also has the `@Default` qualifier), because they didn't use the `@Any` qualifier. Fixing them as I find them.

**Comment by cescoffier** [comment]
Thanks @Ladicek !
