### ISSUE TITLE
Add support for dynamic per message topic for Mqtt messaging

### ISSUE THREAD

**Issue by misl** [smallrye/smallrye-reactive-messaging#110]
In the existing situation Mqtt messaging only supports (hard) configured topics. This however does allows you to determine the topic dynamically per message. Kafka messaging however does have this ability.
I would be nice if Mqtt messaging could support dynamic topics as well.

**Comment by misl** [comment]
A pull request for this on in the making, I need to add some more unittests first.

**Comment by cescoffier** [comment]
Agreed,

**Comment by zeljkot** [comment]
@misl I need to determine the topic dynamically per Kafka message, but I could not find any documentation or example. Could you please give me some pointers?

**Comment by cescoffier** [comment]
@zeljkot you should send an email to the mailing list for questions.

For sending a kafka message to a specific topic, creates a KafkaMessage as follows:
```
  @Outgoing("to-kafka")
  public KafkaMessage<String, String> produce(Message<String> incoming) {
    return KafkaMessage.of("topic", "key", incoming.getPayload());
  }
```
