### ISSUE TITLE
Add custom header to message before it is sent to dead letter queue

### ISSUE THREAD

**Issue by r00ta** [smallrye/smallrye-reactive-messaging#1103]
Hi! 

I'm trying to add a custom header to the message I fail to process, but as far as I can see the header is not there in the new event in the dead letter queue. 

Here's a snippet of my application that adds the custom header before I send the `nack`

```java 
    protected CompletionStage<Void> handleMessage(final Message<String> message) {
        try {
            CloudEventUtils.decode(message.getPayload()).ifPresent(this::handleCloudEvent);
        } catch (Exception e) {
            Optional<IncomingKafkaRecordMetadata> metadata = message.getMetadata(IncomingKafkaRecordMetadata.class);
            int retryCounter = 1;
            if (metadata.isPresent()) {
                LOG.info("metadata present");
                Header header = metadata.get().getHeaders().lastHeader("my-header");
                if (header != null) {
                    LOG.info("header present");
                    retryCounter = intFromByteArray(header.value());
                }
            } else {
                LOG.info("metadata not there");
            }
            if (retryCounter >= 10) {
                LOG.error("retry counter = 10");
                return message.ack();
            }
            message.withMetadata(Metadata.of(buildFailedCounterMetadata(retryCounter + 1)));
            return message.nack(e);
        }
        return message.ack();
    }

    private OutgoingKafkaRecordMetadata<String> buildFailedCounterMetadata(int value) {
        return OutgoingKafkaRecordMetadata.<String> builder()
                .withKey("failure-count-key")
                .withHeaders(new RecordHeaders()
                        .add("my-header", intToByteArray(value))
                        .add("nextTimestamp", intToByteArray((int) System.currentTimeMillis() / 1000 + 60)))
                .build();
    }
```

Is this scenario not supported or am I doing something wrong? Or am I facing a bug? If needed, I can create a separated reproducer. 

Thank you very much!

**Comment by cescoffier** [comment]
It’s an interesting feature. At the moment you can’t modify the header
passed to the dlq. We should provide a way to customize the written record.

**Comment by Ladicek** [comment]
I see where the problem is. `Message` exposes an immutable interface, so when you do

```java
message.withMetadata(Metadata.of(buildFailedCounterMetadata(retryCounter + 1)));
return message.nack(e)
```

the 1st line creates a new `Message` (and immediately discards it), and the 2nd line calls `nack` on the original `Message`.

However, even if you fixed the code to do

```java
return message.withMetadata(Metadata.of(buildFailedCounterMetadata(retryCounter + 1)))
              .nack(e)
```

it still wouldn't work. The new `Message` would carry over the old nack handler, which would use the old `Message` state.

I'll see what I can do about it, but frankly, trying to expose an immutable interface over something that is inherently stateful is IMHO a bad idea.

**Comment by Ladicek** [comment]
I have prototyped something here: https://github.com/Ladicek/smallrye-reactive-messaging/commits/modify-kafka-dlq-metadata

I need to look at how to actually propagate the outgoing metadata into the nack handler -- the rest should be good.

**Comment by cescoffier** [comment]
The metadata is immutable to avoid concurrent access, which had lead to many issues in the first attempt of the APIs. 
However, the metadata object themselves could be mutable. So, you can inject a metadata object in the message (in the incoming connector), and modify its state.

**Comment by Ladicek** [comment]
I don't really mind the metadata -- what matters is the message :-)

At this point, I'm thinking it would probably be best to add `nack(Throwable, Metadata)` to the existing `nack(Throwable)`. If the underlying connector supports it, the `Metadata` would be used in the nack handler. For example, when the Kafka connector forwards the nacked message to a dead letter topic, it would look for `OutgoingKafkaRecordMetadata` in the `Metadata` and if it's there, use it to augment the outgoing message.

I'll see if that's possible.

**Comment by Ladicek** [comment]
So it seems the idea is entirely possible. I pushed the prototype here: https://github.com/Ladicek/smallrye-reactive-messaging/commits/modify-kafka-dlq-metadata

With this change, the original use case would be solved with:

```java
return message.nack(e, Metadata.of(buildFailedCounterMetadata(retryCounter + 1)));
```

@r00ta WDYT?

**Comment by r00ta** [comment]
> So it seems the idea is entirely possible. I pushed the prototype here: https://github.com/Ladicek/smallrye-reactive-messaging/commits/modify-kafka-dlq-metadata
> 
> With this change, the original use case would be solved with:
> 
> ```java
> return message.nack(e, Metadata.of(buildFailedCounterMetadata(retryCounter + 1)));
> ```
> 
> @r00ta WDYT?

Hi @Ladicek , thank you very much for taking care of this. From my perspective I think this is going to cover my scenario :+1:

**Comment by Ladicek** [comment]
Perfect, thanks! I'll write some documentation and submit a PR.
