### ISSUE TITLE
AMQP producer requests credits asynchronously, leading to possible subscription error

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-reactive-messaging#1125]
I'm playing with the AMQP connector and found an interesting thing that I'd personally call a bug.

I have a textbook producer configured to produce messages into a queue in an Artemis broker:

```java
@Outgoing("ticks-producer")
public Multi<Message<String>> produce() {
    return Multi.createFrom()
            .ticks().every(Duration.ofMillis(1000))
            .map(it -> Message.of("" + it));
}
```

There's nothing else in the application -- it just pushes messages into a queue. However, when I run it, I get nothing -- no messages appear in the queue, no error message is printed to the log, nothing.

I added a few debug prints and found that `AmqpCreditBasedSender.onError` is called early on with a backpressure error: the ticks stream can't produce anything, because noone has requested any items. I can easily make the whole thing work by the following little change:

```java
@Outgoing("ticks-producer")
public Multi<Message<String>> produce() {
    return Multi.createFrom()
            .ticks().startingAfter(Duration.ofMillis(2000)).every(Duration.ofMillis(1000))
            .map(it -> Message.of("" + it));
}
```

Here, the producer takes a little break at the beginning, which is enough for the async process started in `AmqpCreditBasedSender.getSenderAndCredits` to finish. That, in turn, requests items from the source stream, and all goes well.

I'm not exactly sure where the problem is -- I'm not well-versed in the Reactive Streams request protocol, so I'm not sure if `Subscription.request` is supposed to work synchronously or if asynchrony is permitted. I first thought that it must be synchronous, so I rewrote the `AmqpCreditBasedSender.request` method to this:

```java
public void request(long l) {
    if (!once.getAndSet(true)) {
        try {
            getSenderAndCredits().await().indefinitely();
        } catch (Exception e) {
            downstream.get().onError(e);
        }
    }
}
```

and indeed that also fixed the problem. But it sounds more like a workaround, and seems to not comply with the Reactive Streams specification.

Full reproducer is here: https://github.com/Ladicek/artemis-playground Run the Artemis broker per the README, then run the `ProducerMain` class from the `amqp/producer` module.

**Comment by cescoffier** [comment]
It's an interesting scenario. Ticks does not handle backpressure (you can't constraint time), meaning that if you emit too quickly it will fail with a back pressure error.
In general we combine ticks with an overflow strategy such as:

```java
Multi.createFrom().ticks(...)
   .onOverflow().drop()
```

Now, is this a bug or expected.

`request` can be asynchronous or synchronous. It's up to the "source" to decide how it will handle it. However, it must not block the thread.  So, it's not strictly a bug, but it's something we should improve. Typically, your workaround would not work on Quarkus, if "request" is called from the I/O Thread.

**Comment by Ladicek** [comment]
My workaround does work with Quarkus, because the initial `request` is not called from an event loop thread (and that's expected, IIUC, because it submits the "get credits" task to the event loop -- so it knows the original thread might be / often is something else).

Now, how do we improve this? I'm going to claim that "no error is printed and no message is produced" is a bug (one that took me a few hours to debug, I was looking everywhere else). If anything, the exception must not be swallowed. I'll try to figure out some logging.

**Comment by cescoffier** [comment]
The fact it does not print anything is definitely a bug. I can see why.
The failure is propagated (good) but because there is no subscription yet, it can't pass the failure downstream.

That being said, there is another weird part, how can you produce items if the outbound connector did not subscribe yet. I will look at your reproducer, there is something weird there too.

**Comment by Ladicek** [comment]
This is what I was scratching my head about, actually. Because as far as I can tell, there _is_ a subscription -- it just didn't request anything yet (because it first needs to get credits from the broker). That's why deferring the first tick for a few seconds helps -- the asynchronous process that gets credits and then requests items has a chance to finish.

**Comment by cescoffier** [comment]
I tracked down the issue and found the _culprit_.

The `ticks` are started at subscription time and not when it gets the first requests. Most of the time these two events are close enough so it does not fail. But, here, emitting the first request takes time (as we need to retrieve the credits from the broker) and ... boom.

One way to fix the problem would be to fix the Mutiny "ticks", to only start at the first request. I'm discussing it with @jponge. The fix is trivial. 

Another way, more AMQP specific would be to delay the subscription until we get the credits. That leads to the interesting case where we get `0` credits (should we still subscribe, fail, retry later?). 

Also, my feeling is that, while rare, what we are seeing here is not AMQP centric, and can happen as soon as we delay the requests:

```
Multi.createFrom().ticks().every(Duration.ofSeconds(5))
   .onRequest().call(() -> Uni.createFrom().voidItem().onItem().delayIt().by(Duration.ofSeconds(10))) // simulate some delay
  .subscribe().with(i -> System.out.println(i), f -> f.printStackTrace());
```

**Comment by Ladicek** [comment]
Do we wanna close this (addressed in Mutiny), or is there something we could/should do on the Reactive Messaging side as well?

I'm thinking we should at least provide some form of error logging in case there's no downstream to which an error could be propagated. I'll submit a PR if you agree :-)

**Comment by cescoffier** [comment]
Yes, we need to log something in this case. I let you open a PR.
