### ISSUE TITLE
dynamic channels

### ISSUE THREAD

**Issue by Traivor** [smallrye/smallrye-reactive-messaging#1134]
I have a project where I need to be able to publish to arbitrary channels determined at runtime. Basically I'm wanting to dispatch jobs to region appropriate channels. I tried this as a test with a static channel name that works fine when used the normal way:

```java
	//@Inject
	//@Channel("snmp-out")
	//@OnOverflow(OnOverflow.Strategy.UNBOUNDED_BUFFER)
	//private Emitter<String> emitter;
	@Inject
	@Any
	@OnOverflow(OnOverflow.Strategy.UNBOUNDED_BUFFER)
	private Instance<Emitter<String>> emitterInstance;

...

		Emitter<String> emitter = emitterInstance.select(new ChannelLiteral("snmp-out")).get();

```

Unfortunately that results in:

> Caused by: java.lang.IllegalStateException: Unable to find a emitter with the name snmp-out, available emitters are: [fping-out]

Is there some way to dynamically bring up channels after startup?

**Comment by cescoffier** [comment]
You can't use dynamic channels like this. However, you can attach metadata to messages to indicate where they should go (for example the Kafka topic). Would that work for you?

**Comment by Traivor** [comment]
It would be nice if channels could be injected like this someday. It feels very CDI-y to me.

I hadn't noticed the metadata stuff. It might work, but:
* Is there some way to determine what kind of connector the channel is configured for?
  * I guess I could dig out the config property...
* Otherwise, is it possible to add all possible metadata types to a single message?
  * The javadoc suggests no...

My application doesn't know what kind of connector it is going to be dealing with. My goal is to allow the end user to use any infrastructure they have available. In fact, the default configuration just uses vertx for in-memory message passing (which doesn't provide for metadata at all...).

**Comment by cescoffier** [comment]
We picked a different approach and validate the complete graph at startup (even at build time in Quarkus (coming soon)). So you can't define channels like this. 

> Is there some way to determine what kind of connector the channel is configured for? I guess I could dig out the config property...

I don't see another way.

> Otherwise, is it possible to add all possible metadata types to a single message? The javadoc suggests no...

You can add as man y metadata as you want. a metadata is just an object.

**Comment by cescoffier** [comment]
Closing, please re-open if you need.

**Comment by Traivor** [comment]
> Closing, please re-open if you need.

Sounds good. Thanks for the help.
