### ISSUE TITLE
Publishing to amqp exchange.

### ISSUE THREAD

**Issue by belkevglaz** [smallrye/smallrye-reactive-messaging#1139]
Is it possible to publish messages directly to amqp exchange to be able to use `fanout` or `topic` pub/sub mechanism out of the box?

**Comment by cescoffier** [comment]
The AMQP connector is for AMQP 1.0. 

So, I'm not totally sure what you are talking about.

**Comment by belkevglaz** [comment]
Thanks @cescoffier. 
I'm trying to migrate our product from `SpringBoot` to `Quarkus` and faced with some problems that were solved perfectly in `Spring Messaging`.
I'm would like to deliver messages to all consumers (queues) on RabbitMQ. In all guides mentioned outbound channels with simple configuration like `mp.messaging.outgoing.publish-channel.address` where address is a queue (looks like this) name. Unfortunately, I'm not found any information, how to configure or implements logic to send messages to amqp exchange, but not to queue.
Formally, as I know,  in RabbitMQ all messages goes to default exchange first and routed to queue based on routing_key (in simple case routing_key = queue name)
From RabbitMQ docs :

> The core idea in the messaging model in RabbitMQ is that the producer never sends any messages directly to a queue. Actually, quite often the producer doesn't even know if a message will be delivered to any queue at all.
Instead, the producer can only send messages to an exchange. An exchange is a very simple thing. On one side it receives messages from producers and the other side it pushes them to queues. 

Could you point me how to get around this?

**Comment by cescoffier** [comment]
You refer to RabbitMQ specific behavior. You will have to check how this can be done with the RabbitMQ AMQP 1.0 plugin (on the broker side).

**Comment by Ladicek** [comment]
I'm no expert, but I believe that what @cescoffier is trying to explain is: the AMQP connector in SmallRye Reactive Messaging uses AMQP 1.0. The notion of "exchange" seems to be specific to AMQP 0.9.1. Even though numerically, the difference between 1.0 and 0.9.1 is something like 0.0.9 :-D, the reality is that AMQP 0.9.1 and 1.0 are two completely different protocols that have nothing in common but the name.
