### ISSUE TITLE
How can I send a request every time I refresh a web page? - No suscriber found error

### ISSUE THREAD

**Issue by Gfuentesmo99** [smallrye/smallrye-reactive-messaging#1176]
Hello guys! I'm trying to make a webapp and I'd like to a message when I refresh the web(This is an easy example that I've made because it's easier to understand). I've tried with internal channels but I also tried with Kafka and it did not work too.

The failure message is "No subscriber found for the channel  "notify refresh"". When I tried it with kafka there was no error but it doesnt retrieves the message.

My Resource:
It returns a publisher because a functionality that the main app has and not this reproducible example, but that is not the problem.
```
@ApplicationScoped
@Path("/refresh")
public class refresh {

    @Inject
    @Channel("notify-refresh")
    Emitter<String> emitter;


    @Inject
    @Channel("uploaded")
    Publisher<String> publisher;

    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.TEXT_PLAIN)
    public Publisher<String> hello() {
        emitter.send("lets go");
        return publisher;
    }
}
```

And then this class takes the msg, make some changes and send to a processor:

```
@ApplicationScoped
public class generator {

    @Incoming("notify-refresh")
    @Outgoing("send-processor")
    public String sendToProcessor(String uni){
        return uni;
    }
}
```

The processor which returns to the resource:
```
@ApplicationScoped
public class processor {

    @Incoming("send-processor")
    @Outgoing("uploaded")
    public String processMsg(String uni){
        return uni;
    }
}
```

**Comment by cescoffier** [comment]
You are creating a cycle, I don't believe it would work. 
With Kafka is will work because it cut the cycle.
