### ISSUE TITLE
Allow Kafka consumer to specify the initial offset

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#1195]
The idea is to allow the application to define which offset should be read first.
This can be done using the `seek` method on the Kafka Consumer.

CC @Ladicek that's what we discussed.

**Comment by Ladicek** [comment]
I've been looking into this for a while today and I believe we shouldn't attempt to allow _programmatically_ setting an _initial_ offset. There's just no good place in the code to do that. It is an error to seek on a topic/partition you haven't been assigned, so we'd have to wait for an initial assignment -- which gets notified through a rebalance listener.

Fortunately, Kafka itself has a way to _configure_ the initial offset _in case no offset is committed_: the `auto.offset.reset` property. Furthermore, we can expose the `seek` operations through our `KafkaConsumer` interface. That should be enough for advanced use cases. WDYT? I'll submit a draft PR and we can discuss there, too.

**Comment by cescoffier** [comment]
>I've been looking into this for a while today and I believe we shouldn't attempt to allow programmatically setting an initial offset. There's just no good place in the code to do that. It is an error to seek on a topic/partition you haven't been assigned, so we'd have to wait for an initial assignment -- which gets notified through a rebalance listener.

That's a good point!


> Fortunately, Kafka itself has a way to configure the initial offset in case no offset is committed: the auto.offset.reset property. Furthermore, we can expose the seek operations through our KafkaConsumer interface. That should be enough for advanced use cases. WDYT? I'll submit a draft PR and we can discuss there, too.

+1 to expose seek operation. So, if you want a specific location, implement a rebalance listener which will be called during the assignment and let you seek the right position. (that would need to be documented).

**Comment by Ladicek** [comment]
Thanks! I'll see what's the best place in the documentation to mention this.

**Comment by Ladicek** [comment]
Actually I see that our `KafkaConsumerRebalanceListener` already provides access to the Kafka `Consumer`, and our documentation for consumer rebalance listeners even contains an example of `seek`-ing. So we already have everything that's needed for this.

I'm just thinking I will add a short section on `KafkaClientServices` to the documentation and that will be it.
