### ISSUE TITLE
Allow receiving Kafka record by batch

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#1214]
At the moment, the records are received one by one, requiring a method processing the stream to recreate a _batch_ (by size). It would be convenient to allow the user to receive the batch directly:

```java
@Incoming("kafka")
void consumeBatch(List<Record> records) {
  // contains all the records from the batch
}
```

The underlying client should allow us to do this, and a converter should be able to call the method.

Acknowledgment would still be the same, except that when this method returns, we ack all the included messages.

**Comment by diogenes1oliveira** [comment]
This functionality would help me a lot as well. I suppose we can do some tricks with Multi<> and Uni<> but it isn't clear how that would work, at all.

Some suggestions on how to implement microbatches would be very welcome!

**Comment by cmasantos** [comment]
It would also be cool if we could define a timetout, for example: take lists of 100 records but wait at max 5 minutes. 

We can make it work using this: https://github.com/smallrye/smallrye-reactive-messaging/issues/979

But it would be nice do this without that workaround.

**Comment by cescoffier** [comment]
@cmasantos #979 won't help. Mutiny does not have (yet) an operator grouping items with a max duration. 

CC @jponge

**Comment by jponge** [comment]
We can make groups at fixed rates with `every` but it's not the same thing.

**Comment by cescoffier** [comment]
An idea would be to implement a Message implementation where the payload is the collection/list of records (or values).

- Calling .ack() would commit the last offset of the batch
- It should provide metadata such as initial offset, last offset, topic, partition, number of records...
- It should allow access to the underlying records
