### ISSUE TITLE
CDI Extension assumes that the Config bean is available

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-reactive-messaging#127]
On OpenLiberty, the `Config` bean is RequestScoped*. This means that the reactive messaging provider throws an error when trying to obtain the config because the request scope isn't active.

This could be fixed by:
* Using the `ConfigProvider.getConfig()` method to obtain the config, rather than the bean
* Manually activating the request scope around the `afterDeploymentValidation` observer method

We could also work around it if `afterDeploymentValidation` was made `protected` so that we could activate the request context around it.

*The rationale for using `@RequestScoped` for the `Config` bean is that the config is based on the thread context classloader which can vary depending on which web module processes the request.

**Comment by cescoffier** [comment]
@mkouba what do you think?

While I like using `ConfigProvider.getConfig()`, I need to see how I can _mock_ this in tests.

**Comment by mkouba** [comment]
> Manually activating the request scope around the afterDeploymentValidation observer method

Hm, it's not very common to activate the request context during a container lifecycle notification. In fact, I've never seen it before.

> the Config bean is RequestScoped

Well, although the spec does not specify a scope of the `Config` bean it's IMHO quite natural to expect the ApplicationScoped/Singleton scope. I understand the rationale though. 

@Azquelt Couldn't you try to use the current TCCL to identify the correct Config instance and delegate to this instance in every `Config` method invocation? I.e. something like:

```java
@Produces
Config getConfig(InjectionPoint injectionPoint) {
        return new Config() {
             Iterable<String> getPropertyNames() {
                  return ConfigProvider.getConfig(getContextClassLoader()).getPropertyNames();
             }
        }  
}
```

**Comment by Azquelt** [comment]
> While I like using `ConfigProvider.getConfig()`, I need to see how I can _mock_ this in tests.

If you don't have a Config implementation present, I think you would just need to implement a mock `ConfigProviderResolver` to return your mock `Config`

@mkouba yes that does work and probably makes sense for us to do anyway, I'll run it past the rest of my team. Thanks.

**Comment by cescoffier** [comment]
Closing for now. Please reopen if the current solution does not work for you.
