### ISSUE TITLE
Potential misuse of @Outgoing and/or @Incoming annotations in documentation examples

### ISSUE THREAD

**Issue by oneturkmen** [smallrye/smallrye-reactive-messaging#1273]
If a method of a class uses `@Outgoing` or `@Incoming` from Microprofile Reactive API, then the class containing the method(s) should be annotated with `@ApplicationScoped` or `@Dependent` annotations

Relevant documentation link: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/model/model.html#overview

Relevant code snippets:
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/camel/examples/api/CamelApi.java#L23
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/processing/StreamExamples.java#L9
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/ack/StreamAckExamples.java#L9
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/skip/StreamSkip.java#L8
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/ack/PreAckExamples.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/generation/GenerationExamples.java#L14
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/consumption/ConsumptionExamples.java#L10
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/skip/SingleSkip.java#L8
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/broadcast/BroadcastExamples.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/converters/ConverterExample.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/broadcast/BroadcastWithCountExamples.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/beans/Chain.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/ack/AutoNack.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/messages/MetadataWithMessageChainExamples.java#L12
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/processing/ProcessingExamples.java#L11
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/merge/MergeExamples.java#L7
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/ack/MessageAckExamples.java#L9
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/messages/MetadataWithPayloadChainExamples.java#L12
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/emitter/EmitterExamples.java#L11
https://github.com/smallrye/smallrye-reactive-messaging/blob/49bae43453a27e3c26e0db6682ea9ad2654c311d/documentation/src/main/doc/modules/ROOT/examples/incomings/IncomingsExamples.java#L5

**Comment by cescoffier** [comment]
The code you listed is just here to allow inclusion into the documentation. They are not bean per-se (we don't execute them). Yes, in a real application these classes would need to be annotated with `@ApplicationScoped` (or any other supported scope).
