### ISSUE TITLE
Messages not sent when being ready while AK still is starting

### ISSUE THREAD

**Issue by gunnarmorling** [smallrye/smallrye-reactive-messaging#128]
I have a [Compose file](https://github.com/gunnarmorling/quarkus-quickstarts/blob/srm-128/kafka-streams-quickstart/docker-compose-distributed.yaml) that starts AK, ZooKeeper and a Quarkus app that writes to a Kafka topic via a Reactive Flow, i.e. it should produce a new message every second. But for some reason only a single message is written, and then nothing more happens. This is not the case, if I start the Quarkus app some time after AK and ZooKeeper have started up. To reproduce, run

    docker-compose -f docker-compose-distributed.yaml up

Then observe how only a single time it is logged that the "temperature-values" message has been written despite this being a `Flowable` producing new values continuously.

**Comment by cescoffier** [comment]
So the fact you don't see the other value is the expected behavior as the back-pressure kicks in and consider that the sink (kafka) is not ready to receive more (and so do not request other values).

However, instead of this behavior, we should just log an error message, and not acknowledge the incoming message.

**Comment by gunnarmorling** [comment]
Ok, but the interesting fact is that I actually see that first message in
Kafka; so it appears as if the stream doesn't continue after the issue
causing the back-pressure has been resolved.

**Comment by gunnarmorling** [comment]
This situation is very confusing and in particular not easily detectable,
as the application keeps running. So it wouldn't be restarted e.g. on OS
automatically.

>

**Comment by cescoffier** [comment]
Yes, definitely not the right behavior.

When I start without kafka I'm seeing:
```
[kafka-producer-network-thread | producer-2] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

Are you seeing these messages too?

**Comment by gunnarmorling** [comment]
Yes, I do see those.

**Comment by gunnarmorling** [comment]
@cescoffier, should this be resolved as per the commit you pushed?

**Comment by cescoffier** [comment]
@gunnarmorling You are right, this has been fixed.
