### ISSUE TITLE
Instance Emitter without using @Inject

### ISSUE THREAD

**Issue by phelioz** [smallrye/smallrye-reactive-messaging#1302]
Would like to instance a Emitter without using @Inject. So creating it imperative and using a dynamic channel name.
So instead of doing this:
```
@Inject
@Channel("random_channel_name")
Emitter<JsonObject> emitter;
```

I would like to do something like this:
```
Emitter<JsonObject> emitter = <something>.createEmitter("random_channel_name");
```

I see that you can get the existing emitters from `io.smallrye.reactive.messaging.ChannelRegistry.getEmitter()`
Wonder if there is anything similar for creating a emitter, if not this would be a feature request for it.

**Comment by ozangunalp** [comment]
This is not possible at the moment and I don't think that if it'll ever be. 

Channels are configured for a specific messaging backend using connectors, such as `smallrye-kafka`, `smallrye-amqp`, etc. This is done at startup and configured by application properties *per channel* (mainly properties like `mp.messaging.incoming|outgoing.my_channel`). Each connector uses various configurations on a channel to configure message broker client and establish connection with the broker. 

While by default the channel name is the topic/queue to which your application sends messages, you can override this.

If what you are trying to achieve is to send a message to a different topic dynamically, you can do that as well.
You need to configure the metadata of your outbound message. This is described [here for kafka](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.6/kafka/kafka.html#_dynamic_topic_names) and [here for amqp](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.6/amqp/amqp.html#_dynamic_address_names).

**Comment by phelioz** [comment]
Yeah what I really was trying was to send messages to different topics dynamically and that fixed it for me, must have missed it when reading the docs. 
Thanks for the help, appreciate it! 👍

**Comment by Ladicek** [comment]
For the record, it should be possible to lookup the `Emitter` object from the CDI container programmatically (`CDI.current()` etc.). But using metadata for dynamic addressing is definitely better, if that's what you're after.
