### ISSUE TITLE
Change consumer rebalance listener name property to identifier

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#1303]
`@Named` is not suggested anymore to be used to identify the ConsumerRebalanceListener beans.
 It'd be best to rename the 
`mp.messaging.incoming.$channel.consumer-rebalance-listener.name` property to `mp.messaging.incoming.$channel.consumer-rebalance-listener.identifier`.

**Comment by Ladicek** [comment]
I personally think `name` is fine and can stay, but I also see how the rename is appealing :-)

**Comment by cescoffier** [comment]
We would need to support both for a bit of time if we decide to switch.
