### ISSUE TITLE
Messages not sent from Flowable with too short interval

### ISSUE THREAD

**Issue by gunnarmorling** [smallrye/smallrye-reactive-messaging#132]
Playing with the Quarkus KStreams quickstart, I noticed some weird behavior: the producer won't send more than one event when using an interval of 100ms. It's still working with 250 ms. So this is failing:

    @Outgoing("temperature-values")
    public Flowable<KafkaMessage<Integer, String>> generate() {

        return Flowable.interval(100, TimeUnit.MILLISECONDS)
                .map(tick -> {
                    WeatherStation station = stations.get(random.nextInt(stations.size()));
                    double temperature = new BigDecimal(random.nextGaussian() * 15 + station.averageTemperature)
                            .setScale(1, RoundingMode.HALF_UP)
                            .doubleValue();

                    LOG.info("station: {}, temperature: {}", station.name, temperature);
                    return KafkaMessage.of(station.id, Instant.now().toEpochMilli() + ";" + temperature);
                });
    }

**Comment by cescoffier** [comment]
What's the failure? 

Also, from the `interval` operator documentation:
```
The operator generates values based on time and ignores downstream backpressure which may lead to MissingBackpressureException at some point in the chain. Consumers should consider applying one of the onBackpressureXXX operators as well.
```

**Comment by gunnarmorling** [comment]
No failure, exception whatsoever. It just stops doing anything.

>

**Comment by cescoffier** [comment]
I reproduce the issue and as expected it's a back pressure issue because of the interval operator:
`io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 1 due to lack of requests`

You need to use `onBackPressureDrop()`:
```
 return Flowable.interval(100, TimeUnit.MILLISECONDS)
        .onBackpressureDrop()
```

In my test, I got an error reported:
```
2019-06-17 09:05:11,806 ERROR     Unable to dispatch message to Kafka (io.smallrye.reactive.messaging.kafka.KafkaSink)
io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 1 due to lack of requests
	at io.reactivex.internal.operators.flowable.FlowableInterval$IntervalSubscriber.run(FlowableInterval.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cescoffier** [comment]
If you use `onBackPressureBuffer()`, you should receive something like:
`io.reactivex.exceptions.MissingBackpressureException: Buffer is full`

**Comment by cescoffier** [comment]
If you use `onBackPressureBuffer()`, you should receive something like:
`io.reactivex.exceptions.MissingBackpressureException: Buffer is full`

**Comment by gunnarmorling** [comment]
Thanks for exploring!

So in my case I didn't see any feedback whatsoever in the logs, it just
stopped doing anything. Is this expected? Can something be logged also when
not using that other method you suggest?

In terms of backpressure, I guess it makes sense, but it seems to kick in
way too early. 10 messages per second is short to nothing, so something
must be wrong, like a buffer that's too small by default. I'd expect to be
able to send 10Ks to 100Ks messages/s to Kafka really.

>

**Comment by cescoffier** [comment]
This is because of the `write`. Reactive Messaging waits until the _write_ operation completes (so wait for the acks), which takes time.

I just added the `waitForWriteCompletion` (`true` by default) to control this.
