### ISSUE TITLE
Kafka connector performance issue with 3.5

### ISSUE THREAD

**Issue by loicmathieu** [smallrye/smallrye-reactive-messaging#1331]
We detect a performance regression when migrating our application from Quarkus 1.13 to Quarkus 2.0, that includes Smallrye Reactive Messaging Kafka 3.5.

The detail of the issue and the research done on the subject can be found here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Smallrye.20Reactive.20Messaging.20Kafka.20Quarkus.202.20Thread.20blocked

Observation: When using manual message acknowledge (calling directly msg.ack() on an incomming message) toughtput goes from 100k msg/min to 25k msg/min. We discover Vert.x threads blocked on random stack (but a lot on SR reactive messaging related classes). Performance profile seems to be dominated by samples on `java.util.concurrent.ConcurrentLinkedDeque.size` called from `io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription.run`.

We worked around the issue by forwarding the ack (building the outgoing message from the incomming one), after this change the toughput is back to normal (or even higer).

**Comment by cescoffier** [comment]
@ozangunalp @Ladicek I've seen some investigation. Has the regression being identified?

**Comment by ozangunalp** [comment]
This has been fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/1339. Forgot to mention it in a commit message.

**Comment by cescoffier** [comment]
Thanks @ozangunalp !
