### ISSUE TITLE
Default deserialization failure handler is danger

### ISSUE THREAD

**Issue by Dieken** [smallrye/smallrye-reactive-messaging#1350]
https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/fault/DeserializerWrapper.java#L139

```java
    private T tryToRecover(String topic, Headers headers, byte[] data, Exception exception) {
        if (deserializationFailureHandler != null) {
            try {
                return (T) deserializationFailureHandler.handleDeserializationFailure(topic, this.handleKeys,
                        delegate.getClass().getName(), data, exception, headers);
            } catch (Exception e) {
                KafkaLogging.log.deserializationFailureHandlerFailure(deserializationFailureHandler.toString(), e);
                source.reportFailure(e, true);
            }
        } else {
            KafkaLogging.log.unableToDeserializeMessage(topic, exception);   // <---- danger!!!
        }
        return null;
    }
```

I use Quarkus + smallrye-reactive-messaging to consume AVRO message produced by Debezium from MySQL binlog, I'm surprised the consumer offset is still advanced even when Quarkus fails to deserialize.

Isn't it safer to just fail Kafka consumer when there is no failure handler?

**Comment by cescoffier** [comment]
This is the behavior that has been chosen when we designed the feature. 
After a few months, yes, I believe it would be safer to fail and stop and only skip the message if the user specifically configured it.

So basically, we would add a new configuration attribute (something like `deserialization-failure-strategy` (with two values: fail (default), skip). Note that this setting will only be used if there is no deserialization handler.

**Comment by Ladicek** [comment]
I agree we should fail by default, even if that's a breaking change.
