### ISSUE TITLE
Replaying from a Kafka Topic Broken with Out of Memory

### ISSUE THREAD

**Issue by pcasaes** [smallrye/smallrye-reactive-messaging#1377]
On of our use cases is replaying a kafka topic in order to build a state from 0.
It looks like the new reactive kafka consumer never stops polling from kafka and filling up a queue in KafkaRecordStream.

This TODO is very suspicious
https://github.com/smallrye/smallrye-reactive-messaging/blob/5296684541b3bcad5bdfc65c3db4666a0350c3e3/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaRecordStream.java#L69

We were able to confirm from heap dumps that the referenced queue is the culprit (more than 100k records).

**Comment by pcasaes** [comment]
Version 3.7.1 on Quarkus 2.1

**Comment by pcasaes** [comment]
This might solve this issue

https://github.com/smallrye/smallrye-reactive-messaging/pull/1339

**Comment by cescoffier** [comment]
Can you try to override the reactive messaging version to 3.9.1?

**Comment by Ladicek** [comment]
Also, do you have `pause-if-no-requests` configured to `false`? If not, there would probably be a bug elsewhere.

**Comment by pcasaes** [comment]
3.9.1 resolves the issue! 

On 3.7.1 changing `pause-if-no-requests` has no effect. With it set to true the channel would still keep requesting so the consumer would never pause. #1339 solves it by making the queue the deciding factor to pause and not whether requests were being made.

Thanks everybody!

**Comment by pcasaes** [comment]
It would be nice to have some metrics around the queue size and the state of the pause.
