### ISSUE TITLE
Hyphenation in attribute names on doc website

### ISSUE THREAD

**Issue by antoniomacri** [smallrye/smallrye-reactive-messaging#1381]
Looking at:

https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.9/kafka/kafka.html

I noticed the incoming `bootstrap.servers` attribute is shown as `boot-strap.servers` on my browser:

<img width="850" alt="Screenshot 2021-08-27 at 11 45 48" src="https://user-images.githubusercontent.com/1660048/131108307-42b64437-2b5b-4c47-ac61-dd4811b4056c.png">

Maybe better to disable hyphenation on attribute names or code parts? It may be misleading.

Sorry if this is not the correct place to report this "issue".

**Comment by cescoffier** [comment]
Ah ah, found a CSS trick! 
It requires modifying the attributes to tables converter and add a CSS rule. But it works.

**Comment by antoniomacri** [comment]
Uh, great!
