### ISSUE TITLE
Incoming asynchronous messages

### ISSUE THREAD

**Issue by manuelrf** [smallrye/smallrye-reactive-messaging#1382]
Hello, 

I would like to ask a question concerning incoming messages.

We are seeing in Kafka, when we receive these messages are processed synchronously, these messages require a long-term operational, approximately 20 seconds before ack

Is it possible to receive each message as it arrives in different threads and not block other messages?

I don't sure if it is a configuration error or it's working as expected, it's the first time we use reactive messages

Thanks in advance.

**Comment by cescoffier** [comment]
Yes, it's possbile. 
In the next version (3.10) it will be a lot easier than it is today, but here is what would work today:

```java

Executor executor = Executors.... // Your thread pool

@Incoming(...)
@Acknowledgement(Strategy.MANUAL)
public CompletionStage<Void> consume(Message<T> message) {
    try {
    executor.submit(() -> { 
            try { 
                 //    handle your message
                message.ack();
           }  catch(Exception e) {
               message.nack();
           }
    });
    return CompletableFuture.completed(null);
} catch(Exception e) {
   return message.nack(); // handle rejected operation exception 
}

}
```

**Comment by manuelrf** [comment]
ok, thank you very much, creating the thread pool we can manage them asynchronously, and not blocking other incoming messages.
