### ISSUE TITLE
kafka protobuf support

### ISSUE THREAD

**Issue by msillence** [smallrye/smallrye-reactive-messaging#1393]
The documentation mentions support for avro: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.9/kafka/kafka.html

specifically:

```
mp.messaging.incoming.[channel].value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.[channel].schema.registry.url=http://<your_host>:<your_port>/
mp.messaging.incoming.[channel].specific.avro.reader=true
```

the obvious change to support protobuf is 

`mp.messaging.incoming.[channel].value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer`

and I do see a com.google.protobuf.DynamicMessage deliverd to my consumer but I'm less clear on how to make it deserialise to the correct specific object and what the reader should be or even if that is supported
the obvious has no effect:

`mp.messaging.incoming.[channel].specific.protobuf.reader=true`

**Comment by msillence** [comment]
Found the documentation here:
https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html

adding the following lines worked for me:

mp.messaging.incoming.figaro-currency.specific.protobuf.value.type=....Key$Key
mp.messaging.incoming.figaro-currency.specific.protobuf.key.type=....Value$Value

I've not manged to persuade the autodetection to work with .derive_type=true

Shall I create a PR for the docs?

**Comment by cescoffier** [comment]
Auto-detection only works in Quarkus and has not been implemented for Protobug (@ozangunalp / @Ladicek). 
That being said, a PR updating the doc is more than welcome!

**Comment by Ladicek** [comment]
Protobug is a lovely typo :rofl:

**Comment by msillence** [comment]
I am using quarkus, any hints on configuring it would be welcome. Looking at the code it seems it's `derive.type` and not `derive_type`

`mp.messaging.incoming.[chanel].derive.type=true`

generates lots of errors saying I need to set either `java_outer_classname` or `java_multiple_files` and setting them doesn't make the error go away. I'm only consuming the messages here so may be there's some magic on the producer when this is set. When I look at the topic in kafka I can see the type so I'm not quite sure why it doesn't pick it up in the same way as avro but from the code I've explored that is going to be a confluent question.

I presumed that protobug was not a typo but bitter experience? Any warnings for someone new?

I based the PR on the avro docs and I've only used confluent registry so I've not added anything for Apicurio

**Comment by cescoffier** [comment]
What's the status of this issue? We merged the documentation PR. Is there anything else?

**Comment by msillence** [comment]
I'm happy to close.

I presume if anyone needs Apicurio that can be raised as a seperate issue.

I think I now understand the derive type problem - we need the code generating the schema to include the optional java_outer_classname parts and debezium is not doing that so that problem lies elsewhere.

**Comment by cescoffier** [comment]
Let's close it, we can add apicurio later.
