### ISSUE TITLE
Consider switching to Weld Junit

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#14]
It would simplify the tests:
https://github.com/weld/weld-junit

**Comment by francois-travais** [comment]
I used weld junit here in the MQTT server connector tests [here](https://github.com/smallrye/smallrye-reactive-messaging/tree/master/smallrye-reactive-messaging-mqtt-server/src/test/java/io/smallrye/reactive/messaging/mqtt/server)

**Comment by cescoffier** [comment]
Closing - out of date.
