### ISSUE TITLE
Kafka Throttled commit strategy sometimes fails to commit after a consumer rebalance

### ISSUE THREAD

**Issue by pcasaes** [smallrye/smallrye-reactive-messaging#1403]
Symptom: After a consumer rebalance there's a chance that the throttled commit strategy will _break_ and stop commiting for one or more assigned partitions. This will only occur if using a non sticky consumer assignor (the default) and the chances increase if the consumer is far behind, ie: during a replay. A secondary symptom I noticed was having the commited offset go back after a rebalance.

Cause: As of 3.9.1 the throttled commit strategy implementation isn't idempotent
Per topic partition it expects to always receive records newer then ones already received. The new reactive consumer keeps a queue of polled records that persists over a rebalance. After a rebalance the vanila kafka consumer will rewind to the latest commit offset (even for topics partitions that stayed with their consumer instances) and duplicate records wrt to the already filled queue. The old vertx kafka consumer didn't keep a buffered queue or implement flow control so it wasn't an issue (side note: big fan of this new reactive consumer with flow control).

Work Around: Configure the [CooperativeStickyAssignor](https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/consumer/CooperativeStickyAssignor.html). The kafka docs suggest this assignor over the default "Users should prefer this assignor for newer clusters." With this assignor the consumer won't rewind for topic partitions that aren't moved to other instances. Note: Upgrading to the sticky assignor is not trivial, see kafka docs!

Current fix: Make the commit strategy idempotent
This is simple enough and https://github.com/smallrye/smallrye-reactive-messaging/pull/1396/ fixes the issue. Kudos @ozangunalp 

But breaking the throttled commit strategy isn't the only issue caused by keeping messages from revoked partitions in the queue. Keeping these messages in the queue will increase the chances of duplicates and worse increase the chances of concurrent processing of the same record. Concurrent record processing can have performance implications depending on the application, ie: database locks (the first sign I noticed of this issue was from a collegue who reported lots of database locks for 1-2 minutes after a rebalance). In the case of a replay or slow consumer we can end up processing 6 times the batch size which also has performance implications.

Proposal: On revoke clear the queue of records from revoked topic partitions. 
On the default Round Robin assignor this effectively means we'll flush the queue entirely since with that assignor all topic partitions are always revoked. With a sticky assignor only the revoked partitions will be cleared. 

FYI: @cescoffier

**Comment by cescoffier** [comment]
Which version are you using? We recently did a long analysis and fix a few things in the commit strategy.

**Comment by cescoffier** [comment]
Closed by #1404
