### ISSUE TITLE
Kafka consumer and producer with kotlin coroutines examples

### ISSUE THREAD

**Issue by ericsouza** [smallrye/smallrye-reactive-messaging#1405]
Is there any example to use Kafka both consumer and producer with kotlin coroutine?

**Comment by cescoffier** [comment]
Not that I'm aware, but I've seen it working (in Quarkus).

**Comment by ericsouza** [comment]
@cescoffier do you have any quickstart link for this using quarkus? I'm evaluating a full reactive stack with kotlin

**Comment by cescoffier** [comment]
There is some info there: https://quarkus.io/guides/kotlin#kotlin-coroutines-and-mutiny - but not that much. Any contribution is more than welcome. I'm not a Kotlin developer, so it's hard for me to build something outside of the very basic things.

**Comment by ericsouza** [comment]
I see. Well, thanks a lot for your work with reactive stuff!!
