### ISSUE TITLE
ClassCastException in KafkaRecordStream

### ISSUE THREAD

**Issue by pfaffn** [smallrye/smallrye-reactive-messaging#1406]
Hi, I am currently migrating a kafka consumer service from Quarkus 1.13.7.Final to 2.2.2.Final and have possibly found a bug in your class `KafkaRecordStream`. 

Quarkus 2.2.2 uses smallrye-reactive-messaging-kafka version 3.9.1 (quarkus 1 uses some 2.x version).

In `KafkaRecordStream` line 59 in its private class `KafkaRecordStreamSubscription` the value of `max.poll.record` is cast to an Integer if present, else set to default 500.

When setting `max.poll.records=50`(or any value) in my application.properties, the value in KafkaConnectorIncomingConfiguration is somehow interpreted as a String and hence the ClassCastException is thrown:

```
ERROR [io.qua.mut.run.MutinyInfrastructure] (smallrye-kafka-consumer-thread-0) Mutiny had to drop the following exception: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription.<init>(KafkaRecordStream.java:79)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream.subscribe(KafkaRecordStream.java:41)
        at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:40)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToMulti$FlatMapPublisherSubscriber.onItem(UniOnItemTransformToMulti.java:127)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:36)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:29)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

A screenshot of my debugger.
![Bildschirmfoto 2021-09-13 um 15 53 58](https://user-images.githubusercontent.com/62337610/133098907-cfe6c5d7-a027-42b9-becf-a63a478b64eb.png)

Temporary workaround is obviously not setting max.poll.records. But can you confirm that this is indeed an issue in smallrye-reactive-messaging and whether it will be fixed?

**Comment by cescoffier** [comment]
It was a bug. "max.poll.records" is intended to be an integer, not a String.
But what you say concerns me. Are you saying that you cannot configure `max.poll.records` anymore?

**Comment by cescoffier** [comment]
@radcortez For my own curiosity, shouldn't the converters convert the String into Integer?

**Comment by pfaffn** [comment]
Yes, I cannot configure it because it would always lead to the exception. So it uses always the default 500.

**Comment by cescoffier** [comment]
Thanks, Definitely a bug. I'm on it.

**Comment by pfaffn** [comment]
Thanks and good luck!

**Comment by radcortez** [comment]
> @radcortez For my own curiosity, shouldn't the converters convert the String into Integer?

Yes. That is super weird because a String to Integer converter is registered as default.

**Comment by cescoffier** [comment]
Working on a patch right now using the `ConfigValue` which is always a String (getValue() returns a String). Not very happy, but should make it work. 

About the converter, it is because of the Optional?

**Comment by radcortez** [comment]
> About the converter, it is because of the Optional?

No, it works for Optionals as well. Let me have a look.

**Comment by cescoffier** [comment]
There is the ConnectorConfig in the way, but it delegates to the overall config.

**Comment by radcortez** [comment]
I noticed that in tests a `MapBasedConfig` implements `Config` and the implementations of `getOptionalValue` completely ignores the the conversion type:

https://github.com/smallrye/smallrye-reactive-messaging/blob/c6df05d53d442f7c1cf798b2850399e852db2704/test-common/src/main/java/io/smallrye/reactive/messaging/test/common/config/MapBasedConfig.java#L99-L104

I see other `Config` implementations in the project. While it is ok to reimplement stuff, I think regarding `Config` it is somehow dangerous it may behave differently. Maybe we need to revise this and move any required behaviour to SR Config, so you don't require these different implementations?

**Comment by cescoffier** [comment]
The MapBasedConfig is only used in tests. It should not matters.

The ConnectorConfig is where things can be more tricky. Unfortunately, there is nothing we can do (it's mandated by the spec):
https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConnectorConfig.java

**Comment by radcortez** [comment]
Ok, let me have a look into that one.

**Comment by radcortez** [comment]
@pfaffn can you please also provide us a reproducer to make sure we are looking in the right place? Thanks!

**Comment by cescoffier** [comment]
Oh, I've one - Let me share it:
[Archive.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/7156428/Archive.zip)

It's a quarkus app overriding the Kafka connector version to the snapshot one.
If you start it in dev mode, it should crash with the class cast exception.

**Comment by cescoffier** [comment]
Sorry,m it won't reproduce it. I may be found the problem, and it's not a conversation problem (at least it's not obvious).
This configuration fails:
```
kafka.max.poll.records=50
```

It fails with:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription.<init>(KafkaRecordStream.java:79)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream.subscribe(KafkaRecordStream.java:41)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:40)
```

This configuration works:
```
mp.messaging.incoming.foo.max.poll.records=50
```

You may wonder how does that matter? 
The `kafka.x` attributes are extracted by Quarkus which creates a `Map<String, ?>`. This map is then used in the connector to configure the Kafka client.  To do that, the configuration from SR Config and the maps are _merged_, and I'm pretty sure the problem from from there...

**Comment by cescoffier** [comment]
Confirmed - the merge is broken

**Comment by cescoffier** [comment]
(And I have a fix).

However, @radcortez, I'd like to talk to you about that _merge_. If we can find a better way that would be great. This is done in `io.smallrye.reactive.messaging.kafka.KafkaConnector#merge`.

**Comment by pfaffn** [comment]
Hey, can confirm, using `mp.messaging.incoming.foo.max.poll.records` does fix the issue. Thx! I understand you don't need a reproducer anymore - correct?

**Comment by cescoffier** [comment]
no, thanks @pfaffn, I built one myself.

**Comment by radcortez** [comment]
> However, @radcortez, I'd like to talk to you about that _merge_. If we can find a better way that would be great. This is done in `io.smallrye.reactive.messaging.kafka.KafkaConnector#merge`.

Ideally, the map configuration should go to a low-level source. The problem is that it means that we need to hook up a mutable source so we can update it. 

A better option might be to create an actual `Config` instance with the `SmallRyeConfigBuilder`, with everything empty (except from Converters, and a source for the default kafka config) and keep the same login that you have, but instead of delegating to the map, it will delegate to an actual `Config` instance and behave in the same way regarding conversions, lookups, etc. What do you think?

**Comment by cescoffier** [comment]
It's even more complex, as in another PR it's not one Map, but multiple and the set of maps depends on the channel. So, I'm not sure it would work.

Also, I can't easily integrate a dependency to SmallRye Config in this connector. I need to check the usage first.

**Comment by radcortez** [comment]
We might be able to do it just with `ConfigProviderResolver.instance().getBuilder`. I believe we don't need anything specific from the `SmallRyeConfigBuilder`.

The other option is to go back to the mutable `ConfigSource` idea, so you can just add the values you need to a source and keep the same `Config` instance.

It worries me that we are relying on CDI for users to set configuration. The relationship between Config and CDI was always a bit problematic, especially considering if you want to use Config to configure CDI itself. We may want to discuss this and find an alternate way for users to provide the default without relying on CDI.

**Comment by cescoffier** [comment]
So, actually, while the mechanism is based on CDI, the user does not use that behavior directly. It's mostly for service bindings.
