### ISSUE TITLE
Saga pattern / LRA integration in microprofile for Apache Kafka

### ISSUE THREAD

**Issue by tryasta** [smallrye/smallrye-reactive-messaging#1419]
**Context:**
Narayana LRA has been integrated in [Quarkus 2.2.1](https://quarkus.io/blog/using-lra/) and it provides Saga orchestration for SOA. For our purposes it works sweet as. It is easy to use and we would love to use it in other scenarios as well.

**Question:**
Does smallrye provide support for LRA for Kafka topics?

**Request**:
Can it be supported by smallrye?

**Comment by cescoffier** [comment]
That's more a question for Narayana.
The problem is that you can't really compensate with Kafka. The only thing you can do is send another message that canceled the one you want to roll back. 
The consumer will see the 2 messages, and for a time window (between the two), will have a wrong state.

**Comment by tryasta** [comment]
After reading this article https://ibm-cloud-architecture.github.io/refarch-eda/patterns/saga/ I was hoping compensation in Kafka was possible. It seems to imply not all hope is lost. 

There are certainly some differences with the SOA approach. Not only orders are events. Compensation (and I guess Completion?) in this case is implemented via events, too.

**Comment by cescoffier** [comment]
Yes, that is correct. It’s going to be eventual consistent.
