### ISSUE TITLE
[Camel] Headers not forwarded through message processor

### ISSUE THREAD

**Issue by OpenGuidou** [smallrye/smallrye-reactive-messaging#1458]
Hello,

When using a message processor pattern, the headers are not forwarded between the incoming and outgoing messages.

`@Incoming("receiver-channel")
 @Outgoing("emitter-channel")
  public String ping(String ping)  {
    return "pong"
  }`
  
  I would expect the headers received with the ping message to be forwarded with the pong.

Looking at the CamelConnector code (createExchangeFromMessage), only the OutgoingExchangeMetadata is read, but in this case the headers come from the IncomingExchangeMetadata.

Would it be ok if I open a PR to read the headers from this metadata too ?

**Comment by cescoffier** [comment]
Fixed by #1460.
