### ISSUE TITLE
The link to Acknowledgement is broken

### ISSUE THREAD

**Issue by bennetelli** [smallrye/smallrye-reactive-messaging#1466]
Hi coworkers,

the link to "Achknowledgement" is broken here: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/acknowledgement/acknowledgement.html

I will open a PR and fix this issue.

**Comment by cescoffier** [comment]
hum, this is a very old URL. We are using 3.10, this one is for 2.0
