### ISSUE TITLE
Logging Kafka producer settings for emitter

### ISSUE THREAD

**Issue by shnplr** [smallrye/smallrye-reactive-messaging#1526]
Can we log actual config values used by the emitter kafka producer?

for example say I want to configure acks=all for all emitters, can property work like

```
kafka.acks=all
mp.messaging.connector.smallrye-kafka.acks=all
mp.messaging.outgoing.kafka.acks=all
mp.messaging.outgoing.acks=all
mp.messaging.outgoing.my-channel.acks=all
```

It would be great to see which setting actually works - I assume the last definitely will

**Comment by cescoffier** [comment]
If you are using Quarkus, set the log level of `org.apache.kafka.clients` to `INFO` and you will get the configuration of the producer and consumer.

```
quarkus.log.category."org.apache.kafka.clients".level=INFO
```

From the top of my head, the working configs are:

```
kafka.acks=all
mp.messaging.connector.smallrye-kafka.acks=all
mp.messaging.outgoing.my-channel.acks=all
```

Pick the one you prefer.

**Comment by shnplr** [comment]
Thanks, adding the logging category to Quarkus 2.4.2 app the ProducerConfig for the Emitter channels is now logged.

I ended up using the custom kafka-configuration option to pass a custom map (since its more flexible approach to configure dynamically based on non kafka. (kafak-streams) properties, & targeting both secure & unsecure kafka envs.

Thanks
