### ISSUE TITLE
Forward headers in kafka processor

### ISSUE THREAD

**Issue by OpenGuidou** [smallrye/smallrye-reactive-messaging#1535]
Hello,

Following https://github.com/smallrye/smallrye-reactive-messaging/issues/1458, it seems that the kafka headers are not  forwarded either between incoming channel and outgoing channel when using a processor.

Can I open a PR to add this feature ?

**Comment by ozangunalp** [comment]
One thing to be cautious about is that Serializers can add headers to the record.
That's why I think it can make sense to add this behind a flag, like the propagate record key feature (#1324).
Also, we should not override the existing headers in OutgoingKafkaRecordMetadata.

**Comment by cescoffier** [comment]
This feature makes sense.
As @ozangunalp said, it should be a flag, because it could leak sensible or ephemeral data.
