### ISSUE TITLE
MutinyEmitter send Message<?>

### ISSUE THREAD

**Issue by butwhoareyou** [smallrye/smallrye-reactive-messaging#1539]
Version: `3.13.0`
Package: `io.smallrye.reactive.messaging`
Expected behaviour: send method returns `Uni<Message<?>>`
Actual behaviour: send method returns `Message<?>`

As a user of MutinyEmitter I expect that every `send` method returns `Uni<?>` like `Uni<Void>` without `Message<?>` wrapper.
At this moment, the method `send` which wraps payload with `Message<?>`, subscribes internally and returns just `Message<?>` instead of `Uni<Message<?>>`.

Is it intentional design limitation?

**Comment by cescoffier** [comment]
Yes, it's intentional. 

When passing a message, you need to pass the ack and nack methods into the message. Because we cannot modify a `Message` instance, we cannot (and should not) change the ack and nack methods. 

So, in order to get a `Uni<Void>` you could use something like:


```java
public Uni<Void> emit(T myPayload) {
    return Uni.createFrom().emitter(e -> emitter.send(Message.of(myPayload, () -> {
             e.complete(); return CompletableFuture.completed(null);
    }, failure -> {
            e.error(failure); return CompletableFuture.completed(null);
  )
};
```

Change the message creation with what you need (metadata and so on)

**Comment by butwhoareyou** [comment]
Cool. That is what I thought to implement. 
Thanks for quick reply.

**Comment by butwhoareyou** [comment]
>  you need to pass the ack and nack methods into the message

As far I know, custom ack/nack are optional, so I can stay with `CompletableFuture.completedFuture(null)` theoretically. 

> Because we cannot modify a Message instance, we cannot (and should not) change the ack and nack methods.

Do you want modify ack/nack because of possible blocking operations inside ack/nack?

**Comment by cescoffier** [comment]
It would require changing the ack/nack to be notified of the completion/failure. That event is the one completion/failing the returned Uni.

Note that if you only pass a payload, then it returns a `Uni<Void>`, because in that case, I can pass my own ack/nack methods.

**Comment by butwhoareyou** [comment]
In my case I was thinking to map Uni of completion/failure to ack/nack completion stage and return the result as an output.
Something like (pseudo-code):

``` 
 Uni<Void> send(Message<T> message) {
        return Uni.createFrom()
            .item(message)
            .flatMap(m -> Uni.createFrom().emitter(e -> emit(m)))
            .flatMap(m -> Uni.createFrom().completionStage(message.ack()))
            .onFailure().recoverWithUni(throwable -> Uni.createFrom().completionStage(message.nack(throwable)));
    }
```

But I assume it is too "dirty hack" for the library.

Anyway, thanks for your help!
