### ISSUE TITLE
How to keep topic and channel name different?

### ISSUE THREAD

**Issue by chainhead** [smallrye/smallrye-reactive-messaging#1548]
As per [documentation](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/kafka/kafka.html#_example):

> You don’t need to set the Kafka topic. By default, it uses the channel name (prices). You can configure the topic attribute to override it. 

1. Can you show an example of _exactly_ how the topic attribute is to be overridden for both incoming and outgoing cases? 
2. Also, can a single channel map to multiple topics - incoming or outgoing?

**Comment by chainhead** [comment]
I think, [this](https://quarkus.io/guides/kafka#kafka-configuration) should help.

**Comment by cescoffier** [comment]
1. just use the `topic` attribute in your channel configuration:
```
mp.messaging.incoming.my-incoming-channel.topic=my-topic
mp.messaging.outgoing.my-outgoing-channel.topic=my-topic
```

(`topics` and `pattern` are also available for incoming)

2. multiple topics only work for incoming (writing to multiple topics would need multiple outgoing channels).  You can set the `topics` attribute to a comma-separated list of topics, or `pattern` which is a regexp.
