### ISSUE TITLE
Split packages between in-memory and messaging-provider

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-reactive-messaging#1571]
https://github.com/smallrye/smallrye-reactive-messaging/tree/main/smallrye-reactive-messaging-in-memory/src/main/java/io/smallrye/reactive/messaging/providers/connectors

https://github.com/smallrye/smallrye-reactive-messaging/tree/main/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/connectors

**Comment by radcortez** [comment]
It should be fine to change the packages in the in-memory module. It is unlikely that someone is using the APIs directly.

**Comment by ozangunalp** [comment]
@radcortez I also think that it'd be better to change the in-memory module package.
But the in-memory connector classes are documented (and are used) for testing applications: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.13/testing/testing.html

So it'll be a breaking change but cleaner than the other way around.

@cescoffier WDYT?

BTW I'll leave this here for x-ref: https://github.com/quarkusio/quarkus/issues/22837

**Comment by radcortez** [comment]
> So it'll be a breaking change but cleaner than the other way around.
 
Another option is to just create a new module and deprecate the current one.

> BTW I'll leave this here for x-ref: [quarkusio/quarkus#22837](https://github.com/quarkusio/quarkus/issues/22837)

Ops, I've missed that this was already reported on the Quarkus side.

**Comment by ozangunalp** [comment]
I was here to create the issue myself :)

**Comment by cescoffier** [comment]
It's a public API that is used, so we would need a deprecation cycle (at least 6 months). 
Before deprecating, we need an alternative implementation in a package that does not lead to a split-package.

**Comment by cescoffier** [comment]
Might be a good candidate for the jakarta version of RM (integrated into Quarkus 3).
