### ISSUE TITLE
Kafka connector: cloud event support perrormance issue

### ISSUE THREAD

**Issue by loicmathieu** [smallrye/smallrye-reactive-messaging#1574]
The Cloud Event support for the Kafka connector has some performance issue.

It uses the configuration on each message to get default configuration which lead to calls to `Config.getOptionalValue` .
Some profiles shows up to 10% samples on this method call.
Caching the config value (wich never changes) should improve performance.

CPU profile is attached. 
[profile-cpu.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/7887795/profile-cpu.zip)

I'll have a look to propose a PR to workaround this.

**Comment by cescoffier** [comment]
+1! 

AMQP is likely going to have the same issue.
