### ISSUE TITLE
Support AWS SNS Topic

### ISSUE THREAD

**Issue by iabughosh** [smallrye/smallrye-reactive-messaging#159]
Hello Dears,
I want to suggest adding AWS Simple Notification Service (SNS) for SmallRye Reactive messaging.

**Comment by cescoffier** [comment]
Definitely! 

Fancy a PR? I can help you if you need.

**Comment by iabughosh** [comment]
I would like to dedicate some time for it, I didn't do anything yet. I just want to check if it is good idea or not. If it is fine then I will start with it. For a start I need from you for a contribution guide. Also, is it mandatory to master Vert.x before begging with the implementation ?

Thanks.

**Comment by cescoffier** [comment]
@iabughosh not at all, you don't need to use Vert.x in a connector. We are having a discussion about Kinesis (#160)  giving you some details.

**Comment by iabughosh** [comment]
Great, I will start soon and keep you updated.

Thanks.

**Comment by iabughosh** [comment]
Hello @cescoffier ,
I already started on this but I want to discuss something with you. For topic subscription, best way is to use http(s) protocols. so we need some kind of servlet or rest url to consume topic messages.
My initial suggestion is to create Rest resource with standard url format ex : http(s)://host:port/(topicName). and to call that endpoint internally using rest client to generate message.

Looking forward to hear your response.

**Comment by cescoffier** [comment]
> On 7 Aug 2019, at 17:04, Ibrahim Abu Ghosh <notifications@github.com> wrote:
> 
> Hello @cescoffier ,
> I already started on this but I want to discuss something with you. For topic subscription, best way is to use http(s) protocols. so we need some kind of servlet or rest url to consume topic messages.
> 

Do you need to send a HTTP request or is it SNS calling you (pushing) the message to the application ? (So is it an outgoing http requests or incoming http requests)


> My initial suggestion is to create Rest resource with standard url format ex : http(s)://host:port/(topicName). and to call that endpoint internally using rest client to generate message.
> 
Depending on the direction, we can:

- use vertx web client to emit a HTTP request in a non blocking manner
- use vertx to create a lightweight (non blocking) http server

**Comment by iabughosh** [comment]
Once message is being received to SNS, it will be pushed automatically to the subscribed URL.

**Comment by cescoffier** [comment]
Ok, thanks for the clarification.

The easiest is to create a dedicated HTTP server as follow:

vertx.createHttpServer()
    .requestHandler( req -> manageSNSRequest(req))
    .listen(port)

The manage method should do something like:

AsyncProcessor processor = AsyncProcessor.create();

public void manageSNSRequest(HttpServerRequest req) {
SnsMessage msg = SnsMessage.from(req);
processor.onNext(msg);
}

**Comment by iabughosh** [comment]
Thanks for the reply @cescoffier , I will keep you updated.

**Comment by iabughosh** [comment]
Dear @cescoffier ,
I have successfully sent message to AWS SNS Topic through reactive messaging :). but in my test, I am sending multiple messages and only the first message is being processed. here is a a snapshot
of my code for handling the subscriber builder : 
`
    @Override
    public SubscriberBuilder<? extends Message<?>, Void> getSubscriberBuilder(Config config) {

        String topicName = getTopicName(config);
        return ReactiveStreams.<Message<?>> builder().flatMapCompletionStage(message -> {
            CompletionStage<Void> cs = CompletableFuture.runAsync(() -> {
               //send to sis
                send(message, topicName);
            });
            return cs;
        }).ignore();
    }
`

can you help on this regard ?

**Comment by cescoffier** [comment]
I'm pretty sure it's the "flatMapCompletionStage" trap (don't worry, I fell in this trap dozen of times). You must not return a `CompletionStage<Void>` as it propagates `null` as item in the stream and `null` is not a valid value. So use something like:

```
    String topicName = getTopicName(config);
    return ReactiveStreams.<Message<?>> builder().flatMapCompletionStage(message -> {
        CompletionStage<Void> cs = CompletableFuture.runAsync(() -> {
           //send to sns
            send(message, topicName);
        }).thenApply(x -> message);
        return cs;
    }).ignore();
```

Also, I would avoid using `runAsync` without having set a specific executor as it can behave oddly.

**Comment by iabughosh** [comment]
Great. It worked like a charm !!!. Thanks @cescoffier .
for the other part "publisher" I did the below :
`@Override
    public PublisherBuilder<? extends Message<?>> getPublisherBuilder(Config config) {

        String topicName = getTopicName(config);
        Integer port = config.getValue("port", Integer.class);
        boolean broadcast = config.getOptionalValue("broadcast", Boolean.class).orElse(false);
        SnsVerticle snsVerticle = new SnsVerticle(appURL.get(), topicName, port);
        vertxInstance.deployVerticle(snsVerticle);

        PublisherBuilder<? extends Message<?>> builder = ReactiveStreams
                .fromCompletionStage(CompletableFuture.supplyAsync(() -> {
                    //Is not working as expected.
                    SnsMessage<String> snsMsg = snsVerticle.pollMsg();
                    return snsMsg == null ? new SnsMessage<>("test") : snsMsg;
                }));

        if (broadcast) {
            return builder.via(MulticastProcessor.create());
        }

        return builder;
    }`

where SNSVerticle is a Vertx vertical that handles SNS messages and store it in a Q. I tried to pull messages from a Q like the above code (snsVerticle.pollMsg()) but it is not working well. what mistake I did here ?

Regards.

**Comment by cescoffier** [comment]
Can you post the SNSVerticle?

**Comment by iabughosh** [comment]
here you go : 
`@Override
    public void start(Future<Void> startFuture) {

        Router router = Router.router(vertx);
        router.route()
                .handler(BodyHandler.create())
                .method(HttpMethod.POST);
        router.post("/sns/" + topicName).handler(this::handleSns);
...}`

`private void handleSns(RoutingContext routingContext) {

        JsonObject snsNotification = routingContext.getBodyAsJson();
        LOG.info("Message received ...");

        messageManager.handleMessage(new ByteArrayInputStream(snsNotification.toBuffer().getBytes()),
                new DefaultSnsMessageHandler() {

                    @Override
                    public void handle(SnsNotification snsNotification) {
                        LOG.info("Handling new message ...");
                        SnsMessage<String> snsMessage = new SnsMessage<String>(snsNotification);
                        msgQ.add(snsMessage);
                        LOG.info("Q size is  " + msgQ.size());
                    }
                });
        routingContext.response().setStatusCode(200).end();
    }
`

**Comment by cescoffier** [comment]
Does it start the HTTP server? So you see your traces?

**Comment by iabughosh** [comment]
yeah it is starting up (I didn't post its code) and I am able to receive SNS message.

**Comment by cescoffier** [comment]
What's the type of `msgQ` ?

**Comment by iabughosh** [comment]
private java Q : 
private Queue<SnsMessage> msgQ = new ConcurrentLinkedQueue<SnsMessage>();

**Comment by iabughosh** [comment]
Shall I use Vertx event bus in this case ?!

**Comment by iabughosh** [comment]
Shall I replace msgQ with another verticle that listens to event bus ?

**Comment by cescoffier** [comment]
Look at the javadoc:
```
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html#poll()
`

**Comment by iabughosh** [comment]
Sounds good idea. Thanks @cescoffier, I will try it and inform you back with the results.

**Comment by iabughosh** [comment]
I tried this approach and it works only at the first time and it consumes only one message. after that, code is not executed again.

**Comment by iabughosh** [comment]
I tried this approach and it worked only for the first item, I had modified the implementation with two different changes which are : 

1. I used ReactiveStreams.fromPublisher instead of .fromCompletionStage.
2.I delayed the subscription of flowable to 2 seconds, because without delay after calling blockingQ.take main thread get sucked.

here is the new implementation : 
`@Override
    public PublisherBuilder<? extends Message<?>> getPublisherBuilder(Config config) {

        String topicName = getTopicName(config);
        Integer port = config.getValue("port", Integer.class);
        boolean broadcast = config.getOptionalValue("broadcast", Boolean.class).orElse(false);
        SnsVerticle snsVerticle = new SnsVerticle(appURL.get(), topicName, port);
        vertxInstance.deployVerticle(snsVerticle);

        Flowable<SnsMessage<String>> flowable = Flowable.fromCallable(() -> {
            SnsMessage<String> snsMsg = null;
            try {
                System.out.println("Inside flowable");
                snsMsg = snsVerticle.pollMsg();
            } catch (InterruptedException e) {
                LOGGER.error("Polling interrupted", e);
            }
            return snsMsg;
        }).repeatWhen(o -> o.concatMap(v -> Flowable.timer(1, TimeUnit.MILLISECONDS)))
                .delaySubscription(2000, TimeUnit.MILLISECONDS);

        PublisherBuilder<? extends Message<?>> builder = ReactiveStreams.fromPublisher(flowable);

        if (broadcast) {
            return builder.via(MulticastProcessor.create());
        }

        return builder;
    }`

after the above change it works fine. Kindly check it.

**Comment by iabughosh** [comment]
Dear @cescoffier ,
I am doing some code refactoring. if you OK with the above solution, I will share an initial pull request with you.

Regards.

**Comment by cescoffier** [comment]
What does `pollMsg` use under the hood? `poll` or `take`. IF need to check it's not `null` in both case (if you have been interrupted).

**Comment by iabughosh** [comment]
it now use take. incase of null while using take it will block until new item is received. I think no need for null check.

**Comment by cescoffier** [comment]
Can't `take` be interrupted?
What does happen when the JVM / application stops?

**Comment by iabughosh** [comment]
Yes It can be interrupted. but I tried to stop/terminate the application it shutdown gracefully. Do I need to handle anything else ex: add retryWhen to flowable ?

**Comment by cescoffier** [comment]
Just handling the `null` case and throwing an exception in this case (which would terminate the stream) should be enough.

**Comment by iabughosh** [comment]
👍

**Comment by iabughosh** [comment]
Dear @cescoffier,
An initial pull request. Code documentation, unit tests, README will be added in later pull requests.

Thanks.

**Comment by iabughosh** [comment]
Dear @cescoffier ,
I am doing unit/integration test to the connector. I have successfully completed source test but I am stuck with sink, here is my code snippet for sink : 
`private void send(String msg, String topic) {
    	
    	SubscriberBuilder<? extends Message<?>, Void> subscriber = 
    			createSinkSubscriber(topic);
    	Flowable.fromArray(msg, msg, msg)
    		.map(m -> Message.of(m))
    		.safeSubscribe((Subscriber)subscriber.build());
    }
    
    private SubscriberBuilder<? extends Message<?>, Void> createSinkSubscriber(String topic) {

        Map<String, Object> config = new HashMap<>();
        config.put("connector", SnsConnector.CONNECTOR_NAME);
        config.put("address", topic + "-transformed");
        
        SnsConnector snsConnector = new SnsConnector();
        System.out.println("Building sink");
        return snsConnector.getSubscriberBuilder(new MapBasedConfig(config));
    }`

the problem that send method inside my connector is not being called. any ideas ?

**Comment by iabughosh** [comment]
Issue resolved. in unit testing executor is not getting initialized.

**Comment by iabughosh** [comment]
Code review notes has been resolved. kindly check the updated PR.

**Comment by cescoffier** [comment]
Fixed in master.
