### ISSUE TITLE
Pausing kafka channels via KafkaClientService does not work

### ISSUE THREAD

**Issue by MichaelMiles** [smallrye/smallrye-reactive-messaging#1592]
Env:
    Quarkus - 2.6.2.Final
    Java - openjdk 11.0.11

Issue: 

The sample repo https://github.com/addebartek/pause-flap can reproduce the scenario where pausing a channel with https://quarkus.io/guides/kafka#kafka-bare-clients does not work. More specifically, if the channel is paused through `KafkaClientService`, it is possible it will get resumed by `KafkaRecordStreamSubscription` due to attribute `pause-if-no-request=true`. For more information, please read the README inside the repo.

Another small note on another potential bug, for the attribute `pause-if-no-requests`, no matter set it as per channel or global, the attribute takes affect but Quarkus still warns that it is not a known config as shown below:

`WARN  [org.apa.kaf.cli.con.ConsumerConfig] (Quarkus Main Thread) The configuration 'pause-if-no-requests' was supplied but isn't a known config.`

**Comment by ozangunalp** [comment]
Thanks for the sample repo, the issue description is very clear.
`pause-if-no-requests` provides an automatic way of handling pause/resume of the Kafka consumer.
If you'd like to pause/resume manually, why not disable `pause-if-no-requests`?

**Comment by cescoffier** [comment]
We probably should mention that in the javadoc. If you need to pause/resume manually, you should disable RM automatic pause/resume.

**Comment by MichaelMiles** [comment]
HI all, If we pause manually, we would expect either `KafkaRecordStreamSubscription` to check for manual pauses in its `pauseResume` logic or for our manual pausing attempt to fail / throw with some clear message about `pause-if-no-requests`

**Comment by MichaelMiles** [comment]
And yes, it would be great to mention that if to pause/resume manually, `pause-if-no-requests` should be disabled.

**Comment by cescoffier** [comment]
I've added a few sentences to the javadoc and also opened #1649.
