### ISSUE TITLE
record.nack() behavior not as expected for headers

### ISSUE THREAD

**Issue by LazaroR94** [smallrye/smallrye-reactive-messaging#1595]
Hello, I have recently implemented the DLQ failure-strategy in my application and have been monitoring behavior on how the DLQ works in the reactive-messaging library. I have gathered this information from the official documentation:

```
The record written on the dead letter topic contains the original record’s headers, as well as a set of additional headers about the original record:

dead-letter-reason - the reason of the failure (the Throwable passed to nack())
dead-letter-cause - the cause of the failure (the getCause() of the Throwable passed to nack()), if any
dead-letter-topic - the original topic of the record
dead-letter-partition - the original partition of the record (integer mapped to String)
dead-letter-offset - the original offset of the record (long mapped to String)
```

If I understand correctly from above, if a message is _nacked_ properly with a Throwable argument then that Throwable itself gets passed along as metadata to the DLQ. However, whenever I try and check if the header(s) exist I am seeing that the metadata is coming as **null**. Is my understanding correct about the strategy itself sending these headers by default when a Throwable argument is present or do I need to configure something else in order to get the error message in my metadata for my DLQ?

This is currently what I am doing to retrieve the metadata and specific header(s):

```
val metadata = record.getMetadata(IncomingKafkaRecordMetadata::class.java).orElse(null)
        val cause: String? = metadata?.headers?.lastHeader("dead-letter-cause")?.let { String(it.value()) }
        if (cause != null) {
            log.info(
                "someID={} was nacked due to={}",
                someID,
                cause
            )
        }
```

**Comment by cescoffier** [comment]
Do you have a reproducer? It should pass the error message as the header's value. 
Note that we don't serialize the exception, but just use `getMessage()`.

**Comment by LazaroR94** [comment]
I'm sorry, but what is meant by a *reproducer*? The message(s) that come into the final DLQ are only persisted to a database and not retried in any way as that was done by the primary Kafka consumer.

**Comment by cescoffier** [comment]
A reproducer is a small project reproducing the issue you are seeing. So, I can quickly jump into it and debug it / fix the bug if any. 

Just create a small project on GitHub that I can use to reproduce the issue.

**Comment by LazaroR94** [comment]
Sure. I have created a small and simple project so that you may try and reproduce this: [Smallrye Kafka Test](https://github.com/LazaroR94/smallrye-kafka-test)

**Comment by cescoffier** [comment]
Can you also invite @ozangunalp ?

**Comment by LazaroR94** [comment]
He has been invited

**Comment by LazaroR94** [comment]
I assume the issue here lies not on the actual metadata itself (offset, topic, et.c) but the headers of that message not getting populated at all.

**Comment by ozangunalp** [comment]
Sorry, it took me some time to look at this. 
Looking at your reproducer, I noticed a couple of problems:

1/ In testDlqViaApi, as you are using a MutinyEmitter to produce records to the kafka topic, you need to chain the Uni returned by the `emitter.send` method. As in 

```java
Uni.createFrom().voidItem().call { -> emitter.send(payload) }
```

2/ I don't think `onFailure().call` in both consume methods is doing what you are expecting to do. It will still propagate the upstream failure to the downstream, whereas with DLQ you are willing to nack the message and continue the stream.
If you use `.onFailure().recoverWithUni` it'll behave as you expect.

3/ In DeadLetterTopicReader you are looking for the `dead-letter-cause` header but the failure message is inside the `dead-letter-reason` header. `dead-letter-cause` is present when the failure exception has a cause.

4/ I didn't get the inclusion of `@Outgoing("smallrye-test-secondary")` in KafkaEventHandler.

**Comment by LazaroR94** [comment]
Thank you @ozangunalp. I have actually started seeing the DLQ logs come now with the correct **nack** headers so I _believe_ the problem resolved itself. 

To your second point, are you saying that I should `recoverWithUni` on my initial call to the DLQ? Or should I be using `recoverWithUni` on both consume methods?
