### ISSUE TITLE
NoSuchMethodError after Quarkus 2.7.1 uplift

### ISSUE THREAD

**Issue by LazaroR94** [smallrye/smallrye-reactive-messaging#1609]
Hello, I have recently upgraded my Quarkus version to 2.7.1 and all Quarkus packages along with it. I have come to a strange issue in which I am receiving in my Gradle "test" phase and also when I run the application locally that I can only assume has to do with reactive messaging from what I can tell from the very limited stack trace. Can I get some assistance in understanding what is wrong here? I have not changed anything after the version uplift (2.6->2.7).

`ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoSuchMethodError: io.smallrye.config.ConfigValue.getNameProfiled()Ljava/lang/String;
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:407)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:263)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:179)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)`

**Comment by cescoffier** [comment]
That does not look like a reactive messaging issue. @radcortez any idea?

Did you "clean" after updating?

**Comment by LazaroR94** [comment]
@cescoffier Did any smallrye-kafka related changes happen inside the actual configuration following this new release? Maybe something new is missing that I may need but not know it.

**Comment by LazaroR94** [comment]
I have also just tested this by downgrading to version 2.6.3 and everything works as planned. I should note, the only dependency that was added by me to the application was the new reactive-oracle-client.

**Comment by cescoffier** [comment]
Nothing from smallrye reactive messaging, but between quarkus 2.6 and 2.7 there are close to 1000 commits in Quarkus. Can you report the error in Quarkus, as it seems related?

**Comment by radcortez** [comment]
> That does not look like a reactive messaging issue. @radcortez any idea?

The `getNameProfiled()` method was added here:
https://github.com/smallrye/smallrye-config/commit/9fdb499e168b46f6031b8af7b8fef309d8fc6101

And released with SR Config 2.8.0. This was updated for Quarkus 2.7.0:
https://github.com/quarkusio/quarkus/pull/22423

My guess is that a wrong dependency of SR Config is available at the classpath. @LazaroR94 any chance you can provide a reproducer? Can you confirm that you are not setting the SR Config dependency manual somehow? Can you confirm the SR Config version being included?

**Comment by LazaroR94** [comment]
@radcortez How can I check that exactly? What is the SR dependency that you are referring to? It is hard to reproduce this as it seems it may just be a version mismatch of some sort, but I am trying to duplicate this in a new application.

A bit off-topic, but what would the the correct URI syntax for the new oracle client? I am used to using this for JDBC: jdbc:oracle:thin@host:port/SEID - but that causes an incorrect URI syntax.

**Comment by radcortez** [comment]
> @radcortez How can I check that exactly? What is the SR dependency that you are referring to? It is hard to reproduce this as it seems it may just be a version mismatch of some sort, but I am trying to duplicate this in a new application.

The dependency is `io.smallrye.config:smallrye-config`. You should be able to check the dependencies with `gradle -q dependencies`.

**Comment by LazaroR94** [comment]
So I was able to bypass this just now by enforcing a version on the smallrye-config dependency:

`configurations.all {
        if (requested.group == "io.smallrye.config") {
            useVersion("2.9.0")
            because("Versions below 2.9.0 cause a specific SR config error")
        }
    }
}`

**Comment by LazaroR94** [comment]
This is a multi module product with only two modules "main" and "test". The Quarkus BOM did not override all dependencies as far as I can tell because from the dependency tree view I can see different versions scattered throughout different dependencies. The only way to bypass this is to not use the 2.8.2 version in the application and instead use `2.9.0`.

**Comment by radcortez** [comment]
But `2.8.2` already includes the missing method. It was added in `2.8.0`, so the version you are getting has to be lower than that.

Aren't you able to just remove all the code and remove any internal dependencies you have from the gradle files?

**Comment by cescoffier** [comment]
Closing - not a reactive messaging issue. Please reopen in the Quarkus core repository.
