### ISSUE TITLE
Support for single-active-consumers in RabbitMQ Connector

### ISSUE THREAD

**Issue by fndejong** [smallrye/smallrye-reactive-messaging#1626]
First of all, a big thanks for providing a really awesome library!

We're currently transitioning our microservices from Spring Boot to Quarkus. Therefore, all our new systems should be coded in Quarkus. Today, we stumbled on a missing feature within Smallrye Reactive Messaging that is available in [Spring Cloud Stream](https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/3.2.1/reference/html/spring-cloud-stream-binder-rabbit.html#_rabbitmq_consumer_properties). This feature is the [Single Active Consumer](https://www.rabbitmq.com/consumers.html#single-active-consumer) that is available since RabbitMQ 3.8. It is used to give exclusive access for one and only one active consumer for a queue.

I have already made a pull request that might serve as fix for this problem. Please let me know what you think.

Alternatively, I was wondering if it might be a useful extension to add a catch-all property that can be used for other properties that are not defined (yet) by the RabbitMQ Connector.

Something like:
```
queue.extra-arguments.feature-a=true
queue.extra-arguments.feature-b=100
```
It might be a little quirky, but it might help others instead of trying to define all RabbitMQ options as first-class citizens. Let me know what you think and I can take a stab at it.

**Comment by ozangunalp** [comment]
@fndejong Thanks for the PR! I think it looks good and will be merged soon. 
For the extra-args map property, I don't think that we can implement it as you describe. 
Reactive messaging depends on the Microprofile Config spec which doesn't support Map types (without a converter). 
– To be specific, Smallrye Config, so Quarkus, does support Map types –

I think it may make sense to use CDI and search for a `Map<String, Object>` bean with an identifier given by a config property. Similar to the `RabbitMQOptions` and `client-options-name` config property.

@cescoffier wdyt?

**Comment by cescoffier** [comment]
A catch-all property can work as we did in Kafka, but it's not that simple. Basically, you need to read all the keys.

**Comment by cescoffier** [comment]
@fndejong Can you open a discussion about this? 

I'm going to close this ticket as the PR is merged.
