### ISSUE TITLE
Kafka Connector and Avro: Does Deserialization with Avro Block in some way?

### ISSUE THREAD

**Issue by ericsouza** [smallrye/smallrye-reactive-messaging#1640]
Hey! I'm using kafka with avro (confluent schema registry), consuming or producing messages can block in any way due the need to communicate with schema-registry?

If does not block how is the flux to consuming messages, would be something like below?

receive message (polling non blocking) -> call schema registry (non blocking) -> deserialize (when schema registry response is ready) -> read message -> commit it

**Comment by cescoffier** [comment]
I don't know the internals of the Avro serde from Confluent, but that should not be a problem anyway as it happens on the Kafka polling thread (which can be blocked). 

So, in your case, you use something like: https://quarkus.io/blog/kafka-avro/

**Comment by ozangunalp** [comment]
Deserializers and Serializers are called by the underlying Kafka consumer and producer clients. Reactive Messaging extension calls poll (consumer) and send (producer) methods on dedicated threads, outside of the event loop.

**Comment by ericsouza** [comment]
Wonderful!! Thanks @cescoffier @ozangunalp!
