### ISSUE TITLE
 SRMSG00073: Invalid configuration, the following channel names cannot be used for both incoming and outgoing

### ISSUE THREAD

**Issue by Basil1991** [smallrye/smallrye-reactive-messaging#1681]
My config:
mp.messaging.incoming.ws-broadcast.connector=smallrye-kafka
mp.messaging.outgoing.ws-broadcast.connector=smallrye-kafka

Error:
Class - ConfiguredChannelFactory
Method - detectNameConflict()

----------------------
Question:
Why we need "detectNameConflict"? 
I use kafka to ensure our websocket cluster notice.
so I need broadcast the message to all node in websocket cluster.
how can I do?

**Comment by cescoffier** [comment]
The spec prevents you to use the same name for the incoming and outgoing channels. 
So, you need:
```
mp.messaging.incoming.ws-broadcast.connector=smallrye-kafka
mp.messaging.outgoing.ws-broadcast-out.connector=smallrye-kafka
mp.messaging.outgoing.ws-broadcast-out.topic=ws-broadcast
```

and change the `@Outgoing` or `@Channel` to be `ws-broadcast-out`
