### ISSUE TITLE
Add rabbitmq-quickstart

### ISSUE THREAD

**Issue by cdennison** [smallrye/smallrye-reactive-messaging#1696]
I was happy to see that RabbitMQ was recently added to the documentation but I found several points confusing that I think would be best addressed using a quickstart. I plan to submit a PR to add a quickstart.

Questions/confusions I will address in the quickstart:

1. In RabbitMQ the most normal use case is to use the same exchange for both incoming/outgoing messages. In this connector the exchange names default to the channel name which doesn't make a lot of sense to me because the channel names cannot be the same for both incoming and outgoing i.e. you get this error:

`javax.enterprise.inject.spi.DeploymentException: SRMSG00073: Invalid configuration, the following channel names cannot be used for both incoming and outgoing: [prices]`

So in the quickstart I plan to show that typically you would want to specify the exchange name explicitly.

2. The RabbitMQ documentation gives an example of JsonNode serialization which is interesting because that's a typical use case i.e. I've never seen someone sending primitives over a message broker before. I noticed that no other connectors docs or quickstarts shows how to use Jackson serialization so I thought I would add that.

3. I noticed that the "BeanUsingAnEmitter" approach doesn't appear to work for RabbitMQ but before I raise a bug I thought the quickstart might show what I'm doing wrong.

**Comment by ozangunalp** [comment]
Closed with #1892
