### ISSUE TITLE
Allow multiple consumers per channel for RabbitMQ connector

### ISSUE THREAD

**Issue by pravussum** [smallrye/smallrye-reactive-messaging#1699]
Currently for each incoming Smallrye messaging channel there is one RabbitMQ consumer created.
It would be beneficial to allow the creation of multiple RabbitMQ consumers per channel.
- concurrency could be increased (there is [a similar issue for Kafka](https://github.com/smallrye/smallrye-reactive-messaging/issues/329))
- support for sharded queues

Our use case is the following:
We have a high load environment where one RabbitMQ node is not able to process the full load, so our queues are sharded and thus distributed over all RabbitMQ nodes. 
If there are fewer RabbitMQ consumers than RabbitMQ nodes, not all messages will be fetched.

If each of our clients could be configured to create multiple consumers (greater than the number of RabbitMQ nodes), they would be evenly distributed over all queues, thus all messages could be consumed. 

[Here is the corresponding code location.](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQConnector.java#L245)

**Comment by kdubb** [comment]
@pravussum @cescoffier This issue can be closed correct?
