### ISSUE TITLE
Extend @Stream annotation to support back pressure configuration

### ISSUE THREAD

**Issue by mswiderski** [smallrye/smallrye-reactive-messaging#171]
Currently `Emitter` that is annotated with `@Stream` does not allow to configure back pressure which default to buffer based with hardcoded buffer size set to 128.

This results in `io.reactivex.exceptions.MissingBackpressureException` under increased load when the buffer size is exceeded.

This issue is about to extend the `@Stream` annotation to allow

- selecting strategy of the back pressure
- configuring selected strategy

**Comment by cescoffier** [comment]
I've opened a PR providing this feature.

**Comment by FreifeldRoyi** [comment]
How to achieve similar behavior in quarkus till this annotation is supported?

**Comment by cescoffier** [comment]
@FreifeldRoyi Unfortunately, not really. The good news is that it's already integrated in the `master` branch of Quarkus.

You can try something in the meantime:

```
@Stream("foo")
Emitter<String> emitter;

// ...

In another bean:

@Incoming("foo")
@Outgoing("foo-with-overflow")
public Flowable<String> addOverflow(Flowable<String> in) {
    return in.onBackPressureDrop(); // or whatever you need
}

```

**Comment by FreifeldRoyi** [comment]
I think that returning `Flowable` is not valid.. at least according to the [documentation](https://smallrye.io/smallrye-reactive-messaging/#_supported_signatures)

**Comment by cescoffier** [comment]
@FreifeldRoyi it is, it's an extension of `@Outgoing @Incoming Publisher<O> method(Publisher<I> pub)`. 

Actually, the documentation should be updated to explain that it's any implementation of `Publisher`, and `Flowable` extends `Publisher`.

**Comment by FreifeldRoyi** [comment]
> @FreifeldRoyi it is, it's an extension of `@Outgoing @Incoming Publisher<O> method(Publisher<I> pub)`.
> 
> Actually, the documentation should be updated to explain that it's any implementation of `Publisher`, and `Flowable` extends `Publisher`.

Seems like `Publisher<I>` needs to be Publisher<Message<I>>... When trying to send a `List<JsonObject>` I get a class cast exception. it's the same problem with `Flowable<List<JsonObject>>`. 
Any ideas why ?

**Comment by cescoffier** [comment]
It works with `Publisher<P>` and `Publisher<Message<P>>`. 

Can you copy your signature and the complete stack trace of the `ClassCastException`.
