### ISSUE TITLE
DeadLetterQueue KafkaFailureHander - Set a custom client.id

### ISSUE THREAD

**Issue by GoncaloPT** [smallrye/smallrye-reactive-messaging#1712]
I've set up a Kafka consumer using Smallrye Kafka and setting the failure strategy to dead-letter-queue.
Everything works as expected, but,
For particular reasons, I need to have control over the client.id of every producer on my code.

I've tried to set this on the 'general' kafka client but it seems to be overwritten somewhere 

After looking into Smallrye-reactive-messaging code, I think this feature is not supported yet.

KafkaDeadLetterQueue.java excerpt:
```
deadQueueProducerConfig.put(CLIENT_ID_CONFIG, "kafka-dead-letter-topic-producer-" + conf.getChannel());
```

**Comment by GoncaloPT** [comment]
for reference:
https://stackoverflow.com/questions/71915557/quakus-kafka-smallrye-how-to-change-client-id-of-the-underlaying-producer-us

**Comment by GoncaloPT** [comment]
I will submit a PR later with a feature implementation proposal.

**Comment by ozangunalp** [comment]
@GoncaloPT BTW there has been a recent change on this in #1676. So the producer client id is no longer dependent on the channel name but on the consumer channel client id.

**Comment by GoncaloPT** [comment]
That is interesting @ozangunalp, thanks for pointing it out!
What I need is the opportunity of defining the producer client id without any values prepended.

So I see this as maybe adding a specific configuration like we have for deadLetterQueueTopic but for clientId. If the value is not provided, then it will use the one we have currently.
Your thoughts?
