### ISSUE TITLE
Support JMS 1.1 Clients

### ISSUE THREAD

**Issue by josephearl** [smallrye/smallrye-reactive-messaging#1719]
There's nothing in the JMS connector itself that requires JMS 2.0 (it's makes the code a bit easier to write, but the same could be done using `createConnection` instead of `createContext).

Compiling against and using only the JMS 1.1 API would allow people to use legacy clients such as the ActiveMQ client together with the JMS connector.

**Comment by radcortez** [comment]
I guess it won't work if both coincide in the same project, but if the client resides on a separate project, it should be able to connect to any JMS Server (even if Jakarta).

@josephearl, any specific reason why you need the 1.1 API?

**Comment by josephearl** [comment]
@radcortez to support JBoss AMQ / ActiveMQ clients (OpenWire protocol)

Although the Artemis server supports the OpenWire protocol, the Artemis client does not

**Comment by radcortez** [comment]
The problem, as @cescoffier pointed out, the Jakarta rename is moving forward, so even if we move to the 1.1 API, we have the namespace change.

What is required to compile the client? Could it be split is some sort of API / Impl, so the client can use its preferred JMS API?

**Comment by josephearl** [comment]
@radcortez I'm not sure that would work because the JMS connector is designed to work with an exposed ConnectionFactory bean - if the application supplied a `jakarta` ConnectionFactory and the library was expecting a `javax` one then I think as far the library is concerned that dependency would be unsatisfied. 

I think supporting that would involve depending on your own interface rather than directly on the ConnectionFactory so different implementations could be provided. 

I'm not so sure that's a good path because it means the JMS connector won't interoperate seamlessly with other libraries that provide connection factories.

So happy to close this and maintain my fork. I think there's other features like adding JMS failure strategies that would be a benefit to more people than this.
