### ISSUE TITLE
Message is not nacked if a message consumer throws an exception

### ISSUE THREAD

**Issue by josephearl** [smallrye/smallrye-reactive-messaging#1726]
Give a consumer with a consume method like the following

```
@Incoming("sink")
public Uni<Void> consume(Message<String> v) {
    throw new IllegalArgumentException("boom");
}
```

The message is not nacked.

For the Kafka connector this means that following test passes against 3.15.0 with the `ignore` failure strategy:

```
@ApplicationScoped
public static class MyBrokenMessageConsumerUni {
  private final List<String> received = new CopyOnWriteArrayList<>();
  private final AtomicInteger acks = new AtomicInteger();
  private final AtomicInteger nacks = new AtomicInteger();

  @Incoming("kafka")
  @Outgoing("sink")
  public Message<String> process(Message<String> s) {
      return s.withAck(() -> {
          acks.incrementAndGet();
          return s.ack();
      }).withNack(t -> {
          nacks.incrementAndGet();
          return s.nack(t);
      });
  }

  @Incoming("sink")
  public Uni<Void> consume(Message<String> v) {
      received.add(v.getPayload());
      throw new IllegalArgumentException("boom");
  }

  public List<String> received() {
      return received;
  }

  public int acks() {
      return acks.get();
  }

  public int nacks() {
      return nacks.get();
  }

}
```

```
@Test
public void testIgnoreMessageUniException() {
    weld.addBeanClass(MetricRegistries.class);

    MyBrokenMessageConsumerUni bean = runApplication(getConfig(topic), MyBrokenMessageConsumerUni.class);
    await().until(this::isReady);

    companion.produceStrings().usingGenerator(i -> new ProducerRecord<>(topic, Integer.toString(i)), 10);

    await().atMost(2, TimeUnit.MINUTES).until(() -> bean.received().size() >= 1);
    assertThat(bean.received()).containsOnly("0");
    assertThat(isAlive()).isFalse();
    assertThat(bean.acks()).isEqualTo(0);
    assertThat(bean.nacks()).isEqualTo(0);
}
```

I think it should fail, and:

- I would expect all numbers to have been received once
- For the number of nacks to be 10
- And for the connector to still be alive

**Comment by josephearl** [comment]
If you did want to guard against the possibility of it being called twice, you could just make sure all code in the failure handler and the ack/nack methods does not execute synchronously when the handler method is called

**Comment by ozangunalp** [comment]
As you may know already the behaviour you are looking for can be achieved by forcing the `POST_PROCESSING` acknowledgement strategy with `@Acknowledgment(Acknowledgment.Strategy.POST_PROCESSING)`.

I understand the argument about the robustness of the framework. But as you said, the message may have been acked (manually of with PRE_PROCESSING strategy) before the exception is thrown.

TBH I didn't understand the part about how to avoid calling ack/nack twice.

**Comment by josephearl** [comment]
@ozangunalp thanks! I hadn't actually read that part of the docs.

RE: nacking twice, I mean if the consumer does something strange like:

```
@Incoming("sink")
public Uni<Void> consume(Message<String> v) {
    v.nack(new RuntimeException("foo"));
    throw new IllegalArgumentException("boom");
}
```

and your failure handler does something like:

```
public class KafkaFailStop implements KafkaFailureHandler {
    @Override
    public <K, V> CompletionStage<Void> handle(
            IncomingKafkaRecord<K, V> record, Throwable reason, Metadata metadata) {
        // Call log synchronously
        log.error("foo");
        ...
    }
}
```

then if the framework automatically nacked the message, the synchronous code (the log message) would be logged twice
