### ISSUE TITLE
Possibly useless code in RabbitMQConnector

### ISSUE THREAD

**Issue by kdubb** [smallrye/smallrye-reactive-messaging#1742]
@cescoffier Is this line not useless?

On completion is creates a cold `Multi` that is abandoned. It seems like this should be removed _or_ switched from `invoke` to a `transform`.

https://github.com/smallrye/smallrye-reactive-messaging/blob/d09f9f9706626586cc0521700c37c66f4444a5d3/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQConnector.java#L483

**Comment by cescoffier** [comment]
Totally useless.
