### ISSUE TITLE
Allow SSL connections for AMQP

### ISSUE THREAD

**Issue by nderwin** [smallrye/smallrye-reactive-messaging#176]
In `AmqpConnector` where `AmqpClientOptions` is created, it would be helpful if there was a way to configure whether SSL was enabled or not.

I ran into this trying to use Quarkus 0.21.1 (which uses version 0.0.10 of this project) to connect to an Amazon MQ instance, but it failed because the connection was not created using SSL.

**Comment by cescoffier** [comment]
Yes, the SSL configuration is missing. Fancy a PR? 

The options that can be passed are the following:
https://vertx.io/docs/apidocs/io/vertx/amqp/AmqpClientOptions.html.

**Comment by nderwin** [comment]
So, I created https://github.com/smallrye/smallrye-reactive-messaging/pull/179, though it just covers the SSL option.  If you want, I can add the other documented options.

**Comment by cescoffier** [comment]
Fixed in #179.
