### ISSUE TITLE
Support Queue type and mode configuration in rabbitmq

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#1782]
From https://github.com/quarkusio/quarkus/issues/25754

> add an option to set missing properties for queue definition through the application configuration. Support:
> 
> x-queue-type: [quorum, classic, stream]
> x-queue-mode: [lazy, default]

**Comment by kdubb** [comment]
I've tried to implement this but I'm stuck up against SmallRye config. As I said in Quarkus#25754 this should be implemented as a freeform set of options. There are lots of options for queues and lots of options for exchanges. Not to mention RabbitMQ plugins can add more options to each.

Unfortunately after I implemented this trying to use a `java.util.Map` as the `type` for `ConnectionAttribute` SmallRye config complains `SRCFG00013: No Converter registered for interface java.util.Map`.

Is there any way around this?

**Comment by ozangunalp** [comment]
@kdubb I am sorry, your comment went totally under my radar. 
IIRC it is not currently possible to use map as a connector attribute.
It is possible to extract free-form config from the channel configuration, we are doing this in the Kafka connector. 
We can pass config prefixed with `queue` to queue declare and build on what @cdmikechen did on #1836. 
I can give it a shot tomorrow.

**Comment by ozangunalp** [comment]
Closed by #1836
