### ISSUE TITLE
OpenTelemetry support enhancement

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#1784]
In order to improve the OpenTelemetry tracing support in reactive messaging we need:

1. Introduce an SPI that allows _decorating_ messages emitted by emitters. This SPI would be called on the same thread as the one calling `emitter.send(...)`, and the SPI implementor should be able to extract the current OTel Context and create the `TracingMetadata`. This metadata will be added to the emitted message.
2. When a message is associated with a duplicated context (the message could be created from an emitter or from an inbound connector), an SPI should be created to extract the potential `TracingMetadata` and attach it to the duplicated context. This would allow OTel to _re-attach_. 

In terms of ITs, there are already existing tracing-related IT, which verify the propagation along a pipeline and within a single protocol (like Kafka).
In addition to this, we need to check that:

- when emitting a message using an emitter, existing tracing details are propagated
- when emitting a payload using an emitter, existing tracing details are propagated
- when receiving a message from a protocol supporting tracing, the tracing details are propagated and associated with the duplicated context
- OTel can _re-attach_ from the duplicated context

\CC @radcortez @brunobat @ozangunalp

**Comment by cescoffier** [comment]
@ozangunalp @radcortez, where are we on this one?

**Comment by radcortez** [comment]
I believe that https://github.com/smallrye/smallrye-reactive-messaging/pull/1678 takes care of this.

**Comment by ozangunalp** [comment]
Closing this as #1678 takes care of it.
