### ISSUE TITLE
Calling the io.smallrye.reactive.messaging.kafka.KafkaConsumer#pause doesn't suspend the consumer

### ISSUE THREAD

**Issue by iurybakov** [smallrye/smallrye-reactive-messaging#1795]
Description.
Using the public API **io.smallrye.reactive.messaging.kafka.KafkaConsumer#pause**, we are trying to suspend the consumption of the Kafka topic. But as a result of the background work of the subscription class (io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStreamSubscription#pauseResume), there are cases of unexpected resumption of message consumption.

Expected behavior.
Calling the public API io.smallrye.reactive.messaging.kafka.KafkaConsumer#pause suspends the consumption of messages until a similar call to the public API io.smallrye.reactive.messaging.kafka.KafkaConsumer#resume. Otherwise, this API does not make sense from the point of view of public use.

Actual behavior.
Calling the public API io.smallrye.reactive.messaging.kafka.KafkaConsumer#pause has undefined behavior. The consumer can pause, pause temporarily, or not pause at all.

How to Reproduce.
User of public API io.smallrye.reactive.messaging.kafka.KafkaConsumer.

1. call io.smallrye.reactive.messaging.kafka.KafkaConsumer#pause on active Kafka subscription.

java: openjdk version "15.0.2" 2021-01-19
build tool: apache-maven-3.8.4
smallrye-reactive-messaging version: 3.13.0
env: Darwin Kernel Version 20.6.0

**Comment by cescoffier** [comment]
IT's a hard problem, and as documented (I think it is) we cannot use the pause/resume method while having the auto-pause-resume cycles.

**Comment by ozangunalp** [comment]
Yes this has been treated in #1592. Basically if one needs to handle pause/resume manually they need to disable `pause-if-no-requests`.
