### ISSUE TITLE
"io.smallrye.reactive.messaging.kafka.KafkaConnector.getConsumer(Channel)",Only one KafkaConsumer instance can be retrieved when partitions are greater than 1

### ISSUE THREAD

**Issue by liuzhaozhao** [smallrye/smallrye-reactive-messaging#1803]
I want to get all the consumers and close them in the order I want, Some consumers can close them in parallel to avoid waiting too long in serial.

My consumers manage their own consumption points and need to persist the in-memory state to the database when the service is down, so this process cannot be satisfied by `kafkaconnector.terminate(Object)`

It might look something like this:
```java
public <K, V> List<KafkaSource<K, V>> getConsumer(String channel) {
    return sources.stream()
            .filter(ks -> ks.getChannel().equals(channel))
            .toList();
}

public List<KafkaSink> getConsumer(String channel) {
    return sinks.stream()
            .filter(ks -> ks.getChannel().equals(channel))
            .toList();
}
```

**Comment by ozangunalp** [comment]
You are absolutely right. We need to make a couple of adjustments on usages, especially on the `KafkaClientService` side.

**Comment by liuzhaozhao** [comment]
@ozangunalp 
I have another question,Is there an optimization to be made here?
![image](https://user-images.githubusercontent.com/10733976/178640833-a91a291d-ed79-4f79-be6f-928d1d4018ca.png)

 Sources and sinks can be loaded in the order of configuration (or the order can be specified by annotation) so that closure can be carried out in the order of configuration when `Kafkaconnector.terminate (Object)` is called.
![image](https://user-images.githubusercontent.com/10733976/178641888-3c582eb9-4dbf-4cf9-9c2b-cdb352925e62.png)

In some scenarios, upstream and downstream topics are related. If the downstream topic is shut down first and then the upstream topic is shut down, the downstream cannot be shut down properly because there is always data coming in the upstream topic.

The startup sequence is usually reversed from the shutdown sequence.
