### ISSUE TITLE
Typo in Concepts.md

### ISSUE THREAD

**Issue by HknLof** [smallrye/smallrye-reactive-messaging#1815]
Hi Team,

I think the documentation wants to state

_2. Send message to a remote broker (outbound)_

it actually states

> 2.  send messages to a remove broker (outbound)

Spotted a second one see Ref 2
Refs:

1. https://github.com/smallrye/smallrye-reactive-messaging/blob/main/documentation/src/main/docs/concepts/connectors.md?plain=1#L25
2. https://github.com/smallrye/smallrye-reactive-messaging/blob/main/CONTRIBUTING.md?plain=1#L9

**Comment by cescoffier** [comment]
Fancy a PR?

**Comment by HknLof** [comment]
Yepp, If you allow me to contribute / push a branch, than I can open the PR :)

**Comment by cescoffier** [comment]
Yes, sure, just fork the repo and create a pull request.
