### ISSUE TITLE
Kafka Messaging presenting weird issue with ACKs and updating offsets

### ISSUE THREAD

**Issue by jbkc85** [smallrye/smallrye-reactive-messaging#1828]
I do apologize, as this could be something completely outside of the realm of this project, however I am bashing my head against the code and wondering what is going on - so I wanted to reach out to see if this community could provide me with any insight.

We are currently using Quarkus and smallrye-reactive-messaging with Kafka.  The pseudocode of our project looks similar to this (please note, we have `auto.commit` disabled):

```
    @Incoming("topic")
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    public CompletionStage<Void> processResults(Message<Wrapped> message) {

        try { 
....

        } catch (Exception ex) {
                return message.nack(ex);
        }

        return message.ack();
    }
```

Most the time this works just fine.  However there are times where our lag of the topic in question gets to 500+, and we suddenly stop seeing the consumer group offsets update and it appears that the lag continues at 500+, until a very large drop due to all the acknowledges finally being marked on Kafka's end.  We have no idea why this behavior exhibits itself, but can confirm its only when the lag of a topic exceeds a specific threshold.

Some other settings of note:

```
fetch.max.bytes = 52428800 (default)
max.poll.records = 15 (adjusted)
```

Does anyone have any idea what is going on here, or could perhaps would me through trying to debug this?  I would be happy to share pretty much whatever I can in chasing down this issue.

Thanks in advance!

**Comment by jbkc85** [comment]
Some additional notes:

It appears that if we change the `commit-strategy` to `latest`, the offsets change as expected.  However, we are using the smallrye-messaging version that `throttled` is the default strategy - yet we never saw offsets increase after the `5000ms` timing.  Am I not understanding how `throttled` commit strategy works?  Is there something tied into the flex match bytes or max poll records that I am missing?

**Comment by Dougniel** [comment]
> Some additional notes:
> 
> It appears that if we change the `commit-strategy` to `latest`, the offsets change as expected. However, we are using the smallrye-messaging version that `throttled` is the default strategy - yet we never saw offsets increase after the `5000ms` timing. Am I not understanding how `throttled` commit strategy works? Is there something tied into the flex match bytes or max poll records that I am missing?

hi @jbkc85,  if think you got it 👍

What you described [here](https://github.com/smallrye/smallrye-reactive-messaging/issues/1828#issue-1318766361) is coherent with the behaviour of default acknowledge strategy `throttled` according to the [documentation](https://smallrye.io/smallrye-reactive-messaging/4.9.0/kafka/receiving-kafka-records/#acknowledgement). 

ℹ️ The purpose of this strategy is to improve throughout by reducing the number of acks (not all messages are acknowledge only the latest every 5 seconds)
