### ISSUE TITLE
rabbitmq-reconnect-interval

### ISSUE THREAD

**Issue by leoee** [smallrye/smallrye-reactive-messaging#1841]
Hi,

According to the [documentation](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.11/rabbitmq/rabbitmq.html), the values for rabbitmq-reconnect-interval is seconds. During some uses, I realized the time is actually in milliseconds.

**Comment by kdubb** [comment]
This should be fixed in 3.16+ via #1656
