### ISSUE TITLE
Connection refused for rabbitmq cluster

### ISSUE THREAD

**Issue by leoee** [smallrye/smallrye-reactive-messaging#1842]
Hi,

I am using Smallrye for rabbitmq in a service that is a consumer.

Every time I restart the service I got some issues related to the rabbitmq connection.

2022-08-09 17:49:21,009 ERROR [io.ver.rab.imp.RabbitMQClientImpl] (executor-thread-0) Could not connect to rabbitmq: java.net.ConnectException: Connection refused

It seems this is trying to connect too early, because I received the error 3, 4 times and then I got connected.

I added the rabbitmq-reconnect-interval and now I received only 1 error before get connected.

My question is: is there a way to add some kind of delay before the first attempt to connect on rabbitmq?

**Comment by cescoffier** [comment]
You cannot configure the initial delay, only the delay between attempts (and the number of attempts).
