### ISSUE TITLE
Documentation error in Kafka DLQ metadata example

### ISSUE THREAD

**Issue by victorgawk** [smallrye/smallrye-reactive-messaging#1854]
I was trying to reproduce this code example from documentation [documentation/src/main/java/kafka/inbound/KafkaDeadLetterExample.java](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/documentation/src/main/java/kafka/inbound/KafkaDeadLetterExample.java)
but I found out it has a bug. It must call `.build()` after `.withHeaders(...)` to return a `OutgoingKafkaRecordMetadata` object:
```java
public CompletionStage<Void> consume(KafkaRecord<String, String> message) {
    return message.nack(new Exception("Failed!"), Metadata.of(
            OutgoingKafkaRecordMetadata.builder()
                    .withKey("failed-record")
                    .withHeaders(new RecordHeaders()
                            .add("my-header", "my-header-value".getBytes(StandardCharsets.UTF_8)))
                    .build())   // -- must add this line
    );
}
```

**Comment by cescoffier** [comment]
Thanks! I will update the documentation.
