### ISSUE TITLE
AmqpClientHelper behavior when using a producer AmqpClientOptions bean

### ISSUE THREAD

**Issue by aolle** [smallrye/smallrye-reactive-messaging#1873]
Hello,

the changes introduced in:
#1504 

the AMQP configuration behavior is weird and inconsistent.

When you have a bean that produces the `AmqpClientOptions`, all values that have a _defaultValue_ declared in the `AmqpConnector` class are never used from the custom bean configuration; the default `AmqpClientOptions` are used instead.

It can be checked, for example, setting up the following bean:

```
    @Produces
    @Identifier("myclientoptions")
    public AmqpClientOptions options() {
        return new AmqpClientOptions()
                .setHost("myhost")
                .setContainerId("bla bla")
                .setVirtualHost("foo bar")
                .setUsername("user2")
                .setPassword("passwd2")
                .setConnectTimeout(50);
    }
```

and

```
amqp-client-options-name=myclientoptions
```

The host and connect timeout will never be used.

For the _host_, the default options has a default value (won't be null https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java#L75), then the final `AmqpClientOptions` will have "localhost" instead of "myhost".

The same for the connection timeout value. The configured value from the bean will never be used; 1000 will be used instead of, as it is the default value.

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java#L82

Then, the only attributes that can work with the #1504 fix are the _username_ and _password_, which are _null_ by default.

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpClientHelper.java#L77

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java#L73

but, the fix won't work with _host_, _port_, _reconnectAttempts_, _reconnectInterval_ and _connectTimeout_:

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpClientHelper.java#L98

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java#L82

The test case 

https://github.com/smallrye/smallrye-reactive-messaging/blob/40d4fd467b2073a4c6438f9fe32a6375158afe05/smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpSourceCDIConfigTest.java#L203

tests that there are not deployment exceptions because of the beans and the _client-options-name_ correlation, and the result of the `ConsumptionBeans` but is **not** testing the behavior introduced because of the `mergeTo` method.

**Aditionally**, in the hypothetical case that the behavior was the desired, for some of the preference values, like the following check 

```
        if (connectTimeout > 0) {
            custom.setConnectTimeout(channel.getConnectTimeout());
        }
```

does not allow to configure `connectTimeout` to a zero value, which is a a valid value

https://github.com/eclipse-vertx/vert.x/blob/280fdf46717542271c70692df02c56c393a182c0/src/main/java/io/vertx/core/net/ClientOptionsBase.java#L138

it cannot be configured using a bean but it can be configured with the properties. The check should be `>=0`.

The same argument can be applied for `reconnectAttempts` (should be `>=-1`)

https://github.com/eclipse-vertx/vert.x/blob/280fdf46717542271c70692df02c56c393a182c0/src/main/java/io/vertx/core/net/NetClientOptions.java#L315

Thank you.
Regards.

**Comment by cescoffier** [comment]
@kabir you did change something in this code recently. 
I agree with the content of the issue. For me, the bean values should have priority. Do you agree?

**Comment by kabir** [comment]
@cescoffier the only changes I made in this area (at least that I can remember) are in the unmerged https://github.com/smallrye/smallrye-reactive-messaging/pull/1741 (which will need redoing after Julien's changes in vert.x)

**Comment by cescoffier** [comment]
ah, sorry @kabir, my memory is failing me. I will open a PR

**Comment by cescoffier** [comment]
@aolle not totally the solution you mentioned, but can you look at https://github.com/smallrye/smallrye-reactive-messaging/pull/1874?

**Comment by aolle** [comment]
@cescoffier I have been testing the fix and it works as expected!

**Comment by cescoffier** [comment]
Thanks @aolle. Closing this issue!
