### ISSUE TITLE
Configuring reactive messaging in Quarkus for custom third party serializer using uppercase properties

### ISSUE THREAD

**Issue by fikrum** [smallrye/smallrye-reactive-messaging#1907]
## Description
Having an issue integrating Quarkus reactive messaging with third party serializer. 

I use `io.quarkus:quarkus-smallrye-reactive-messaging-kafka:2.9.1.Final`  and a property defined as  `mp.messaging.outgoing.transfer-event-outbound.SOME_VALUE_SERIALIZER=<third party serializer class>`

Notice the key is upper case separated by "_" (`SOME_VALUE_SERIALIZER`) . The third party serializer which uses smallRye kafka configurations is looking for a value for SOME_VALUE_SERIALIZER, but the smallRye reactive messaging  [JsonHelper.java](https://github.com/smallrye/smallrye-reactive-messaging/blob/5296684541b3bcad5bdfc65c3db4666a0350c3e3/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/JsonHelper.java) class transform kafka properties key into lowercase separated by "." (`some.value.serializer`). so the default key will be overridden by `some.value.serializer` and the third party serializer will not able to resolve the key as no value for `CRYPTO_VALUE_SERIALIZER` found in configuration properties.

## Question 

Would it be possible to add an optional Boolean or string configuration key like `mutate-key` and change the code as below so that the default property key will not be changed or is there any other option to keep the original kafka configuration keys?

```
  String mutateKey = config.getOptionalValue("mutate-key", String.class).orElseGet(null);
        if (mutateKey == null || mutateKey.trim().equalsIgnoreCase("true")) {
            if (key.contains("_") || allCaps(key)) {
                key = originalKey.toLowerCase().replace("_", ".");
            }
        }
```

This solution is backward compatible and does not break code. By default  `mutate-key` will be true and if third party does not want smallRye to change environment variables they only need to set `mutate-key` to `false`

@cescoffier

**Comment by cescoffier** [comment]
It should be possible. However, it's kind of weird that the serde does not follow the kafka convention. In addition, it makes configuration from env variable a bit ambiguous.

In the meantime you can reward the serde and pass the configuration as expected.

**Comment by cescoffier** [comment]
Actually, the proposal may be problematic for some kafka properties when coming from env variables. It would need to be checked carefully.

**Comment by cescoffier** [comment]
BTW, what's the serde doing that? It might be better to follow the convention.

**Comment by cescoffier** [comment]
The proposed approach won't work as it will break configuration from env variables (coming from Quarkus/Smallrye config). 

As proposed above, there are two approaches:

- fix the serde
- rewrap it and change the configuration to pass the expected format

**Comment by cescoffier** [comment]
Closing as won't fix, please check the workarounds.
