### ISSUE TITLE
PublisherDecorator package breakage

### ISSUE THREAD

**Issue by cristianonicolai** [smallrye/smallrye-reactive-messaging#1911]
Changes to PublisherDecorator ( moving package and new parameter to decorate method ) ends up creating incompatible change in Koogito to align with Quarkus 2.7 and Quarkus main version, where reactive messaging is upgraded to 3.19.1.

See Kogito class https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/BackpressurePublisherDecorator.java

Related to https://github.com/quarkusio/quarkus/issues/12486

This change seems to impact the upgrade between versions 3.18.0 to 3.19.1. 
Could we somehow keep this compatibility in the code so it works across versions?

**Comment by cristianonicolai** [comment]
@ozangunalp @cescoffier could you take a look on this?

**Comment by fjtirado** [comment]
If you can keep publisherDecorator in package io.smallrye.reactive.messaging.providers rather than moving it to io.smallrye.reactive.messaging, that will do it.

**Comment by cristianonicolai** [comment]
plus, overloading the decorate method so it has the new and old signature.

**Comment by fjtirado** [comment]
@cristianonicolai is right, I miss the new boolean parameter

**Comment by ozangunalp** [comment]
That's unfortunate, the `PublisherDecorator` interface wasn't part of the public API before, as is the case for the `provider` module. I think you added the usage while we were moving this to the public API.

**Comment by ozangunalp** [comment]
We'll restore the `PublisherDecorator` in the providers package and we should release the fix asap.

**Comment by cristianonicolai** [comment]
@ozangunalp thanks for that
