### ISSUE TITLE
[rabbitmq] dynamic queues

### ISSUE THREAD

**Issue by jonsalvas** [smallrye/smallrye-reactive-messaging#1936]
First of all: Thanks for the awesome support for rabbitmq reactive messaging!!

We are currently setting it up for our project and facing one issue while trying to configure producer/consumer. What we are trying to achieve is to have one outgoing channel publishing messages for a certain dynamic routing-key (let's say k1,k2,k3, ...) and one incoming channel consuming messages. For each routing key there should be an own dynamic queue (q.k1,q.k2,q.k3, ...). Just to be clear: dynamic in this context means, new keys can be created or old ones deleted on runtime. However, the only way I see right now to consume all queues by the consumer, is to define multiple channels statically in the application configuration. Or am I missing something?

Any ideas how to solve this? Or should this be a feature request?

**Comment by kdubb** [comment]
SRRM wires all the @Incoming and @Outgoing at startup (possibly partially at build time). It doesn't support dynamically adjusting the configuration at runtime.

**Comment by cescoffier** [comment]
Unfortunately, no, we cannot handle that use case (for the consumer side).
You can use the low level rabbitMQ client for this.
