### ISSUE TITLE
MQTT and CleanSession=false and Unsubscribe on shutdown 

### ISSUE THREAD

**Issue by dometec** [smallrye/smallrye-reactive-messaging#1939]
Using MQTT and "auto-clean-session=false" means that I want leave a session with my subscription live on the broker even when my application is down. 
On reconnection phase, if the session is present on the broker side, the application does not send subscription requests (given that these should already be present on the broker).

The problem is that when the application is shut down, this sends UNSUBSCRIBE request, so then at the next start (since the session is present though without subscriptions) the app didn't send subscriptions, so it does not receive messages.

The UNSUBSCRIBE must never be done, since for clean session = true, on disconnection the broker remove all subscription independently, while for clean session = false, I just want the SUBSCRIPTION always.

As discussed with @cescoffier, it is better to add a variable to allow restore this old behavior in case someone needs it:
_unsubscribe-on-disconnection_ (default false)

**Comment by cescoffier** [comment]
Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/1940.
