### ISSUE TITLE
A message generated from a kafka record with null value (tombstone) should not have a null payload

### ISSUE THREAD

**Issue by mrickly** [smallrye/smallrye-reactive-messaging#1968]
Many methods from the Message class require a non-null payload, otherwise an IllegalArgumentException is thrown. When a kafka record with a null value (tombstone) is read from a topic, it will be transformed to a message with a null payload, creating various problems. For instance, transforming the message by decorating the ack and nack functions (message decorator/interceptor) is not possible for tombstone records, or at least it is not obvious to me how that would work. 

I believe that when a kafka record with a null value is received, the payload of the message should be set to some non-null value, for instance Record(key, null). Alternatively, one could consider adding methods to the Message class that do not throw when the payload is null.

**Comment by cescoffier** [comment]
I don't understand why `null` is inappropriate in this case. 
A Kafka record can have `null` as a value.

**Comment by mrickly** [comment]
@cescoffier : My concrete use case is that I'm modifying messages from an incoming kafka connector in a `PublisherDecorator`. When the value is null, they are mapped by Quarkus to messages with a null payload. Hence, e.g., a call like `message.withAck` will fail. Therefore, before any such call, I have to test whether the payload is null and, if it is, set a non-null payload, `Record.of(key, null)` for instance.

**Comment by ozangunalp** [comment]
I think @mrickly is talking about the `Message` which doesn't accept `null` as payload.

**Comment by ozangunalp** [comment]
I think having `Message` payload `Record.of(key, null)` when the kafka record payload is `null` would be very inconsistent. Isn't it more natural to handle the null case as you are doing now?

**Comment by mrickly** [comment]
Hi @ozangunalp: It's fine with me. I wasn't sure whether you were aware of it and wanted to attract your attention to this use case.

**Comment by cescoffier** [comment]
this is because you are at the junction of two words:

- kafka tombstones have null value - lots of kafka apps uses this
- reactive streams do not support null values - per spec 

So, basically, you need to rewrap the tombstone into your own _Tombstone_ object. 
Not that tombstones do not make a lot of sense if you don't have the key. So... I would have expected the Message payload to be a record in this case.
