### ISSUE TITLE
RabbitMQ - Use of Transactional on @Incoming and @Outgoing

### ISSUE THREAD

**Issue by gpor0** [smallrye/smallrye-reactive-messaging#1978]
Hi, 

I went through the documentation but I cannot find anything related to the JTA. I would like to know if is it possible to create transaction towards RabbitMQ in order to make atomic transaction over the RabbitMQ consume / publish operations meaning consumed and published message will be atomic operation on the RabbitMQ?

**Comment by cescoffier** [comment]
JTA is not supported (as it requires a synchronous blocking model).

**Comment by gpor0** [comment]
It looks like annotating the method with @Transactional enables the blocking behavior but this does not take transactions into account.
