### ISSUE TITLE
Doc issue: mqtt payload is no longer restricted to bytes

### ISSUE THREAD

**Issue by tsegismont** [smallrye/smallrye-reactive-messaging#199]
`MqttMessage` is now parameterized, but the doc says payload is restricted to `byte[]`.

I discussed this @cescoffier off-list and it seems the doc is wrong.

**Comment by misl** [comment]
@tsegismont could you please point out where this is wrong?

As far as I know for incoming messages the payload constraint is still `byte[]`. See also #116 . Outgoing messages do support other types, but that already is in the [documentation](https://smallrye.io/smallrye-reactive-messaging/#_interacting_using_mqtt) I read.

**Comment by tsegismont** [comment]
@misl I wasn't aware of #116 so yes, the doc is right.

I filed this issue after upgrading an app from an older version of Smallrye Reactive Messaging. In the older version `MqttMessage` class was not parameterized and used to return `byte[]` for the payload. Now it's parameterized even if, in fact, it only supports `byte[]`.

So it seems this duplicates #116 

Thanks for pointing this out.

**Comment by misl** [comment]
@cescoffier I think this one can be closed.
