### ISSUE TITLE
RabbitMQ - incoming channel health reporting KO readiness until channel is used

### ISSUE THREAD

**Issue by ggam** [smallrye/smallrye-reactive-messaging#2019]
At least with RabbitMQ connector, health endpoint reports KO readiness and liveness until the channel is first used.

Reproducer: 
[reproducer.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/10194609/reproducer.zip)

After application startup, Quarkus health reports the following:
```

{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "DOWN",
            "data": {
                "test": "[KO]",
                "test_out": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "test": "[KO]",
                "test_out": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - startup check",
            "status": "UP"
        }
    ]
}
```

After a request to localhost:8080/queue the consumer is initialized and both liveness and readiness are reported ok. 

I understand the exact point of initialization depends on Quarkus, but looking at the code:
https://github.com/smallrye/smallrye-reactive-messaging/blob/7a6330c56e3a85c92cb92489d38489b28f951ddf/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQConnector.java#L376-L383

Both readiness and liveness are based on the connection being stablished. The problem with this approach is that my container orchestrator (Hashicorp Nomad, but I suppose the same goes for Kubernetes) won't treat the container a "healthy" until the readiness metrics are reporting OK.

IMO, readiness in this case should mean the client is ready to be used, meaning configuration was correct and nothing seems to prevent the connection to be opened.

**Comment by kdubb** [comment]
The passed `false` is for the `strict` parameter; which is used for outgoing checks.

When `strict` is `false` the outgoing connector is checked if it does _not_ equal `NOT_CONNECTED` (as seen below). The outgoing connector is created in the `INITIALIZING` state _should_ only be `NOT_CONNECTED` if it was first connected and then disconnected.

https://github.com/smallrye/smallrye-reactive-messaging/blob/7a6330c56e3a85c92cb92489d38489b28f951ddf/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQConnector.java#L397-L398

Can you check the logs and see if the connector was connected and then disconnected?

**Comment by kdubb** [comment]
I'm just realizing I read the status in your issue backwards. It's the incoming connector that is reporting `KO`.

**Comment by ggam** [comment]
> I'm just realizing I read the status in your issue backwards. It's the incoming connector that is reporting `KO`.

Exactly. And you ready this comment, it seems my expectation should be correct:
https://github.com/smallrye/smallrye-reactive-messaging/blob/7a6330c56e3a85c92cb92489d38489b28f951ddf/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQConnector.java#L388-L389

**Comment by kdubb** [comment]
According to the documentation, [here](https://smallrye.io/smallrye-reactive-messaging/3.22.1/concepts/emitter/#retrieving-channels) when you inject via `@Channel` then:

     Note that in this case, you will be responsible for the subscription

So, you are required to subscribe to the injected `Multi<String>` first. As you have seen this will cause a connection and then begin reporting health successfully.

One solution to this is to simplify your definition and `@Incoming("test")`, on the getter:
```java

    @GET
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    @Incoming("test")
    public Multi<String> messages(Multi<String> messages) {
        return messages;
    }
```

This will automatically connect the incoming channel as expected.

**Comment by kdubb** [comment]
Alternatively, we can allow both incoming and outgoing connectors to be considered healthy when in the `INITIALIZED` state. I do remember that this code was modeled after another connector when I wrote it but maybe the wisdom has changed.

@ozangunalp Should this change be made?

**Comment by ggam** [comment]
> So, you are required to subscribe to the injected Multi<String> first.

Yeah that's ok, I also need to invoke `DataSource#getConnection()` after injecting a pooled datasource. But the runtime opens the connection eagerly and raises an error (or exposes a `KO` healthcheck) before the first request is served.

That's what I'd like to get here too: being able to know that a connection is `KO` before actually trying to use it. Since this means opening at connection that might not be needed, this probably needs to be guarded by a config property.

> One solution to this is to simplify your definition and use @Incoming("test"), on the GET endpoint:

Interesting idea, but sadly I also need to get some `@PathParam` values. I can move them to class properties, but that's not best practice in Quarkus: https://github.com/quarkusio/quarkus/issues/29776#issuecomment-1346240827

**Comment by ggam** [comment]
> One solution to this is to simplify your definition and use @Incoming("test"), on the GET endpoint:

What I could do is to put the `@Incoming` on a new CDI bean method that returns the `Multi`, then inject the bean and invoke that method to get the stream of messages. That should solve my specific problem.

**Comment by kdubb** [comment]
Easier would be to call `messages.toHotStream()` in a `@PostConstruct` method, save the hot stream and return it from the `@GET` method.

**Comment by kdubb** [comment]
Or use constructor injection for the channel and call `messages.toHotStream()` in that.

**Comment by kdubb** [comment]
Just to be sure I modified your resource. There was one small snag you would most likely hit in any case, you need to eagerly instantiate it; which is done by the startup event.

```java
@Path("queue")
public class QueueResource {

    Multi<String> messages;

    @Inject
    public QueueResource(@Channel("test") Multi<String> messages) {
        this.messages = messages.toHotStream();
    }

    @GET
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    public Multi<String> messages() {
        return messages;
    }

    void startup(@Observes StartupEvent event) {
    }
}
```
