### ISSUE TITLE
CloudEvent time does not follow RFC-3339 format. 

### ISSUE THREAD

**Issue by xqianwang** [smallrye/smallrye-reactive-messaging#2061]
CloudEvent spec requires that the date and time format must follow rfc 3339 standard (https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#type-system). However the time format of generated event is like `2023-01-25T19:07:06.370582GMT`.

**Comment by cescoffier** [comment]
We use the following formatter:

```
public static final DateTimeFormatter RFC3339_DATE_FORMAT = new DateTimeFormatterBuilder()
            .appendPattern("yyyy-MM-dd'T'HH:mm:ss")
            .appendFraction(ChronoField.NANO_OF_SECOND, 0, 9, true)
            .appendZoneOrOffsetId()
            .toFormatter();
```

To you have a reproducer showing the issue?

**Comment by cescoffier** [comment]
Hum, the issue may be the `appendZoneOrOffsetId` instead of just the offset.

**Comment by cescoffier** [comment]
I'm wondering if we should just use `java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME`

**Comment by ozangunalp** [comment]
Why is `2023-01-25T19:07:06.370582GMT` not a correct timestamp for [rfc3339](https://www.rfc-editor.org/rfc/rfc3339)?
For me, it has 370582000 nanos after the second and GMT as the time zone.

**Comment by ozangunalp** [comment]
Ok, actually I now understand. RFC3339 doesn't accept time zones only Z or offset. I think using `ISO_OFFSET_DATE_TIME`  should be fine.

**Comment by xqianwang** [comment]
Hello, quick question. Is this fix released with which version of quarkus?
