### ISSUE TITLE
Make annotations more Kotlin friendly

### ISSUE THREAD

**Issue by geoand** [smallrye/smallrye-reactive-messaging#209]
Currently because `@Stream` and `@Channel` which can be used for field injections are hard to use Kotlin.
This is due to the fact that since these annotations are missing the `@Target` meta-annotation, Kotlin doesn't add it the to java field (but to a synthetic method that the Kotlin compiler creates). 
The effect is that users wanting to use these annotations have to use this weird syntax:

```
@field: Stream("whatever")
```

instead of the intuitive:

```
@Stream("whatever")
```

A demonstration of the problem can be found [here](https://stackoverflow.com/q/57960858/2504224).

If you agree, I can open a PR for this

**Comment by cescoffier** [comment]
Oh yes, definitely! Actually having a Kotlin example would be also amazing!

**Comment by geoand** [comment]
Cool! I'll do this within the week :)

**Comment by geoand** [comment]
PR #209 should take care of this

**Comment by cescoffier** [comment]
#209 is self-referring :-). You meant #227

**Comment by geoand** [comment]
LOL! I certainly did :)
