### ISSUE TITLE
Support failure management strategies when handling deserialization failures

### ISSUE THREAD

**Issue by vsevel** [smallrye/smallrye-reactive-messaging#2120]
As discussed in [the documentation](https://smallrye.io/smallrye-reactive-messaging/3.22.1/kafka/receiving-kafka-records/#handling-deserialization-failures),  "the failure strategy presented above cannot be applied".

For ease of use, it would be nice to support the 3 strategies `fail`, `ignore` and `dead-letter-queue` when handling deserialization failures as well. at the moment, the behavior is to `fail`.

we can implement the `ignore` strategy with a `DeserializationFailureHandler`, but to achieve the proper semantic, we would need to return a dummy object, and test for it plus return in the business method when seeing that dummy object (for instance `null`).
it is possible to use `mp.messaging.incoming.$channel.fail-on-deserialization-failure=false`, but we still need to follow the "return on null" idiom in the business code, which looks like an implementation detail leaking.

```
    @Incoming("source-in")
    public void consume(Order order) {
      // the object is null when deserialization error is occurred
      if (order == null) {
        log.info("Ignoring null order");
        return;
      }
     // now process order
    }
```

finally, we can implement the `dead-letter-queue` strategy as well, using the following approach (with a return on `null` in the business method like for the `ignore` strategy):

```
    @Inject
    @Channel("source-out-error")
    Emitter<byte[]> deadLetterBeanEmitter;
 
    @Override
    public byte[] handleDeserializationFailure(String topic, boolean isKey,
            String deserializer, byte[] data,
            Exception exception, Headers headers) {
        log.error("The following message has been rejected: {} due to {}", new String(data), exception.getMessage());
        deadLetterBeanEmitter
                .send(Message.of(data).addMetadata(OutgoingKafkaRecordMetadata.<String> builder()
                        .withHeaders(headers)
                        .build()));
 
        return null;
    }
```

this is tedious to write (or instruct multiple teams to do).

it would be much nicer, to be able to say one of:
```
mp.messaging.incoming.$channel.deserialization-failure-strategy=[fail|ignore|dead-letter-queue]
```

**Comment by cescoffier** [comment]
I don’t think you can do: new String(data). It is likely going to fail.

Sure it works for simple payload, but large ones, binaries… will be harder.

That’s the very reason why we don’t have the feature yet. If we can
workaround it, then, we can implement it.

**Comment by cescoffier** [comment]
Ah got it! So in the case of a dead letter topic,  you want to serialize it using a byte array serializer. That could work.
However, in a single topic, you will have multiple types, which would make consumption harder. We may need a second topic.

**Comment by vsevel** [comment]
> However, in a single topic, you will have multiple types, which would make consumption harder.

may be. we would have regular business objects "Foo" whose processing had lead to an error.
and "Foo" objects that could not be deserialize, which could be valid - and usually will be since the producer is bound to produce valid "Foo" objects - they just can't be deserialized (for instance a consumer has not been upgraded with the new schema before the new producer started push the new version).
whenever something lands in a DLT, we have some alerting, and somebody will look at the errors and take action : either delete messages/skip them, or republish them (sometimes after a corrective action, such as consumer upgrade) in a dedicated business topic once we believe the consumer has a chance to do something with them.
so I do not see having a separate topic as a strong requirement.
when messages go to the DLT, at this point it is just bytes with some headers giving context about the error. I do not make a strong distinction between a processing error and a deserialization error.
by default I actually would like to be able to reuse the same DLT (and avoid multiplying the required DLTs). but I am missing operational experience with kafka. so I could be wrong on this.

**Comment by vsevel** [comment]
hello all. any news on this?

**Comment by vsevel** [comment]
hello, any news on this? this would simplify a lot moving deserialization error messages into DLT.
we have created an implementation that is working:`
```
@ApplicationScoped
@Identifier("failure-dead-letter")
public class BankDeserializationFailureHandler implements DeserializationFailureHandler<byte[]> {
 
    private static final Logger log = LoggerFactory.getLogger(BankDeserializationFailureHandler.class);
 
    @Inject
    @Channel("source-out-error")
    Emitter<byte[]> deadLetterBeanEmitter;
 
    @Override
    public byte[] handleDeserializationFailure(String topic, boolean isKey,
            String deserializer, byte[] data,
            Exception exception, Headers headers) {
        log.error("The following message has been rejected: {} due to {}", new String(data), exception.getMessage());
        deadLetterBeanEmitter
                .send(Message.of(data).addMetadata(OutgoingKafkaRecordMetadata.<String> builder()
                        .withHeaders(headers)
                        .build()));
 
        return null;
    }
}
```

and in the processing code we need to start with:
```
// the object is null when deserialization error is occurred
 if (order == null) {
     log.info("Ignoring null order");
     return;
 }
// processing message...
```

this looks awkward on the processing code.
is there a better way to do it.
basically we want to store away all messages with processing issues, to avoid blocking the channel.
I am thinking this is a common pattern that is worth higher level idiomatic construct.

**Comment by vsevel** [comment]
hello @ozangunalp 
I was reading again [handling-deserialization-failures](https://smallrye.io/smallrye-reactive-messaging/3.22.1/kafka/receiving-kafka-records/#handling-deserialization-failures)
what is the behavior if I return `null`? the message gets served again to the business method?
have you considered moving the message to a dedicated topic?

**Comment by ozangunalp** [comment]
Yes the message will get delivered to the business method. What effectively happens is that Kafka client will create a `ConsumerRecord` with failing deserialization as null (key and/or value). With business method will get delivered the message, backed by that `ConsumerRecord`, so you can have the method called with a `null` value.

> have you considered moving the message to a dedicated topic?

Do you mean sending the message to a DLQ? I think #2256 should cover that.

**Comment by vsevel** [comment]
> Do you mean sending the message to a DLQ? I think https://github.com/smallrye/smallrye-reactive-messaging/pull/2256 should cover that.

ah yes. that is the one I was looking for. couldn't find it. we can close this one.
