### ISSUE TITLE
Testing via `InMemoryConnector` and Kotlin coroutines fails with "No Vertx context found"

### ISSUE THREAD

**Issue by thjaeckle** [smallrye/smallrye-reactive-messaging#2162]
Hi.

I am trying to use `InMemoryConnector` to test a Kafka "in channel" in Kotlin:
```kotlin
    @Test
    fun testKafkaConsumer() {
        val inChannel = connector.source<LoRaWanMessage>("lorawan")
        val outChannel = connector.sink<Adaptable>("ditto")
        val message = mapper.readValue(kafkaMessage, LoRaWanMessage::class.java)
        inChannel.send(message) // throws java.lang.IllegalStateException: No Vertx context found. Consider using @NonBlocking on the caller method, or make sure the upstream emits items on the Vert.x context

        await().until(outChannel::received) { t -> t.size == 2 }
        ...
   }
```

The "lorawan" incoming channel looks like:
```kotlin
    @Incoming("lorawan")
    suspend fun processor(kafkaMessage: Message<LoRaWanMessage>) {
       ... 
       // emits to channel "ditto"
    }
```

If I make the `processor` function not `suspend`able, the unit test works.  
I however want to make use of Kotlin "coroutines".
Should this work? Did I understand something wrong?

**Comment by cescoffier** [comment]
The in-memory processor won't work with co-routine at the moment. It does not create Vert.x context for the message.

**Comment by cescoffier** [comment]
(maybe some context... if we start using Vert.x context, it would make the in-memory connector async. So a problem per see, but it would make testing slightly more complex (as you would need to wait for the message to be sent and processed). 

@ozangunalp WDYT?

**Comment by ozangunalp** [comment]
I'd need to try it first but I think sending messages to the in-memory connector inside a Vert.x context should work already. 
Of course, there'll be added complexity with `await`s and such as it'll execute on the event loop.

I am writing at the top of my head but it would look like this :
```java
@Inject
Vertx vertx;

@Inject
InMemoryConnector connector; 
...

var source = connector.source("channel);
var ctx = vertx.getOrCreateContext();
ctx.runOnContext(() -> source.send(ContextAwareMessage.of(myPayload));
```

The key here is to use the `ContextAwareMessage` type to propagate the context in message metadata. This happens transparently in other connectors.
Again I'll check out myself to see if everything behaves correctly with coroutines in this case.

**Comment by thjaeckle** [comment]
Cool, thanks a l lot @ozangunalp 
Will have a look how and try to get it to work 👍

**Comment by ozangunalp** [comment]
Closing this as the solution is given in the previous comment
