### ISSUE TITLE
Remove the hard dependency on JSON in the MQTT connector

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#217]
Related to https://github.com/quarkusio/quarkus/pull/4194.

**Comment by misl** [comment]
Looking at `mvn help:effective-pom` it show 3 dependencies related to JSON. However all 3 are part of dependency management, not actual dependencies. Using `mvn dependency:tree` shows no dependencies with JSON in their name at all.

**Comment by cescoffier** [comment]
Cleaning up - this has been fixed.
