### ISSUE TITLE
RabbitMQ - Set multiple addresses to connect to a cluster

### ISSUE THREAD

**Issue by Kyo667** [smallrye/smallrye-reactive-messaging#2174]
Hello,

The vert.x RabbitMQ client provides an 'addresses' parameter via RabbitMQOptions to specify multiple RabbitMQ nodes. Unfortunately there is no corresponding property to set the parameter for SmallRye RabbitMQ connections. Is it possible to add a 'addresses' property representing the underlying config option?

Thank you for you attention.

**Comment by neon-dev** [comment]
I am missing this option, too.
Originally I thought it was an issue with `quarkus-smallrye-reactive-messaging-rabbitmq` which I was going to use, but soon found out that all what's missing is just the `addresses`/`rabbitmq-addresses` property and the mapping in:
https://github.com/smallrye/smallrye-reactive-messaging/blob/3c6e35f4183d4041d0bb4e859edd85787d8dc57d/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/RabbitMQClientHelper.java#L74-L75
The RabbitMQ client already comes with a parsing method that can be used for this:
https://github.com/rabbitmq/rabbitmq-java-client/blob/c8673750dc51b4f44d944c5c80e4ac38d59e1ad0/src/main/java/com/rabbitmq/client/Address.java#L177

Would be great to find support for this soon, thank you!
