### ISSUE TITLE
Really slow reactive KafkaProducer

### ISSUE THREAD

**Issue by FreifeldRoyi** [smallrye/smallrye-reactive-messaging#220]
Hi
I added reactive Kafka support to a really simple Quarkus service I wrote that receives HTTP requests, doing some transformation to the data and sends it to Kafka.
The messages are emitted to Kafka as `Emitter<List<JsonObject>>` and on the Kafka end:
```
    @Incoming("incoming")
    @Outgoing("to-kafka")
    public Flowable<KafkaMessage<String, String>> toKafka(Flowable<Message<List<JsonObject>>> styxes) {
        return styxes
                .flatMapIterable(Message::getPayload)
                .map(s -> KafkaMessage.of(s.getJsonObject("metadata").getString("event_id"), s.toString()))
                .onBackpressureDrop(message -> {
                    // send metrics
                })
                .doOnNext(message -> {
                    // send metrics
                });
    }
```

The list contains only 1 element so it's 1:1 in:out ratio.
I'm not sure why but It's not handling the load. Inbound HTTP request are `~333msg/sec`.
Simple KafkaProducer with default setting should handle it perfectly with no problem.. Not sure why I see metrics from the backpressure section.

How can I tackle this issue?

Thank you

**Comment by cescoffier** [comment]
It might be due to the acknowledgment. It waits until the message is correctly written before consuming next.

Can you try to set `waitForWriteCompletion` to `false`:

`mp.messaging.outgoing.your-channel. waitForWriteCompletion=false`

**Comment by FreifeldRoyi** [comment]
Documentation states that it defaults to false and I hadn't used it. I'll try to add it explicitly just in case..

**Comment by FreifeldRoyi** [comment]
@cescoffier That helped!
[The documentation is misleading](https://smallrye.io/smallrye-reactive-messaging/#_forwarding_messages_to_kafka) in the default value part. 

Thank you very much!!

**Comment by cescoffier** [comment]
Damn! I need to update the doc!

**Comment by cescoffier** [comment]
Created https://github.com/smallrye/smallrye-reactive-messaging/issues/223
