### ISSUE TITLE
Is SmallRye JMS JMSXGroupID aware , what variant Ordered or Ordered applies

### ISSUE THREAD

**Issue by ashboson** [smallrye/smallrye-reactive-messaging#2205]
There is a partitioning feature in ActiveMQ 
https://activemq.apache.org/how-do-message-groups-compare-to-selectors
I assumed smallrye has support for such semantics in context of kafka, does such semantics work in JMS too, if so how

**Comment by cescoffier** [comment]
Unfortunately, no, as it's something custom. 

We could allow headers I guess. But even this might be specific.

**Comment by ashboson** [comment]
Would Camel connector be able to achieve that?

**Comment by cescoffier** [comment]
I don't know, you need to check the JMS or ActiveMQ components of Camel.
