### ISSUE TITLE
Load/change consumer topics at runtime

### ISSUE THREAD

**Issue by KaisNeffati** [smallrye/smallrye-reactive-messaging#2213]
Hey, is there a way to do/(add support) for dynamic topics but for consumers ?
I am in case where i need to load the consumers topics from database at runtime. I've seen some code on stackoverflow but it's not quit clear 

He would do something like this at runtime : 
`System.setProperty("mp.messaging.incoming.price.topics", "example1,example2");`

So my questions are the following : 

Hwo can I charge my topics to consume from at startup ?

And is there a way to change this list of consumers topics at runtime ?

**Comment by cescoffier** [comment]
You cannot do this.

What you can do is use the regexp to capture the topics. You will start receiving the message when a new topic matching the regexp is created. Note that it only gets the new topics every "metadata refresh time". 


If you want to use dynamic consumer, you would need to use the low-level kafka client.
