### ISSUE TITLE
Incoming message NACKed using the JMS connector never gets redelivered and appears to be "stuck" in the client

### ISSUE THREAD

**Issue by enicolaescu** [smallrye/smallrye-reactive-messaging#2218]
I am using the JMS connector and Apache Artemis as the broker. After sending a message to the queue , inside my @Incoming method I return `message.nack(exception)`.
I expect the NACKed message to be redelivered instantly another 9 times (based on the default broker settings), get NACKed another 9 times and then be sent to the dead letter queue.
 For instance using the AMQP connector I get this intended behavior by setting the failure strategy to `modified-failed`.

Instead, it appears that the messages get "stuck" in the client side. If I go to the broker console and browse the queue I get the message `No Items Available` with the message counter in the bottom right increasing every time I send a new message to the queue.
After I shutdown the quarkus application I can see all the messages.
When I restart the quarkus application all these messages will be redelivered once, get "stuck" again and will become unavailable from the broker console.

From what I recall in a previous spring project using JMS I had the same issue and was able to solve it by setting the `consumerWindowSize` value to 0 inside the connection url to the broker, but it seems it doesn't do anything here

#################
To reproduce the issue:

1) Start the apache artemis container:
```
docker pull quay.io/artemiscloud/activemq-artemis-broker:artemis.2.27.1
docker run -d -p 8161:8161 -p 61616:61616 -e AMQ_USER=artemis -e AMQ_PASSWORD=artemis -e AMQ_EXTRA_ARGS="--host 0.0.0.0 --http-host 0.0.0.0 --relax-jolokia" quay.io/artemiscloud/activemq-artemis-broker:artemis.2.27.1
```

The console is accessible at localhost:8161 with credentials artemis/artemis
You should also go to JMX -> org.apache.logging.log4j2 -> org.apache.activemq logger and set the log level to DEBUG.
You also need to create an address, from the left menu Artemis -> broker -> addresses, create an address and a queue, both named `starting-queue` and of type ANYCAST

2) Run the quarkus application:

```
quarkus create app org.acme:jms-quickstart --extension='resteasy-reactive,io.quarkus:quarkus-smallrye-reactive-messaging' --no-code
```

Add the dependencies to pom.xml:
```
     <dependency>
         <groupId>io.smallrye.reactive</groupId>
         <artifactId>smallrye-reactive-messaging-jms</artifactId>
         <version>4.7.0</version>
     </dependency>
     <dependency>
         <groupId>org.apache.activemq</groupId>
         <artifactId>artemis-jakarta-client</artifactId>
         <version>2.27.1</version>
     </dependency>
     <dependency>
         <groupId>jakarta.jms</groupId>
         <artifactId>jakarta.jms-api</artifactId>
         <version>3.1.0</version>
    </dependency>
```

Inside the `org.acme` package in the project create the 2 files:
`JMSClient.java`
```
package org.acme;

import java.util.UUID;
import java.util.concurrent.CompletionStage;

import org.eclipse.microprofile.reactive.messaging.Channel;
import org.eclipse.microprofile.reactive.messaging.Emitter;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.jboss.logging.Logger;

import io.smallrye.reactive.messaging.annotations.Blocking;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/jms")
public class JMSClient {

	private static final Logger LOGGER = Logger.getLogger(JMSClient.class);

	@Channel("starting-queue-out")
	Emitter<String> emitterStartingQueue;

	@POST
	@Path("/request")
	@Produces(MediaType.TEXT_PLAIN)
	public String createRequest() {
		UUID uuid = UUID.randomUUID();

		LOGGER.info("Sending: " +uuid.toString());
		CompletionStage<Void> completionStage = emitterStartingQueue.send(uuid.toString());
		completionStage.toCompletableFuture().join();

		return uuid.toString();
	}

	@Incoming("starting-queue-in")
	@Blocking
	public CompletionStage<Void> process(Message<Object> message) {
		LOGGER.infof("received: %s", message.getPayload().toString());
		
		LOGGER.info("rejecting: " +message.getPayload());
		return message.nack(new RuntimeException());
	}
}
```

`ConnectionFactoryBean.java`
```
package org.acme;

import org.apache.activemq.artemis.jms.client.ActiveMQJMSConnectionFactory;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import jakarta.jms.ConnectionFactory;

@ApplicationScoped
public class ConnectionFactoryBean {
	@Produces
	ConnectionFactory factory() {
		String uri = "tcp://localhost:61616";
		String user = "artemis";
		String password = "artemis";
	
		ActiveMQJMSConnectionFactory factory = new ActiveMQJMSConnectionFactory(uri, user, password);
		
		return factory;
	}
}
```

Inside `application.properties` copy these properties:
```
mp.messaging.outgoing.starting-queue-out.connector=smallrye-jms
mp.messaging.outgoing.starting-queue-out.destination=starting-queue
mp.messaging.outgoing.starting-queue-out.durable=true

mp.messaging.incoming.starting-queue-in.connector=smallrye-jms
mp.messaging.incoming.starting-queue-in.destination=starting-queue
mp.messaging.incoming.starting-queue-in.session-mode=CLIENT_ACKNOWLEDGE
```

Run the application
`quarkus dev` from inside the project folder

Send a message to the queue
POST `http://localhost:8080/jms/request`

**Comment by cescoffier** [comment]
JMS does not have negative-acknowledgement support - or, at least, I didn't see anything in the spec.

**Comment by enicolaescu** [comment]
I guess it was an oversight on my part, seeing the negative acknowledgement in the general concepts section but it isn't in the JMS connector section. 
In that case I believe the only way to "reject" and force a redeliver of a jms message would be to not acknowledge it and close the consumer (and open a new one to replace it). But I assume manually closing the consumer is not something that is supported in this project, or at least I can't find mention of it anywhere

Do you have any other idea how I could do this?

**Comment by cescoffier** [comment]
No, unfortunately, I'm not a JMS expert.
