### ISSUE TITLE
Configuring AMQP connector for better throughput

### ISSUE THREAD

**Issue by Tomboyo** [smallrye/smallrye-reactive-messaging#2232]
I have a Quarkus application with a channel that consumes messages using the smallrye AMQP connector and produces messages with the Kafka connector. My experience so far is that the channel has very low throughput at approximately one message every two seconds when deployed to a real network, even with relatively small messages and minimal processing. To the best of my understanding, this is because the AMQP connector doesn't prefetch any messages, and the channel waits for the last message to be ACKd by Kafka before fetching the next message from the AMQP broker.

In order to improve throughput I've deployed replicas of my application. I am looking for and/or requesting ways to configure smallrye so that each instance of my application makes better use of available resources.

The options that occur to me are (1) provide a way to configure a larger prefetch so that the channel doesn't spend as much time waiting, and (2) provide a way to deploy multiple instances of a channel so that multiple consumers and producers are running in tandem (I think this is possible using RabbitMQ per #1699 and #1706).

[Edit] I'm not entirely sure, but I think the `@Blocking` annotation could be number 3. With a larger prefetch, I think that would let one channel (using one consumer-producer pair) process messages as fast as the consumer can retrieve them by scaling the thread pool out. Does that sound right?

Thanks, and please let me know if I'm simply overlooking existing configuration options. I appreciate it.

**Comment by cescoffier** [comment]
By default, you have a single thread processing the message - so it keep the order. If the order is not important, you can use @Blocking with ordered=false.

**Comment by Tomboyo** [comment]
Ah, okay. Is it correct to say that when a channel is ordered, it will wait to consume the next message from the inbound connector until the message sent to the outbound connector has been ACKed? (e.g. we retrieve a message from AMQ, process it, then publish to Kafka synchronously. Once Kafka ACK's the publisher, the next message may be retrieved via AMQ.) And so my original concern about prefetch was misguided -- the bottleneck would be the rate at which we can synchronously publish to Kafka, not the rate at which we can fetch messages from AMQ?

Thanks. I'll mark this closed because I think the `@Blocking` annotation does what I was looking for, and I just overlooked it.

**Comment by cescoffier** [comment]
Exactly!
