### ISSUE TITLE
MQTT protocol 

### ISSUE THREAD

**Issue by CCH0124** [smallrye/smallrye-reactive-messaging#2243]
When I used smallrye-reactive-messaging integrates mqtt. 

I want to set mqtt version to v5, but I don't find any parameter.

**Comment by ozangunalp** [comment]
The MQTT connector is based on vertx-mqtt client which is only 3.1.1 spec compliant. There is an open issue on vertx-mqtt on this : https://github.com/vert-x3/vertx-mqtt/issues/161

**Comment by CCH0124** [comment]
I got it. Thanks for your reply. 👍
