### ISSUE TITLE
Split package warning with -jackson or -jsonb libraries with Quarkus

### ISSUE THREAD

**Issue by josephearl** [smallrye/smallrye-reactive-messaging#2261]
When using `smallrye-reactive-messaging-jackson` or `smallrye-reactive-messaging-jsonb` with Quarkus you get a split package warning because both `JacksonMapping` and/or `JsonBMapping` are in the same package `io.smallrye.reactive.messaging.json` as `JsonMapping` but in different artifacts.

**Comment by cescoffier** [comment]
Yes, we need to ensure they are not in the same package. But I don't think you can use both at the same time.

**Comment by josephearl** [comment]
@cescoffier the issue is JacksonMapping is in the same package as JsonMapping (and same for JSON-B)

**Comment by cescoffier** [comment]
Yes, I understand the issue (just opened a PR), but having both may not work as expected.
