### ISSUE TITLE
AMQP Example  pom dependency refer to version 4.10.0 which is not available on maven repo

### ISSUE THREAD

**Issue by dev-mansonthomas** [smallrye/smallrye-reactive-messaging#2287]
I'm trying to run 

smallrye-reactive-messaging/examples/amqp-quickstart

after cloning this repo.

I get the follower maven errors: 
Unresolved dependency: 'io.smallrye.reactive:smallrye-reactive-messaging-provider:jar:4.10.0-SNAPSHOT'
Unresolved dependency: 'io.smallrye.reactive:smallrye-reactive-messaging-amqp:jar:4.10.0-SNAPSHOT'

Checking here : 
https://mvnrepository.com/artifact/io.smallrye.reactive/smallrye-reactive-messaging-provider

The version 4.10 is not published.

So either the example should be fixed or the 4.10 should be published

**Comment by dev-mansonthomas** [comment]
The instruction in the README.md at the root of the project also fails to build (either using IntelliJ maven integration or command line)

<img width="1314" alt="image" src="https://github.com/smallrye/smallrye-reactive-messaging/assets/5695269/0fa359b5-f5b7-44de-bc5f-26932fe098dc">

[smallrye-reactive-messaging-example-build.log](https://github.com/smallrye/smallrye-reactive-messaging/files/12617516/smallrye-reactive-messaging-example-build.log)

**Comment by ozangunalp** [comment]
Quickstart examples depend on the current development version of project artifacts. 
If you have a fresh checkout, you can run `mvn -T1C clean install -DskipTests` (build all modules by skipping tests). 
You can then go through the examples. 

Although for AMQP quickstart I'd recommend the Quarkus guide: https://quarkus.io/guides/amqp

**Comment by dev-mansonthomas** [comment]
Thanks @ozangunalp 

I would like to try to implement a new provider for Solace PubSub+ event broker using SMF as a protocol.

PubSub+ supports AMQP 1.0 so I wanted to first have a running example against the broker and then try to implement a new provider. 

Do you have suggestion/resources on how to go this way ? 

Would this project accept such contributions once it's tested ?

**Comment by ozangunalp** [comment]
Of course contributions are welcome!

I've an internal document for implementing connectors. I can arrange it a bit and make it public on the wiki.

As for the PubSub+ AMQP 1.0 support, I think it should just work.

**Comment by cescoffier** [comment]
Closing. 

(and yes, we would welcome a Solace connector!)

**Comment by dev-mansonthomas** [comment]
> I've an internal document for implementing connectors. I can arrange it a bit and make it public on the wiki.

I'm still interested in that documentation :)
