### ISSUE TITLE
Publisher confirms in smallrye-rabbitmq

### ISSUE THREAD

**Issue by i96751414** [smallrye/smallrye-reactive-messaging#2294]
Hello,

Apologies in advance if this is being asked in the wrong place.

Is there any way to have publisher confirms on smallrye-rabbitmq connector? I've noticed that confirms are already enabled, but I haven't found a way to confirm the message was received by rabbit (usually this is done through waitForConfirmsOrDie method of the channel).

Thanks

**Comment by ozangunalp** [comment]
I've checked why we aren't waiting for the publish confirms. 
The vertx-rabbitmq-client feature that we use is half-baked. It calls the confirm.select and subscribes to publish confirmations but doesn't complete publish futures on confirmation received. 

I'll need to contribute to the `vertx-rabbitmq-client` to enable that, and provide this with a flag in rabbitmq connector.

**Comment by amricko0b** [comment]
Hello, @ozangunalp and thanks for your clarification!
Any updates on this?

**Comment by ozangunalp** [comment]
The changes were included in vertx 4.5, we are planning on bumping to 4.5 early next year.
