### ISSUE TITLE
smallrye-reactive-messaging-jackson.jar missing /META-INF/beans.xml file

### ISSUE THREAD

**Issue by am-tribia** [smallrye/smallrye-reactive-messaging#2303]
Why is smallrye-reactive-messaging-jackson.jar missing /META-INF/beans.xml file? I get the following error when I use 
smallrye-reactive-messaging-jms:4.10.0 and smallrye-reactive-messaging-jackson:4.10.0

```ERROR [io.sma.rea.mes.jms] (executor-thread-1) SRMSG15800: Unable to send message to JMS: java.lang.NullPointerException: Cannot invoke "io.smallrye.reactive.messaging.json.JsonMapping.toJson(Object)" because "this.jsonMapping" is null```

_Originally posted by @am-tribia in https://github.com/smallrye/smallrye-reactive-messaging/issues/2272#issuecomment-1739019051_

**Comment by ozangunalp** [comment]
I think those json modules didn't have `beans.xml` files to begin with. I am not sure why. Did your example work with 4.9.0 ?

**Comment by am-tribia** [comment]
> I think those json modules didn't have `beans.xml` files to begin with. I am not sure why. Did your example work with 4.9.0 ?

Nope, it didn't work in 4.9.0 either. I assume `smallrye-reactive-messaging-jackson` was a split from `smallrye-reactive-messaging` that had `beans.xml`.
