### ISSUE TITLE
Managed Vertx instance should be closed after all Kafka resources have been closed

### ISSUE THREAD

**Issue by mswiderski** [smallrye/smallrye-reactive-messaging#233]
This issue originates from Quarkus application using quarkus-smallrye-reactive-messaging-kafka. It is thrown for each and every producer that is created within the application thus occurs multiple times.

````
2019-10-01 12:03:18,276 ERROR [org.apa.kaf.cli.pro.KafkaProducer] (vert.x-worker-thread-11) [Producer clientId=producer-2] Interrupted while joining ioThread: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1313)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1161)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1138)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1117)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$close$12(KafkaWriteStreamImpl.java:238)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

this interrupted thread seems to originate from

````
	VertxThread(Thread).interrupt() line: 985	
	ThreadPoolExecutor$Worker.interruptIfStarted() line: 663	
	ThreadPoolExecutor.interruptWorkers() line: 761	
	ThreadPoolExecutor.shutdownNow() line: 1407	
	WorkerPool.close() line: 43	
	VertxImpl.lambda$deleteCacheDirAndShutdown$25(Handler, AsyncResult) line: 838	
	2050620396.handle(Object) line: not available	
	ContextImpl.lambda$null$0(Handler, AsyncResult, Void) line: 330	
	183555305.handle(Object) line: not available	
	EventLoopContext(ContextImpl).executeTask(T, Handler<T>) line: 369	
	EventLoopContext.lambda$executeAsync$0(Handler) line: 38	
	621014131.run() line: not available	
	AbstractEventExecutor.safeExecute(Runnable) line: 163	
	NioEventLoop(SingleThreadEventExecutor).runAllTasks(long) line: 416	
	NioEventLoop.run() line: 515	
	SingleThreadEventExecutor$5.run() line: 918	
	ThreadExecutorMap$2.run() line: 74	
	FastThreadLocalRunnable.run() line: 30	
	VertxThread(Thread).run() line: 834
````

an investigation done by @vietj 

> This happens because of this in KafkaSink : https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaSink.java#L144
> 
> When the application is shutdown then the KafkaSink is shutdown concurrently because it does not wait for the completion. Since the Vertx instance is closed too, the Vert.x worker thread used for closing the producer will be interrupted which is the expected behavior.
> 
> I think that the Vertx instance should wait until all closeQuietly methods are executed. Either synchronously (as it does not seem to be a Vert.x thread) or asynchronously: https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#L43
> 
> e.g each closeQuietly could return a CompletionStage, then when internalVertxInstance is true the Vertx#close method will be called when all completion stages have been completed.

**Comment by cescoffier** [comment]
Yes, we can wait for completion. However, in this case, we don't control the Vert.x instance.

**Comment by mswiderski** [comment]
@cescoffier so does that mean it can't be addressed at all or will it be addressed in quarkus?

**Comment by cescoffier** [comment]
I already fixed it.

**Comment by mswiderski** [comment]
damn, you're fast :) thanks a lot

**Comment by cescoffier** [comment]
You're welcome.

**Comment by cescoffier** [comment]
going to release a new version this morning and bump the version in Quarkus.

**Comment by vietj** [comment]
I think it would be better if `closeQuietly` returns a `CompletionStage` so the caller thread can wait several of them simultaneously. If you have several source/sink to close, the caller thread will wait less time until all are completed.

**Comment by cescoffier** [comment]
I actually don't want to close them concurrently, as under the hood it closes the partitioner and other objects that may be shared between several sinks and sources.
