### ISSUE TITLE
Blocking consumer cannot access proper SLF4J-MDC when running in QuarkusTest

### ISSUE THREAD

**Issue by lostiniceland** [smallrye/smallrye-reactive-messaging#2335]
Following the [discussion on Zulip-Users](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/SLF4J.20MDC.20lost.20during.20QuarkusTest), we are facing the issue that we cannot properly use an SLF4J-MDC during a QuarkusTest when the tests are setup to log via Quarkus-LogManager.

Using ` smallrye-reactive-messaging-in-memory` during testing to push messages to a source which is consumed by a consumer annotated with `@Blocking`, writing a value to the MDC and immediately retrieving this value fails.

Quarkus Version 3.2.6.Final
JDK 17

The attached sample reproduces the issue. 

1. run ./mvnw test -> fails
2. comment out ` @Blocking` in `KafkaConsumer` 
3. run ./mvnw test -> success

[mdc.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/13062953/mdc.zip)

Workaround: put some other SLF4J Logging backend on the test-classpath and remove slf4-jboss-logmanager from Mavens surefire, failsafe.

Note: `@Transactional` has the same behaviour since it is implicitly applying `@Blocking`

**Comment by ozangunalp** [comment]
Indeed tests using `in-memory` connector doesn't handle vertx context and blocking automatically. 
You need to use the `@io.quarkus.test.vertx.RunOnVertxContext` annotation on your test method. (And you need to add the `quarkus-test-vertx` to your test dependencies.

This is the same as calling Hibernate Reactive transactions from tests. 
I think we better document this where we talk about messaging in-memory tests.

**Comment by lostiniceland** [comment]
Hmmm. It seems the MDC issue is solved, but now other parts of the code throw `BlockingOperationNotAllowedException`

`You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make...`

This is now coming from one of the Repositories which use Hibernate (non-reactive).

So it seems to be a bit more complicated getting the in-memory-connector to work when using plain-old-blocking code.

**Comment by cescoffier** [comment]
I'm wondering if we should not add duplicated context support in the in-memory connector? 

With an option to disable them if needed.

**Comment by lostiniceland** [comment]
Seems to work though now our tests which access an entitymanager no longer work because this needs to run on a worker-thread.
I am currently trying to create a Mutiny function which returns the result from the entitymanager and emits on the default-worker-pool, but I am struggleing a bit with the api.

**Comment by lostiniceland** [comment]
I am getting the feeling that we are hitting a blocker here. I can schedule something on a worker-thread by using Uni, but the tests needs to get the value of the Uni so it needs to wait, which I cant on the EventLoop.

Proper support for `@Blocking` in the `InMemoryConnector` seems to be needed.

**Comment by lostiniceland** [comment]
We did some more internal testing, weather or not it is feasible to either remove `@Blocking` or rewrite our tests. 

Removing the blocking or transactional (which is also causing blocking) nature from our consumers is not feasible with regards to our data consistency because message might not be consumed in order any more.
Another solution would be to replace the in-memory-connetors with a real Kafka test-sidecar by using testcontainers, but this is a big rewrite of our tests and also has some problems due to limitations what the clients-network allows (we cannot pull arbitrary images from the outside).

@ozangunalp would you be willing to put this feature-request in the backlog as @cescoffier mentioned? Or are there other concerns why this is not a good idea?

At the moment we have this weird workaround which makes it working, by using another slf4j backend (logback-classic) into the test-classpath which is not aware of Vertx and accidentally makes the MDC available on the Eventloop-Thread.

**Comment by ozangunalp** [comment]
I think it makes sense that the in-memory connector behaves closer to other connectors for handling context and hence context propagation.
I'll try something without breaking the existing behaviour. Maybe a flag to set like `runOnVertxContext` to schedule source events on Vert.x context.

**Comment by ozangunalp** [comment]
With #2374 this should be resolved. It is a channel attribute or a flag to set on the `InMemorySource` instance to activate dispatching events on Vert.x context. @lostiniceland would you have time to verify that this works as expected in your case?

**Comment by lostiniceland** [comment]
@ozangunalp 
I was able to successfully test the SNAPSHOT version for the Demo with ` streamIn.runOnVertxContext(true)` as well as setting `%test.mp.messaging.incoming.in.run-on-vertx-context=true`.
I will try to do the same tomorrow in our project. I am not sure if the customers environment allows to build Smallrye from source though, but lets see. But is looking very good. Thanks a lot.

**Comment by lostiniceland** [comment]
As expected, I currently cannot build Smallrye since I cannot clone from Github at the client.
I do think the fix is valid. Is there a roadmap for the next release?

**Comment by lostiniceland** [comment]
I can confirm that the release 4.12.0 fixes the issue at our client.

Thanks again.

**Comment by ozangunalp** [comment]
Perfect! It'll land in Quarkus soon
