### ISSUE TITLE
The javadoc should use @Channel instead of @Stream

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#236]
https://github.com/smallrye/smallrye-reactive-messaging/blob/b7e019596d02b72ba7659ddc773f1093cf26c852/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/annotations/OnOverflow.java#L18

**Comment by kenfinnigan** [comment]
This is fixed
