### ISSUE TITLE
Is it possible to send a "failed ack" ?

### ISSUE THREAD

**Issue by FreifeldRoyi** [smallrye/smallrye-reactive-messaging#239]
When using `Emitter` to bridge between the imperative and reactive styles, it seems that one cannot notify the emitter side that a message had failed to be sent.
Considering the following flow of REST->Emitter->Kafka there's no way of returning a proper error code back to the client.
I thought that maybe if a `failed ack` was available (maybe with an exception or a reason) it can help to achieve that behaviour.

Is there another way to do that?

**Comment by vietk** [comment]
There's an [open pull request](https://github.com/smallrye/smallrye-reactive-messaging/pull/339/files#diff-9767322e4cd6607a449e5bc1f42f5401) to improve the emitter's API to return a completion stage that is completed upon acknowledgement.

Cheerz
Kevin

**Comment by cescoffier** [comment]
Fixed in #573
