### ISSUE TITLE
Missing @QuarkusTest annotation in documentation

### ISSUE THREAD

**Issue by DavidRajnoha** [smallrye/smallrye-reactive-messaging#2392]
I have been following the https://smallrye.io/smallrye-reactive-messaging/4.4.0/concepts/testing/ and had to include the `@QuarkusTest` annotation for the  injection of the `InMemoryConnector` to work properly.

Steps to reproduce:
Follow the instructions on https://smallrye.io/smallrye-reactive-messaging/4.4.0/concepts/testing/.

Suggested fix:
```
...
import io.smallrye.reactive.messaging.memory.InMemorySource;

@QuarkusTest
public class MyTest {

    // 1. Switch the channels to the in-memory connector:
    @BeforeAll
    public static void switchMyChannels() {
...
```

Environment:
Java 17.0.9
Maven 3.9.5
smallrye-reactive-messaging-in-memory 4.4.0

**Comment by ozangunalp** [comment]
The Reactive Messaging documentation is not Quarkus-specific. Given examples are therefore generic.
