### ISSUE TITLE
Surprising InMemoryConnector handling of AMQP metadata

### ISSUE THREAD

**Issue by goldmann** [smallrye/smallrye-reactive-messaging#2407]
I'm using the `InMemoryConnector` as part of a Quarkus application test suite. This application is sending and receiving AMQP messages and I wanted to test it.

My code is similar to what is in the exmples:

```java
Optional<IncomingAmqpMetadata> metadata = incoming.getMetadata(IncomingAmqpMetadata.class);
metadata.ifPresent(meta -> {
    String address = meta.getAddress();
    String subject = meta.getSubject();
    boolean durable = meta.isDurable();
    // Use io.vertx.core.json.JsonObject
    JsonObject properties = meta.getProperties();
    // ...
});
```

The important bit is the use of `IncomingAmqpMetadata` as the metadata wrapper.

In my test I was hoping to use an approach similar to what is (again) in the docs:

```java
OutgoingAmqpMetadata metadata = OutgoingAmqpMetadata.builder()
        .withDurable(true)
        .withSubject("my-subject")
        .build();

// Create a new message from the `incoming` message
// Add `metadata` to the metadata from the `incoming` message.
return incoming.addMetadata(metadata);
```

Unfortunately, the `InMemoryConnector` seems to just forward messages as-is and on the receiver part I get metadata wrapped within the `OutgoingAmqpMetadata` which is something I did not expect.

My workaround is to create messages with the `IncomingAmqpMetadata` and sending them to the channel. This is counter-intuitive.

Any ideas?

**Comment by ozangunalp** [comment]
The InMemoryConnector for testing is independent of connector implementations, so it is not related to the metadata provided by the connectors. I think your workaround is correct.
