### ISSUE TITLE
Pulsar Consumer with Topic Pattern creates a topic using a channel name

### ISSUE THREAD

**Issue by michalcukierman** [smallrye/smallrye-reactive-messaging#2467]
Pulsar allows to create consumers with only topic pattern:
https://pulsar.apache.org/docs/3.1.x/concepts-messaging/#multi-topic-subscriptions

SmallrRye uses channel name as a fallback for a topic, even if the pattern should be used:
https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L76

This may be problematic, because the topics are created in the `public/default` namespace. Some problems I see:
- unnecessary topics are created
- unnecessary subscriptions are created
- multiple consumers may be assigned to the topic using default namespace
- error may occur, if the client does not have access to the default namespace (no access rights)

Proposal:
Skip setting the topic name, if it's not defined and the pattern is available.

I can create the PR, if the solution is accepted.

**Comment by ozangunalp** [comment]
There is already a check against overriding the already set topic. 

But one would only need to write a correct condition for it to work....

https://github.com/smallrye/smallrye-reactive-messaging/blob/0a994af85d2b89fc0e9357fe775ef6af8ecb1576/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L228-L231

https://github.com/smallrye/smallrye-reactive-messaging/blob/0a994af85d2b89fc0e9357fe775ef6af8ecb1576/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L76-L78

I'll create the PR to fix the check.
