### ISSUE TITLE
Enable `KafkaRequestReply` on the same topic

### ISSUE THREAD

**Issue by iLem0n** [smallrye/smallrye-reactive-messaging#2488]
Are you planning the `KafkaRequestReply` to work on the same topic? 

What I currently see is the need of two distinct topic for the logic to work, we have several use cases where request records are published on the same topic as response records.

I think  the basic problem here is how to distinguish the requests from the replies to handle them properly.
Played a little bit around with the code and think i found a lean solution by injecting annotated predicate like `isReplyPredicate` which can be used here as an extra if-condition to check whether a message is a reply or not: 
https://github.com/smallrye/smallrye-reactive-messaging/blob/533d77f23dd782437d20d1b83ce6b86f4808f7b9/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/reply/KafkaRequestReplyImpl.java#L257

Per default it can always pass so u don't have to provide it. 

What do you think?

**Comment by ozangunalp** [comment]
And your request and reply records would have the same type? If not the reply consumer would have a deserialization failure.

**Comment by iLem0n** [comment]
> And your request and reply records would have the same type? If not the reply consumer would have a deserialization failure.

That indeed a problem i faced afterwards while generalizing my approach. The first version did work because i used simple String serialization thus injecting a `Predicate<String>` wasn't a problem. At the point of injection the generic types are not known and even if they would they need to be equal to not run into deserialization exception. 

At least it was just one idea to solve our current single topic request reply problem.

Do u have better ideas archive this?

**Comment by ozangunalp** [comment]
"Normally" only the correlation id header is required to be present in the reply message. 
So we could imagine by default the reply consumer can filter out messages containing the reply topic header. 

For de-serialization errors if we set the `fail-on-deserialization-failure` to `false` both on requester and replier it should be fine. 

Only case I see this would break is a custom replier that sends back all request headers with the replier.

**Comment by ozangunalp** [comment]
Here is a working solution with minimal change : https://github.com/smallrye/smallrye-reactive-messaging/pull/2495

**Comment by darkeagle1337** [comment]
Hi I know the issue is closed but I think there is a missleading element in the documentation.

The Method "process" of the class "KafkaCustomHeaderReplier" should remove the header "MY_TOPIC" otherwise the following line will not work and the messages is not processed.

https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/reply/KafkaRequestReplyImpl.java#L272
