### ISSUE TITLE
[Kafka Test Companion] Inconsistent handling of properties

### ISSUE THREAD

**Issue by Abaudat** [smallrye/smallrye-reactive-messaging#2489]
### The problem
In Kafka Test Companion's `ProducerBuilder` and `ConsumerBuilder`, the properties seem to be treated inconsistently:

- The constructors of both `ProducerBuilder` and `ConsumerBuilder` use the signature `Map<String, Object>`
- The `properties` field in both [`ProducerBuilder`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ProducerBuilder.java#L54) and [`ConsumerBuilder`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L64) also use the signature `Map<String, Object>`
- The method [`ConsumerBuilder#withProps`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L265) also use the signature `Map<String, Object>`

However:
- The method [`ProducerBuilder#withProps`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L265) uses the signature `Map<String, String>`
- Both [`ProducerBuilder#withProp`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ProducerBuilder.java#L212) and [`ConsumerBuilder#withProp`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L254) use the type `String` for the value

As both `KafkaConsumer` and `KafkaProducer` support properties of the form `Map<String, Object>`, it seems like `ProducerBuilder` and `ConsumerBuilder` should use this form instead of restricting the property value to `String`.

### Suggestion of implementation

- Change [`ProducerBuilder#withProps`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L265) to take a `Map<String, Object>`
- Change both [`ProducerBuilder#withProp`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ProducerBuilder.java#L212) and [`ConsumerBuilder#withProp`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java#L254) to use the type `Object` for the value

I am willing to work on the PR, I just need confirmation that this change would be welcome.

**Comment by ozangunalp** [comment]
Hi, Thank you for the detailed explanation. 
I think you are right. And of course, if you are willing to contribute it is always welcome!
