### ISSUE TITLE
Dynamic Outgoing topic for Apache Pulsar

### ISSUE THREAD

**Issue by vszakd** [smallrye/smallrye-reactive-messaging#2504]
Hello,
with AMQP and Kafka (that I know of) it's possible, with OutgoingMetadata, to set the address/topic at runtime for every single message sent.

I could not find anything about Pulsar, neither in the Metadata, nor in the documentation.

Is there a way to achieve that?

Thanks.

**Comment by ozangunalp** [comment]
Pulsar producers are configured and bound to a topic, I don't think there is a way to publish to a given topic per message.

**Comment by ozangunalp** [comment]
I don't think we'll address that in the near future. We can close it as not planned.
