### ISSUE TITLE
Azure Role Based Access control with AMQP 1.0

### ISSUE THREAD

**Issue by antoinechamot** [smallrye/smallrye-reactive-messaging#2506]
Hi,
I need to use smallrye with Azure service Bus. 
For security reasons, I can only use the recommended [passwordless connections using Role Based Access control  ](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-migrate-azure-credentials?tabs=dotnet%2Croles-azure-portal%2Csign-in-azure-cli%2Cservice-connector%2Cservice-connector-identity%2Cassign-role-service-connector)

Is it possible to configure smallrye to connect this way or not ? 
When I look at the AMQP connector, it don't see anything else than simple username /password.

**Comment by cescoffier** [comment]
I do not think we can. There is a AMQPOptioncusotmizer, maybe you can hook something here, but I doubt. 

I think you will need a custom connector.

**Comment by artragis** [comment]
Hello,
I see that the azure sdk is using the project-reactor lib. Do you think that we can easily use their SDK if we use the mutiny-reactor library? https://smallrye.io/smallrye-mutiny/1.6.0/guides/converters/#picking-the-right-dependency

**Comment by artragis** [comment]
Hello,
I think we can close this ticket. On our side we manage to create a custom connector that allows us to use Azure Service Bus with default identity.
We indeed had to use the `mutiny-reactor` lib and a custom message mapper to get the object: 
```java
return FlowAdapters.toFlowPublisher(
                ReactiveStreams.fromPublisher(receiver.receiveMessages()).map(AzureServiceBusMapper::convertToMessage)
                               .buildRs());
```

**Comment by cescoffier** [comment]
Thanks for the feedback - closing.
