### ISSUE TITLE
Deadlock when using Avro schema with pulsar

### ISSUE THREAD

**Issue by marekczajkowski** [smallrye/smallrye-reactive-messaging#2513]
I reported the issue https://github.com/smallrye/smallrye-reactive-messaging/issues/2493#issue-2146960922

which has been fixed by changing the condition to fetch schema that requires fetchnig. Unfotunately AvroSchema does not fulfill this condition and the issue still occurs.

**Comment by ozangunalp** [comment]
Ok as far as I understand we need to look for all the schemas using `AbstractMultiVersionReader`.
