### ISSUE TITLE
There should be a documented way to configure a default connector globally

### ISSUE THREAD

**Issue by mrickly** [smallrye/smallrye-reactive-messaging#2532]
The [smallrye-reactive-messaging documentation](https://smallrye.io/smallrye-reactive-messaging/latest/concepts/connectors/#configuring-connectors) states that "The connector attribute must be set for each mapped channel and indicates the name of the connector responsible for the channel". 
I would like to be able to configure a default connector globally to avoid repetitive configuration settings.

**Comment by ozangunalp** [comment]
In Quarkus the only connector available in classpath is discovered at build time and configured automatically for all channels.  But in Smallrye Reactive Messaging we don't have "default" connector setting.

**Comment by mrickly** [comment]
Ah, yes. I missed "Connector auto-attachment
If you have a single connector on your classpath, you can omit the connector attribute configuration". I'll try it out.

**Comment by mrickly** [comment]
@ozangunalp : My tests weren't successful. I get 
```
SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `contract-premiums`
```
when I omit the connector configuration.

**Comment by mrickly** [comment]
Ah, but we also had smallrye-reactive-messaging-in-memory in the test classpath. So you're right, works as advertised.
