### ISSUE TITLE
GlobalOpenTelemetry instance recreated in Reactive Messaging channels

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#2539]
https://github.com/quarkusio/quarkus/issues/39449

It can be injected with CDI with a failover to getOrCreate through `GlobalOpenTelemetry.get()`

**Comment by ozangunalp** [comment]
@kabir do you remember more than I do about our discussion ?

**Comment by kabir** [comment]
@ozangunalp No, sorry....
