### ISSUE TITLE
Kafka delayed retry topic not retrying after initial produce

### ISSUE THREAD

**Issue by nielsvhaldvb** [smallrye/smallrye-reactive-messaging#2566]
I'm currently implementing the delayed retry topic feature for Kafka, but I'm encountering difficulties getting it to function as expected.

- I've set up a topic with the suffix "_600000" (indicating a delay of 600,000 milliseconds) and a global timeout of 6,000,000 milliseconds. The default retry count is set to 10.
- When producing a failing message, it does get redirected to the delay retry topic with the correct headers and key. However, the value of the message in this topic appears as NULL.
- Afterwards a message never appears back on the topic past a retry-count header of 0 (and it did not succeed).

Here are some additional details:

-     I'm using the Confluent Avro serializers and deserializers for serialization.
-     The Kafka consumer default API timeout has been adjusted to 6,000,000 milliseconds to test its impact, but it doesn't seem to resolve the issue.

Could there be any known issues related to using such large timeouts or employing Avro serialization within retry topics? And should I be directly consuming messages from the delayed retry topic myself?

**Comment by ozangunalp** [comment]
The delayed-retry-topic policy consumes messages and schedules them according to the calculated delay, so you don't need to consume messages yourself. 

I think what's happening is, because the re-serialization of the message value results in NULL, it gets reconsumed by your application but doesn't get consumed because it's value is null. 

Can you try by forcing the serializer for the dlq with the config : `mp.messaging.incoming.[channel].dead-letter-queue.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer ` ?

I don't think the consumer API timeout is relevant here. The retried record gets consumed immediately by the application.

**Comment by nielsvhaldvb** [comment]
This is the config i'm already running

mp.messaging.incoming.direct-debit-status-update.key.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.direct-debit-status-update.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.direct-debit-status-update.failure-strategy=delayed-retry-topic
mp.messaging.incoming.direct-debit-status-update.default.api.timeout.ms=${DEFAULT_API_TIMEOUT_MS:6000001}
mp.messaging.incoming.direct-debit-status-update.dead-letter-queue.key.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.incoming.direct-debit-status-update.dead-letter-queue.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.incoming.direct-debit-status-update.delayed-retry-topic.max-retries=${DELAY_RETRY_TOPIC_MAX_RETRIES:10}
mp.messaging.incoming.direct-debit-status-update.delayed-retry-topic.topics=${DELAY_RETRY_TOPICS:dvb-dta-tst-sepa-incasso-status-update-dlq_600000}
mp.messaging.incoming.direct-debit-status-update.delayed-retry-topic.timeout=${DELAY_RETRY_TOPIC_TIMEOUT:6000000}

**Comment by ozangunalp** [comment]
It would be helpful if you could prepare a simple reproducer. Surely I can't reproduce it with only :
```
delayed-retry-topic.max-retries=10
delayed-retry-topic.topics=dlq_600000
delayed-retry-topic.timeout=6000000
```

**Comment by nielsvhaldvb** [comment]
I tracked the NULL issue to be a serialization issue which was unrelated. Still the message did not seem to be retried automatically. Can't continue with this now myself and decided to use a different retry strategy. Issue may be closed
