### ISSUE TITLE
Kafka consumer gets into a rebalance loop

### ISSUE THREAD

**Issue by marksouletheprogrammer** [smallrye/smallrye-reactive-messaging#2589]
We are running a Kafka consumer with quarkus and smallrye reactive messaging.

Quarkus: 3.2.10
Smallrye: 4.6.1
Kafka client: 3.4.0
Kafka broker: 3.6.0

Problem:

Very rarely our kafka consumer will get stuck into a rebalance loop. Here is a sample of the logs:

```
...normal message processing log...
...normal message processing log...
...normal message processing log...
{"@timestamp":"2024-03-22T12:57:21.159Z","logger_name":"io.smallrye.reactive.messaging.kafka","level":"INFO","message":"SRMSG18224: Executing consumer revoked re-balance listener for group '<redacted>'","thread_name":"smallrye-kafka-consumer-thread-2","@version":"1"}
{"@timestamp":"2024-03-22T13:02:24.243Z","logger_name":"io.smallrye.reactive.messaging.kafka","level":"INFO","message":"SRMSG18224: Executing consumer revoked re-balance listener for group '<redacted>'","thread_name":"smallrye-kafka-consumer-thread-2","@version":"1"}
{"@timestamp":"2024-03-22T13:02:34.142Z","logger_name":"io.smallrye.reactive.messaging.kafka","level":"INFO","message":"SRMSG18224: Executing consumer revoked re-balance listener for group '<redacted>'","thread_name":"smallrye-kafka-consumer-thread-2","@version":"1"}
```

This continues until we restart the consumer.

- Consumer is processing normally until rebalance occurs.
- When we get into this loop, Kafka does not reassign the partition. The partition is just building up lag.
- Restarting the consumer generally fixes it.

Consumer definition:
```
@Blocking
@Incoming("events")
public void consume(ConsumerRecords<GenericData.Record, GenericData.Record> consumerRecords) {
    ...
}
```

Cause: Unknown
Steps to recreate: Not able to recreate. It generally happens when our prod consumer is rebalancing while under load.

I do not know if this is in any way related to a smallrye problem. I figured I would post here just on the off chance that somebody has also seen this issue or knows of a potential cause.

Thank you!

**Comment by marksouletheprogrammer** [comment]
Yes you're right. The Confluent slack suggested the same. It hasn't happened again and we have not been able to recreate. If/when it does we will do more analysis.

**Comment by cescoffier** [comment]
Please re-open when you have more details.
