### ISSUE TITLE
IncomingConnector has no downstream

### ISSUE THREAD

**Issue by pengxo** [smallrye/smallrye-reactive-messaging#2593]
I want to integrate avro serialization/deserialization with confluent schema registry into quarkus. The `quarkus-smallrye-reactive-messaging-kafka` is used. I tried with the documentation in https://quarkus.io/guides/kafka-schema-registry-avro#confluent and it did not work well.  So I use `com.github.davidmc24.gradle.plugin.avro` and the dependency `org.apache.avro:avro` to generate the code at build time. However, there will be error indicating that the consumer is not available:

```
SRMSG00207: Some components are not connected to either downstream consumers or upstream producers:
	- IncomingConnector{channel:'kafka', attribute:'mp.messaging.incoming.kafka'} has no downstream
```

There is a consumer with annotation `@Incoming`. As long as I deactivate the avro gradle plugin and don't create java resource with the `.avsc` schema file, there will be no issue. The quarkus version 3.9.4 is used. I don't see the relationship between the error message and the plugin. Could you have a check?

**Comment by ozangunalp** [comment]
Please add a reproducer so that I can take a look.

**Comment by cescoffier** [comment]
The error means that connector does not have a downstream consumer.

Do you have a method using `@Incoming("kafka")`?

**Comment by pengxo** [comment]
There is a method with @Incoming("kafka"). Without the plugin, it works well and message can be retrieved.

**Comment by pengxo** [comment]
@ozangunalp , I will try to create a simple project to reproduce it. Before that it would be great if you could find something about it.

**Comment by ozangunalp** [comment]
That `@Incoming("kafka")` method has not been discovered at build time, why I don't know.

**Comment by pengxo** [comment]
Hi @ozangunalp , I created a sample project to reproduce it (see [sample](https://github.com/pengxo/quarkus-kafka-demo)).  

In the file `build.gradle.kts` when the plugin `id("com.github.davidmc24.gradle.plugin.avro") version("1.9.1")` is activated and the app is started with main function as entry point , then the error will appear. When debugging the `resolved` in `io.smallrye.reactive.messaging.providers.wiring.Graph` does not contain the kafka consumer. When the plugin is disabled and the app is started, then the `resolved` in  `io.smallrye.reactive.messaging.providers.wiring.Graph` contains the kafka consumer. 

It seems that the consumer can somehow not be found.

**Comment by ozangunalp** [comment]
> the app is started with main function as entry point

I don't get this part

In your reproducer when I uncomment the line `id("com.github.davidmc24.gradle.plugin.avro") version("1.9.1")` and a task dependsOn from kotlincompile to `generateAvroJava`. It builds ok with `./gradlew build` and it runs ok with `java -jar build/quarkus-app/quarkus-run.jar`

**Comment by pengxo** [comment]
Hi @ozangunalp , thanks for the test. The startup from you is different from what I did. I started the app by running the `main` function in file `Main.kt` in Intellij directly and I got the error when the plugin is acticated. This is what I meant about the main function as entry point. So actually it is equivalent to something like `java ... com.test.example.MainKt` . Not sure if this is somehow related to the extension of `smallrye-reactive-messaging`.

**Comment by ozangunalp** [comment]
Oh, I missed the main class. 
This seems to be related to https://github.com/quarkusio/quarkus/issues/39404
As a workaround, Intellij now detects a Quarkus app and sets up run/debug profiles. They work expectingly.

**Comment by pengxo** [comment]
Hi @ozangunalp , thanks for the information. they seem to be similar issues but a little bit different. Unfortunately it does not work well in IntelliJ even with the latest version. If you don't find any problem with this extension, then this issue can be closed.

**Comment by pengxo** [comment]
Hi @ozangunalp , I confirmed that it will affect other rest resources with the generated java code in kotlin project. So I think it is an issue that you mentioned and it should not be related to this extension. 

I will close this ticket. Thanks for your support.

**Comment by ozangunalp** [comment]
@pengxo thanks! I'll in the original issue.
