### ISSUE TITLE
Is not possible to add a custom batchReceivePolicy to the consumer

### ISSUE THREAD

**Issue by hermeswaldemarin** [smallrye/smallrye-reactive-messaging#2631]
When we add a configuration in Quarkus to provide a custom ConsumerConfigurationData with the batchReceivePolicy provided 

`
@Produces
@Identifier("goals")
public ConsumerConfigurationData<String> getConsumerGoalsConfig() {
  ConsumerConfigurationData<String> data = new ConsumerConfigurationData<>();
  data.setMaxPendingChunkedMessage(2000);
  data.setBatchReceivePolicy(
		  BatchReceivePolicy.builder()
				  .messagesFromMultiTopicsEnabled(false)
				  .maxNumBytes(10 * 1024 * 1024)
				  .maxNumMessages(1000)
				  .timeout(30, TimeUnit.SECONDS)
				  .build());
  
  return data;
}
`

This configuration is never sent to the builder.. 

We don't have [here](https://github.com/smallrye/smallrye-reactive-messaging/blob/5fd97395610010114b3010a9f3005aa867497d8a/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L99) a if to set the batchReceivePolicy to the builder when the batchReceivePolicy is provided in the conf instance. 

The process rely on [this](https://github.com/smallrye/smallrye-reactive-messaging/blob/5fd97395610010114b3010a9f3005aa867497d8a/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L78)  code. 

Even if I provide the batchReceivePolicy property in the Map returned by configResolver.configToMap the builder.loadConf will not get this info because it can't handle complex attributes. 

Will need to be used the same strategy used [here](https://github.com/smallrye/smallrye-reactive-messaging/blob/5fd97395610010114b3010a9f3005aa867497d8a/smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java#L82)  to set the batchReceivePolicy to the builder. 

Just adding this code make it work correctly

`
if (conf.getBatchReceivePolicy() != null) {
	builder.batchReceivePolicy(conf.getBatchReceivePolicy());
}
`

**Comment by ozangunalp** [comment]
I am sorry I couldn't totally follow the issue description. 
Did you provide the `batchReceive=true` in channel attributes in addition to the batchReceivePolicy you are building using `ConsumerConfigurationData` ?

**Comment by hermeswaldemarin** [comment]
Hey @ozangunalp , yes I've provided the batchReceive=true and I'm building providing the ConsumerConfigurationData setting the batchReceivePolicy there. But the batchReceivePolicy is never sent to the consumer builder in the PulsarIncomingChannel

**Comment by ozangunalp** [comment]
@hermeswaldemarin Indeed, it looks like a bug. 

Also, not related to the bug but due to a limitation in CDI you'd need to produce a `ConsumerConfigurationData<Object>` for the programmatic configuration to be taken into account.
