### ISSUE TITLE
Version 3.x problem with Vert.x 4.5.4

### ISSUE THREAD

**Issue by LucaT75** [smallrye/smallrye-reactive-messaging#2647]
Hi,
 version 3.x does not support Vert.x version 4.5.4,
 because in the latter a refactoring was done which resulted in
 to eliminate the io.vertx.core.impl.EventLoopContext class used in io.smallrye.reactive.messaging.kafka.impl.KafkaSource.

 I'm wrong ?
 
 I need to switch to 4.5.4 of Vert.x where is fixed some vulnerability , Is it possible to have a patch ?

Thanks in advance

**Comment by cescoffier** [comment]
Hello,

No, it's not possible to update the 3.x branch to Vert.x 4.4.x or 4.5.x - too many changes. It would break users. Note that Vert.x 4.3.x is not maintained anymore by the Vert.x project (see https://github.com/eclipse-vertx/.github/pull/5#issuecomment-2156419619).

If the vulnerability concerns SNI, reactive messaging is unaffected (we do not use SNI). 

Anyway, I would recommend updating to the latest major version of reactive messaging (4.x). The last release of 3.x was done 11 months ago.

**Comment by LucaT75** [comment]
HI,
 the vulnerability concerns incorrect validation of the certificate with a mismatched host.
 In smallrye we don't use NetClientOptions with the default configuration?

Thanks in advance

**Comment by cescoffier** [comment]
You means the host name verification algorithm? It's something we set explicitly in reactive messaging when needed.

**Comment by cescoffier** [comment]
Do you have a link on the vulnerability?

**Comment by LucaT75** [comment]
I am referring to this pool https://github.com/eclipse-vertx/vert.x/pull/3680

For my use case the incompatibility between smallrey 3.2.5 and Vert.x version 4.5.4, is due to 
io.smallrye.reactive.messaging.kafka.impl.KafkaSource in particular in 
 private final EventLoopContext context;

In this case resolution should be possible if KafkaSource used the interface
 private final ContextInternal context;

**Comment by cescoffier** [comment]
So, it's the hostname verification - SmallRye Reactive messaging does the right things every time we use a NetClient. We also recommend that any NetClient user clearly specify the hostname verifier they want to use. Te Vert.x PR makes mandatory setting one. 

So, Reactive messaging is not affected.
