### ISSUE TITLE
Kafka Compaion connects to multiple bootstrap servers at the start of the test

### ISSUE THREAD

**Issue by cj19** [smallrye/smallrye-reactive-messaging#2650]
In my Quarkus project I try to use actual kafka topics instead of in-memory ones. But seems like however I define my KafkaCompanion instance, it creates two instances.
```static KafkaCompanion companionResource = new KafkaCompanion("localhost:9092");```
This is how I create my instance for the test.
First the constructor runs with parameters like these:
![image](https://github.com/smallrye/smallrye-reactive-messaging/assets/19404874/08f38fa1-c26c-4974-9b24-ded82d235e45)
And after this it runs with my parameters (localhost:9092).
![image](https://github.com/smallrye/smallrye-reactive-messaging/assets/19404874/05e85eee-e51b-492d-841d-3686a95ef719)
I am using Quarkus framework with gradle and java 17.
Is this a normal behavior? Does this mean that there is another kafka instance running? Can I turn this off? Does the quarkus devservice cause this behavior?

**Comment by ozangunalp** [comment]
If you are using [`KafkaCompanionResource`](https://quarkus.io/guides/kafka#testing-using-a-kafka-broker), it by default creates a KafkaCompanion configured with dev service bootstrap.servers.

**Comment by cj19** [comment]
> If you are using [`KafkaCompanionResource`](https://quarkus.io/guides/kafka#testing-using-a-kafka-broker), it by default creates a KafkaCompanion configured with dev service bootstrap.servers.

As you can see I am using KafkaCompanion, and I dont want to use any embedded kafka or bootstrap service, because I have a local kafka installation. What are my possibilities?

**Comment by ozangunalp** [comment]
I was misunderstood. If you use 
```
@QuarkusTest
@QuarkusTestResource(KafkaCompanionResource.class)
```

in your tests it'll reuse the dev service or create the Kafka container, and create the KafkaCompanion instance. 

If you are testing against another broker instance, you don't need to use `@QuarkusTestResource(KafkaCompanionResource.class)`
