### ISSUE TITLE
How to get the offset of a KafkaMessage

### ISSUE THREAD

**Issue by ivangfr** [smallrye/smallrye-reactive-messaging#268]
Hi,

I'd like to know how to get the **offset** of a **KafkaMessage**? The offset information is there (as we can see in the picture)... Why is it not public as partition and topic name?

<img width="829" alt="Screen Shot 2019-10-19 at 17 32 22" src="https://user-images.githubusercontent.com/10564548/67147628-afcd6300-f296-11e9-8f57-e14ed4f1422d.png">

Best regards,

**Comment by cescoffier** [comment]
That's a great question!
We should definitely expose it in a better way. For now, you can do:

```
KafkaMessage msg = ...
ConsumerRecord record = ((ReceivedKafkaMessage) msg).unwrap();
record.getOffset();
```

**Comment by ivangfr** [comment]
Hey @cescoffier 

Just a small fix on the workaround you proposed. The method `getOffset()` doesn't exist in `ConsumerRecord`. The correct is `offset()`.

**Comment by cescoffier** [comment]
I've added `KafkaMessage.getOffset()` in https://github.com/smallrye/smallrye-reactive-messaging/pull/303
