### ISSUE TITLE
Suggestion: Incoming- & OutgoingKafkaRecord should override Message#addMetadata & Message#with*

### ISSUE THREAD

**Issue by slinstaedt-hlag** [smallrye/smallrye-reactive-messaging#2777]
While debugging some issues with regard to the public sub-types of `org.eclipse.microprofile.reactive.messaging.Message` implementation, I figured out, that at least the kafka's ones are not returning a type of itself for metadata additions like `Message#addMetadata` and ` Message#withMetadata`, because they are not overriding the corresponding methods. These methods are being used in some places (like `ObservationDecorator`) to *extend* a message with additional metadata, causing the original type being "lost".

Current workaround is to not rely on sub-types of `Message` and rather work their metadata directly.

**Comment by vietk** [comment]
Hello 
I think it's more or less a dup of #2505 with the same conclusion: specialized types of messages should not be used and rather inject/use the metadata if you need to work with the connector specific properties

I think it can be closed.

**Comment by slinstaedt-hlag** [comment]
As long as all non-payload-specific message data is being transported via metadata and not via Message's sub-types fields, I am totally okay with that. 

Perhaps we should deprecate these sub-types at some point and point developers to the use of metadata instead, as the mentioned decorators and likely others will break incoming message processors otherwise.
