### ISSUE TITLE
Executing JPA logic on consumer is not working fine

### ISSUE THREAD

**Issue by iabughosh** [smallrye/smallrye-reactive-messaging#282]
Dears,
I am trying to execute some JPA staff when I receive message from Kafka Topic using Smallrye Reactive messaging using Quarkus but it is not working fine. All details are at [Stackoverflow](https://stackoverflow.com/posts/comments/103457165?noredirect=1).

Need your input on this.

I am using Quarkus version 0.24.0.

**Comment by cescoffier** [comment]
This is now possible using the `@Blocking` annotation.

**Comment by iabughosh** [comment]
I saw it in the new Quarkus versions. Which one is better, using context-propagation or blocking annotation? I believe using blocking will be against 'reactive' paradigm.

**Comment by cescoffier** [comment]
Hello,

JPA is inherently blocking, so you need @Blocking.
Typically, I wrote the following code (using Panache):

package org.acme.panache;

import io.smallrye.reactive.messaging.annotations.Blocking;
import org.eclipse.microprofile.reactive.messaging.Incoming;

import javax.enterprise.context.ApplicationScoped;
import javax.transaction.Transactional;

@ApplicationScoped
public class PriceStorage {

    @Incoming("prices")
    @Blocking
    @Transactional
    public void store(int priceInUsd) {
        Price price = new Price();
        price.value = priceInUsd;
        price.persist();
    }

}

Clement

Le mer. 3 juin 2020 à 18:37, Ibrahim Abu Ghosh <notifications@github.com> a
écrit :
