### ISSUE TITLE
Clean up Emitter interface

### ISSUE THREAD

**Issue by xstefank** [smallrye/smallrye-reactive-messaging#284]
Points collected on the MP reactive hangout on which needs to be done before Emitter can be pushed up to spec: 

- [Emitter<T> send(T msg)](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/annotations/Emitter.java#L34) should return `CompletionStage<Void>`

- change javadoc with regards to `@OnOverflow` - https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/annotations/Emitter.java#L31

- rename `smallrye.messaging.emitter.default-buffer-size` to `mp.messaging.emitter.defult-buffer-size`

**Comment by Emily-Jiang** [comment]
Emtter L3, remove  "if the stream does not have any pending requests, "

**Comment by cescoffier** [comment]
The new emitter has been merged
