### ISSUE TITLE
RabbitMQ and Quarkus Dev Mode restart keeps previous connections

### ISSUE THREAD

**Issue by kdubb** [smallrye/smallrye-reactive-messaging#2853]
When using the RabbitMQ connector with Quarkus in dev mode, each restart creates new connections, but somehow leaves the connections from the previous start. These connections prefetch some of the messages in the queue but never process them. After a few restarts, you end up with lots of connections and no ability to process messages because the number of "active but zombied" connections outweighs the "active" connections and so they get the messages and do nothing with them.

I've tried disabling all the "automatic recovery" in dev mode but nothing seems to work.

I've also traced through the code and the RabbitMQ connector is definitely closing the connections upon shutdown, but after the restart completes, all the previous connections are active again; with only 1 being able to received and process messages.

**Comment by kdubb** [comment]
This is the state of the connections after 1 restart, prior to restart, there are 3 connections.
<img width="754" alt="Screenshot 2024-12-12 at 3 09 05 PM" src="https://github.com/user-attachments/assets/e6d2c915-3c63-42f2-a70d-f2bd18fe43bb" />

This is the queue state, you can see the previous connection has pre-fetched 3 messages and isn't doing anything with them, so they stay here until TTL, at which point they may be consumed again by one of the "active zombie" connections again.
<img width="713" alt="Screenshot 2024-12-12 at 3 09 59 PM" src="https://github.com/user-attachments/assets/cd8ed507-3636-4ecc-8053-2dee814301ee" />

**Comment by kdubb** [comment]
Setting `reconnect-attempts = 0` works around this issue for dev mode.

**Comment by ozangunalp** [comment]
It is now released with 4.26.0, and should land in Quarkus shortly.
