### ISSUE TITLE
Set auto-offset-reset: latest or earliest

### ISSUE THREAD

**Issue by ivangfr** [smallrye/smallrye-reactive-messaging#287]
Hi, is it possible to set the **auto-offset-reset** (`latest` or `earliest`) in `mp.messaging.incoming.topic`? Thanks!

**Comment by cescoffier** [comment]
Yes,
use something like:
```
mp.messaging.incoming.fights.auto.offset.reset=earliest
```

If your channel is named `topic`:
```
mp.messaging.incoming.topic.auto.offset.reset=earliest
```
