### ISSUE TITLE
Issue with isRequested() in EmitterImpl

### ISSUE THREAD

**Issue by aoudiamoncef** [smallrye/smallrye-reactive-messaging#291]
Hi @cescoffier,
I'm using Emitter in [this](https://github.com/Sparow199/bookmarkit/blob/step-6/bookmark-service/src/main/java/fr/loicmathieu/bookmarkit/BookmarkResource.java) Quarkus project and i noticed that the isRequested() returns always `true` even if there is no Artemis broker running. Is this the expected behaviour ? 
Afte some debuging stuff, i noticed that this behaviour is the result of buffer size > 0 at application startup, but i never sent any event yet.

```java
    @Override
    public boolean isRequested() {
        FlowableEmitter<Message<? extends T>> emitter = internal.get();
        return !isCancelled() && emitter.requested() > 0;
    }
```

[EmitterImpl](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/EmitterImpl.java)

**Comment by cescoffier** [comment]
An emitter stores the message in a queue that will then be processed when the Artemis broker is connected. 

To control this behavior and the overflow, use the `@OnOverflow` annotation.

**Comment by Sparow199** [comment]
In my case, there is no produced message  before explicitly calling `POST` endpoint. So, i don't know how the buffer is populated and with what ?

When the test end's, the event is send asynchronously, so i got completion error even if the test passes. Have you an idea about a clean way avoid this ?

**Comment by cescoffier** [comment]
If there are no messages, then the emitter's buffer is empty.  By default, the buffer can store 127 items.

I don't completely understand your issue about the test. Yes, the emitter is going to send the message asynchronously. What can of error do you see?

**Comment by Sparow199** [comment]
At startup, the `emitter.requested()` always returns `9223372036854775807` `(BufferAsyncEmitter{9223372036854775807})`

The issue with test: 
```java
Nov 03, 2019 8:13:09 PM io.smallrye.reactive.messaging.amqp.AmqpConnector lambda$null$15
ERROR: Unable to send the AMQP message
java.util.concurrent.CompletionException: io.vertx.core.VertxException: Disconnected
```
I would like to avoid this error in my tests. May be add some delay to my test in order to be sure that the message was sent.

**Comment by cescoffier** [comment]
Oh I see what you mean? Did you try with 0.27.0? Arc was turned off before Vert.x. It may be the root cause.

**Comment by Sparow199** [comment]
I upgraded to 0.26.1, I'll test with 0.27.0 and let you know.

**Comment by Sparow199** [comment]
I got exacly the same result with `0.27.0`

**Comment by cescoffier** [comment]
I will have a look, might be a bug in the AMQP client.
