### ISSUE TITLE
External Kafka bootstrap server setting ignored

### ISSUE THREAD

**Issue by kabir** [smallrye/smallrye-reactive-messaging#296]
Playing with the `kafka-quickstart` it works fine if I have Kafka running on localhost:9092.

I then modernised the `microprofile-config.properties` file to use MP properties, i.e.:
```
# Kafka Sink (topic = kafka)
mp.messaging.outgoing.data.connector=smallrye-kafka
mp.messaging.outgoing.data.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka Sink used by an Emitter
mp.messaging.outgoing.my-channel.connector=smallrye-kafka
mp.messaging.outgoing.my-channel.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.my-channel.topic=kafka


## Kafka Source (topic = kafka)
mp.messaging.incoming.kafka.connector=smallrye-kafka
mp.messaging.incoming.kafka.group.id=demo
mp.messaging.incoming.kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
```
So far, so good :)

I then try to connect to a Kafka instance running somewhere else, by specifying either
```
mp.messaging.connector.smallrye-kafka.bootstrap.servers=kklinux:9092
```
or
```
mp.messaging.connector.smallrye-kafka.kafka.bootstrap.servers=kklinux:9092
```
None of these work, and it still uses the default `localhost:9092`.
I then tried doing this for each connector instead (the `[.kafka]` denotes with and without '.kafka'), e.g.:
```
mp.messaging.outgoing.data[.kafka].bootstrap.servers=kklinux:9092
mp.messaging.outgoing.my-channel[.kafka].bootstrap.servers=kklinux:9092
mp.messaging.incoming.kafka[.kafka].bootstrap.servers=kklinux:9092
```
In all cases `localhost:9092` is used. Am I doing something wrong, or is there a bug somewhere?

**Comment by cescoffier** [comment]
Hello,

Can you try with:

mp.messaging.outgoing.my-channel.bootstrap.servers=kklinux:9092

Or:

kafka.bootstrap.servers=kklinux:9092

I would have expected  mp.messaging.connector.smallrye-kafka.bootstrap.servers=kklinux:9092 to work, so if one of the proposed approach works, can you open an issue because configuring the connector should also be supported.


Clement

**Comment by kabir** [comment]
`mp.messaging.outgoing.my-channel.bootstrap.servers=kklinux:9092` does not work and neither `does mp.messaging.outgoing.my-channel.kafka.bootstrap.servers` (I think both are mentioned in the SmallRye reactive messaging doc).

In the 'with .kafka' case I see `bootstrap.servers = [localhost:9092]`  in the Producer-/ConsumerConfig output, while for the first case I see it is set to `[kklinux:9092]` although it does not take effect - it is still trying to connect to localhost:9092.

The same for `mp.messaging.connector.smallrye-kafka.bootstrap.servers=kklinux:9092` vs `mp.messaging.connector.smallrye-kafka.kafka.bootstrap.servers=kklinux:9092` - i.e. the first one populates the `bootstrap.servers` with the proper host.

'kafka.bootstrap.servers=kklinux:9092` is the same as `mp.messaging.connector.smallrye-kafka.bootstrap.servers=kklinux:9092`.

I tried changing @ConfigProperty of KafkaConnector.servers to 'bootstrap.servers' (from 'kafka.bootstrap.servers') but all the above cases are the same.

I see that the KafkaConnector.servers value is always 'localhost:9092' when read from KafkaConnector.getSubscriberBuilder() and .getPublisherBuilder(). This is then  used in KafkaSink's constructor if the kafkaConfiguration does not contain a 'bootstrap.servers' entry. 
kafkaConfiguration does contain the `bootstrap.servers=kklinux:9092` vallue if I used the mp.messaging.connector.smallrye-kafka.bootstrap.servers setting, but still does not take effect.

**Comment by kabir** [comment]
Actually, perhaps this is a problem with the Kafka configuration on my 'kklinux' box. I've added some breakpoints where the connector connects to the server.

When I see `bootstrap.servers=[kklinux:9092]` in the Consumer-/ProducerConfigs, the address is correct: `kklinux/192.168.1.200:9092` in the following stacks which happen once for each consumer: 
```
"kafka-producer-network-thread | producer-1"@3,798 in group "main": RUNNING
connect:257, Selector {org.apache.kafka.common.network}
initiateConnect:945, NetworkClient {org.apache.kafka.clients}
access$600:68, NetworkClient {org.apache.kafka.clients}
maybeUpdate:1114, NetworkClient$DefaultMetadataUpdater {org.apache.kafka.clients}
maybeUpdate:1005, NetworkClient$DefaultMetadataUpdater {org.apache.kafka.clients}
poll:537, NetworkClient {org.apache.kafka.clients}
runOnce:335, Sender {org.apache.kafka.clients.producer.internals}
run:244, Sender {org.apache.kafka.clients.producer.internals}
run:745, Thread {java.lang}
```
and once for each consumer:
```
"vert.x-kafka-consumer-thread-0"@4,184 in group "main": RUNNING
connect:257, Selector {org.apache.kafka.common.network}
initiateConnect:945, NetworkClient {org.apache.kafka.clients}
ready:288, NetworkClient {org.apache.kafka.clients}
trySend:474, ConsumerNetworkClient {org.apache.kafka.clients.consumer.internals}
poll:252, ConsumerNetworkClient {org.apache.kafka.clients.consumer.internals}
poll:233, ConsumerNetworkClient {org.apache.kafka.clients.consumer.internals}
poll:212, ConsumerNetworkClient {org.apache.kafka.clients.consumer.internals}
ensureCoordinatorReady:249, AbstractCoordinator {org.apache.kafka.clients.consumer.internals}
poll:326, ConsumerCoordinator {org.apache.kafka.clients.consumer.internals}
updateAssignmentMetadataIfNeeded:1251, KafkaConsumer {org.apache.kafka.clients.consumer}
poll:1220, KafkaConsumer {org.apache.kafka.clients.consumer}
poll:1159, KafkaConsumer {org.apache.kafka.clients.consumer}
lambda$pollRecords$6:146, KafkaReadStreamImpl {io.vertx.kafka.client.consumer.impl}
run:-1, 253622672 {io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl$$Lambda$220}
call:511, Executors$RunnableAdapter {java.util.concurrent}
run$$$capture:266, FutureTask {java.util.concurrent}
run:-1, FutureTask {java.util.concurrent}
runWorker:1142, ThreadPoolExecutor {java.util.concurrent}
run:617, ThreadPoolExecutor$Worker {java.util.concurrent}
run:745, Thread {java.lang}
```
The [documentation](https://docs.confluent.io/current/connect/references/allconfigs.html) mentions that bootstrap.servers is the list of servers used to make the initial connect to the cluster. 
I presume these initial calls return the actual list list of servers in the Kafka cluster, so that later we use the list from that initial call. So I believe that I need to change the advertised_listeners or something on the remote host to get this to work.

So we can probably close this, as it looks like it is working how it should from the SmallRye side.

**Comment by kabir** [comment]
Changing docker-compose.yaml on kklinux to:
```
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
+      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.200:9092
```
it all works fine now. I get the messages output running the example on my client machine. Sorry about the noise :)
