### ISSUE TITLE
Separate API artifact

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-reactive-messaging#298]
To be clear about what's API above and beyond MP and what's actual implementation, I was wondering if it was beneficial to split out things like https://github.com/smallrye/smallrye-reactive-messaging/tree/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/annotations into a separate API artifact that the main codebase then depends on?

It also then signals to the community the pieces we are thinking of proposing to an MP specification in the future.

Thoughts?

**Comment by kenfinnigan** [comment]
@cescoffier good? bad?

**Comment by cescoffier** [comment]
+1

**Comment by kenfinnigan** [comment]
Done with https://github.com/smallrye/smallrye-reactive-messaging/pull/316
