### ISSUE TITLE
Add support for dynamic (per message) address to AMQP connector

### ISSUE THREAD

**Issue by misl** [smallrye/smallrye-reactive-messaging#301]
Currently the address on which to publish messages is taken from configuration. Even though `AmqpMessage` supports `getAddress()` it is not possible to set it without creating a delegate. But even then the message address will not be used since the message will be published only on configured addresses.

Like this is will be very hard to create message routers, where routing is based on message content.

Is it possible to supported dynamic address/topic like supported by Kafka and MQTT connectors?

**Comment by cescoffier** [comment]
It should be possible but would require changing the connector.

**Comment by cescoffier** [comment]
Going to be fixed with `headers`. Got tests passing.

**Comment by cescoffier** [comment]
Has been fixed thanks to metadata passing.
