### ISSUE TITLE
Incoming HTTP requests

### ISSUE THREAD

**Issue by matzew** [smallrye/smallrye-reactive-messaging#31]
While the APIs are currently nicely supporting _outbound_ http messages, It would be nice to be able to wire a a reactive messaging application to a "web server" for receiving http messages.

```
  @Incoming("from-http")
  @Outgoing("to-kafka")
  public CloudEventMessage<String> process(CloudEventMessage<String> message) {
    return CloudEventMessageBuilder.from(message)
      .data("Hello " + message.getPayload()).build();
  }
```

So here (with proper config), I'd receive HTTP inbound traffic, run some "transformations" and send it somewhere (e.g. Apache Kafka)

**Comment by cescoffier** [comment]
Provided in #master.
