### ISSUE TITLE
Consider setting the scope to ApplicationScoped by default.

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#33]

**Comment by kenfinnigan** [comment]
You mean not require the annotation on the class?

**Comment by cescoffier** [comment]
Yes.

**Comment by cescoffier** [comment]
actually wondering "singleton" vs. applicationscoped"

**Comment by kenfinnigan** [comment]
Is there a difference? @mkouba ?

It's been a while since I've been deep in CDI

**Comment by manovotn** [comment]
@kenfinnigan application scoped has client proxy whereas singleton does not.
It's nicely summer up in [Weld doc](http://docs.jboss.org/weld/reference/latest/en-US/html_single/#_the_singleton_pseudo_scope).

**Comment by kenfinnigan** [comment]
Thanks @manovotn, I was trying to find the proxy information in the Weld docs earlier but couldn't find it

**Comment by cescoffier** [comment]
Closing, out of date.
