### ISSUE TITLE
More SSL configuration options for AMQP

### ISSUE THREAD

**Issue by famartinrh** [smallrye/smallrye-reactive-messaging#349]
AmqpConnector currently adds options to configure the amqp client via config properties and for ssl configuration there are still a few missing settings. 

The question is, would be considered to add the posibility to inject an optional `AmqpClientOptions` ?, this way there won't be a need to add more and more config properties and the AmqpConnector could be configured producing by CDI an AmqpClientOptions with the appropiate settings needed. I understand there are missing details like how to deal with the two config ways, allow both and merge properties, only allow one,... this is something could be discussed if this proposal is accepted.

**Comment by cescoffier** [comment]
I like this idea! 

Should we inject a AmqpClientOptions or directly an AmqpClient (already configured) ? 

We also need to check how we will handle multiple channels using different clients.

**Comment by famartinrh** [comment]
nice!

I think AmqpClientOptions is the thing, it will ease the moving to build time in quarkus, and the AmqpClient used here is the axle one and people maybe won't use it and we will have to convert it.... I think AmqpClientOptions is just fine.

I'll have to think about dealing with multiple channels

**Comment by famartinrh** [comment]
We have an example in JmsConnector!!

We can add a config property named `client-options-name` or `client-name`, if we go with the AmqpClient approach, ie:
```
mp.messaging.incoming.foo.client-options-name=myfooclientoptions
```
and then we will have to produce a named instance like 
```
@Produces @Named("myfooclientoptions")
AmqpClientOptions produceOptions() {...
```
we could create our own qualifier, but named is enough.

Then I would implement that if there isn't any `client-options-name` configured but there is an instance of AmqpClientOptions then the amqp client would be created from that options instance.

And finally, to keep backwards compatibility, I would implement it to behave as always if there isn't any instance of AmqpClientOptions

**Comment by cescoffier** [comment]
I would use `@Named` (even if it's a bit of an abuse of the annotation). I already use it in the JMS connector, let's continue with it.

However, you should, as in the JMS connector I believe, use `Instance<AmqpClientOptions`, and manage the cases:
1. no match
2. multiple matches

**Comment by cescoffier** [comment]
@famartinrh, should we close this one as #352 has been merged?
