### ISSUE TITLE
Configuration can be repetitive

### ISSUE THREAD

**Issue by ia3andy** [smallrye/smallrye-reactive-messaging#360]
Hey guys,

Thanks for your great work making messaging easy!! 

 I am successfully using `smallrye-reactive-messaging` on Quarkus with Kafka. I have a few feedbacks about configuration.

Setting connectors and all serializers on every channels can become repetitive and lead to errors like:
- using incoming instead of outgoing
- using Serializer instead of Deserializer

It would be great if it was possible to set the connector for a  list of channels.
It would be great if it was possible to define a type a with `Serializer` and a `Deserializer` with some sensible default. Then, we would just have to define a type on a specific channel. ex:
```
// Those could be defaulted
mp.messaging.type."java.lang.Integer".serializer=org.apache.kafka.common.serialization.IntegerSerializer
mp.messaging.type."java.lang.Integer".deserializer=org.apache.kafka.common.serialization.IntegerDeserializer

// Just have to do this
mp.messaging.outgoing.songs.value.type=java.lang.Integer
```

Maybe we could even guess it directly from the annotation in the code? ex:
```
@Incoming("from-kafka")
  public void consume(KafkaMessage<String, JsonObject> message) {
    JsonObject payload = message.getPayload();
    String key = message.getKey();
    MessageHeaders headers = message.getHeaders();
    Integer partition = message.getPartition();
    Long timestamp = message.getTimestamp();
}
```

We know it's going to be a `JsonObject`, if we have a type defined, not configuration is needed..

Do you get what I mean?

CC @cescoffier

**Comment by cescoffier** [comment]
About serializer and deserializer - I've started some work (in Quarkus) to automatically inject the property based on the method signature. It's not done yet and because they are around 30 different signatures types, it can be complicated. I plan to finish this for Quarkus 1.2 or 1.3.

Note that for keys, the default is String.

**Comment by cescoffier** [comment]
Forgot to mention that this would only work in Quarkus as there is no reliable way to extract generic parameters at runtime.

**Comment by cescoffier** [comment]
In Quarkus, we are detecting most of the configuration.
