### ISSUE TITLE
How to handle errors outside of @Incoming and @Outgoing methods?

### ISSUE THREAD

**Issue by zeljkot** [smallrye/smallrye-reactive-messaging#372]
**Set-up:**

Kafka custom deserializer
Consumer method annotated with @Incoming
Messages in Kafka topic that cannot be deserialized (e.g. due to error or schema change).

**Expected behavior**

A deserializing exception should be at least logged.
An exception should trigger onErrorResume.

**Actual behavior**

An exception is silently ignored; further message processing stops.

**To reproduce**

1. Create an outgoing channel that writes non-string byte[]. 

       @Incoming("asc-processing-status-v1-in")
       Subscriber<KafkaMessage<String, ProcessingStatus>> gotUpdate() {

            return ReactiveStreams.<KafkaMessage<String, ProcessingStatus>>builder()
                    .onErrorResume(throwable -> {
                        log.warn("Cannot get value" + throwable);
                        return KafkaMessage.of(
                                "unknown",
                                new ProcessingStatus("unknown", Status.FAILURE, "unknown", throwable.getMessage())
                        );
                    })
                    .filter(message -> !message.getKey().equals("unknown"))
                    .forEach(message -> {
                        System.out.println("ShiftSocketApi.gotUpdate");
                        send(message.getPayload());
                    })
                    .build();
        }

1. Create an incoming channel that tries to read String.
1. Send a message.

**Environment**

* Quarkus 1.1.1.Final with quarkus-smallrye-reactive-messaging-kafka plugin
* java version "1.8.0_231"

**Comment by cescoffier** [comment]
I believe the issue is in the Kafka connector. If it happens in the pipelines the error is logged.
