### ISSUE TITLE
If incoming and outgoing have the same name, messages sent only to in-memory topic

### ISSUE THREAD

**Issue by zeljkot** [smallrye/smallrye-reactive-messaging#373]
**Describe the bug**

Incoming and outgoing are configured for Kafka and have the same name. Reactive Streams will automatically create in-memory topic. It will complain that consumer has two sources without `@Merge`. If `@Merge` is added, `@Outgoing` will send messages to in-memory topic, but not to Kafka.

Workaround is to give different names to incoming and outgoing channel.

**Expected behavior**

Messages should go to both channels, or in-memory should be disabled.

**Actual behavior**

Reactive Streams complains that consumer has two sources without `@Merge`. If `@Merge` is added, `@Outgoing` will send messages to in-memory topic, but not to Kafka.

**To reproduce**

1. Set-up incoing and outgoing channel with the same name ("my-topic") for the Kafka connector

        mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:10241

        mp.messaging.incoming.my-topic.connector=smallrye-kafka
        mp.messaging.incoming.my-topic.topic=my-topic-1
        mp.messaging.incoming.my-topic.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

        mp.messaging.outgoing.my-topic.connector=smallrye-kafka
        mp.messaging.incoming.my-topic.topic=my-topic-1
        mp.messaging.outgoing.my-topic.value.serializer=org.apache.kafka.common.serialization.StringSerializer
2. Create @Outgoing and @Incoming methods.
3. Start the application.

**Environment**

* Quarkus 1.1.1.Final with quarkus-smallrye-reactive-messaging-kafka plugin
* java version "1.8.0_231"

**Comment by cescoffier** [comment]
Doesn't the spec say that the channel name must be unique?
Anyway, it should handle this case in a more _meaningful_ manner.

**Comment by zeljkot** [comment]
I tried to search for word "uniq" in both Smallrye and "MicroProfile Reactive Messaging
Specification" but I could not find it. I will take a deeper look.

**Comment by zeljkot** [comment]
Found it: 
> Having the same channel appear in the @Outgoing and @Incoming annotations of a processor is not supported and will result in an error during deployment.

Smallrye is not compliant with the specification, but rather implements its own behavior:
> 2.5. Binding matching @Outgoing to @Incoming
> SmallRye Reactive Messaging automatically binds matching @Outgoing to @Incoming to form a chain.

So users should take special care to either use in-memory or external messaging.

**Comment by cescoffier** [comment]
@zeljkot After checking, you are absolutely right! I'm on it.
