### ISSUE TITLE
Emitter for anonymous AMQP sender

### ISSUE THREAD

**Issue by andrejpetras** [smallrye/smallrye-reactive-messaging#379]
Hi,

would it be possible to create the Emitter for the anonymous AMQP Sender? 

My motivation is to create dynamic router which takes all incoming messages and send them to the new address based on the message attributes.

I checked the source code and the AMQ sender is always created for a address.
I believe this will require at least a change in the axle client and in smallrye to have method to create anonymous AMQP sender.

Or do we have another approach for creating the dynamic router?

**Comment by cescoffier** [comment]
So, it will be possible soon.
In the "headers" branch, I switched to an anonymous sender to the message can indicate to which address they need to be sent.
(See https://github.com/smallrye/smallrye-reactive-messaging/blob/features/headers/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java#L275)

Would that work for you?

**Comment by andrejpetras** [comment]
@cescoffier thanks for quick response. I will make a tests and ping you back.

**Comment by andrejpetras** [comment]
@cescoffier cool it is working. When do you plan to release this?

Only one point but I am not sure if this is relevant. It could be that it is different topic:

- When I create the address (queue) in the Artemis manually (or configuration) the messages are sent (1) without an error.

- If I send message to address which does not exist in broker there is no error in quarkus app and artemis creates only the address but not queue (2). 

![image](https://user-images.githubusercontent.com/828045/72619187-10734700-393d-11ea-88e6-3cdfce86d068.png)

**Comment by cescoffier** [comment]
We are still discussing some details about headers (which has been renamed into metadata). Hopefully, it's going to be merged and released in the next 2 weeks.

About the Artemis behavior. Honestly, I don't know. @kenfinnigan anyone, we can ask?

**Comment by kenfinnigan** [comment]
Maybe @ssorj ?

**Comment by cescoffier** [comment]
Fixed in master
