### ISSUE TITLE
Kafka messages silently ignored in case of incompatible key deserializer

### ISSUE THREAD

**Issue by gunnarmorling** [smallrye/smallrye-reactive-messaging#387]
Actual:
I set up an incoming channel for a Kafka topic whose keys are JSON-formatted Strings. Accidentally, I configured the channel to use `org.apache.kafka.common.serialization.IntegerDeserializer`. This caused the messages from the topic to be silently ignored, without any message in the log whatsoever.

Expected:
A meaningful exception indicating the deserialization issue should be raised.

**Comment by cescoffier** [comment]
Already fixed in https://github.com/smallrye/smallrye-reactive-messaging/pull/378.

**Comment by gunnarmorling** [comment]
Ah, very good. When will this be available via Quarkus?

>

**Comment by cescoffier** [comment]
ASAP :-)

Targetting 1.0.4 right now. Maybe 1.0.3 if possible.

**Comment by cescoffier** [comment]
Closing this one as it's already fixed.
