### ISSUE TITLE
Consider to rename KafkaMessage to KafkaRecord

### ISSUE THREAD

**Issue by gunnarmorling** [smallrye/smallrye-reactive-messaging#388]
"Record" is the official term used in upstream Kafka documentation, so people familiar with that may feel irritated when seeing "KafkaMessage" in SmallRye Reactive Messaging.

**Comment by cescoffier** [comment]
KafkaMEssage is probably going to disappear soon with the support of metadata propagation. But I agree with the change, having an IncomingKafkaRecord and OutgoingKafkaRecord make sense.

**Comment by cescoffier** [comment]
Fixed in master.
