### ISSUE TITLE
Vert.x Event Bus connector name incorrect

### ISSUE THREAD

**Issue by boosey** [smallrye/smallrye-reactive-messaging#390]
The Smallrye documentation states that the connector name is smallrye-vertx-eventbus, but the implementation specifies smallrye.vertx.eventbus.

https://smallrye.io/smallrye-reactive-messaging/#_dependency_7

https://github.com/smallrye/smallrye-reactive-messaging/blob/26169cf1ff4fad955060758c679cc1a6e5327926/smallrye-reactive-messaging-vertx-eventbus/src/main/java/io/smallrye/reactive/messaging/eventbus/VertxEventBusConnector.java

**Comment by cescoffier** [comment]
The code is wrong. It should be `smallrye-vertx-eventbus`. Fancy a PR?

**Comment by boosey** [comment]
Never done it before. I'm an old ex-professional developer before all this Git stuff came out. :-) But I will give it a shot.

**Comment by boosey** [comment]
Done and accepted.
