### ISSUE TITLE
Reactive Messaging Channel Emitter Injection Fails

### ISSUE THREAD

**Issue by boosey** [smallrye/smallrye-reactive-messaging#392]
Created scaffold with quarkus.io tool trying both Maven and Gradle build versions. As far as I can tell I am following the documentation faithfully.

Problem: @Inject @Channel("ownercreated") Emitter<Owner> ownerCreatedChannel fails. No value is ever injected. Using Kafka as transport with correctly configured application.properties.

I have attached a minimal reproduction for your information.
[pimp-my-parking.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/4110993/pimp-my-parking.zip)

**Comment by boosey** [comment]
I may have uploaded an incorrect version. Here is the correct one.
[pimp-my-parking.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/4111202/pimp-my-parking.zip)

**Comment by cescoffier** [comment]
Can you try with adding `@ApplicationScoped` on the `Owner` class? I don't believe it injects the emitter.
