### ISSUE TITLE
How can i handle exceptions from emitter?

### ISSUE THREAD

**Issue by tcsantosdev** [smallrye/smallrye-reactive-messaging#400]
How can i handle exception on streaming processing with quarkus + kafka + smallrye?

My code is very similar to the imperative producer example on quarkus guide (https://quarkus.io/guides/kafka#imperative-usage)

```java
import io.smallrye.reactive.messaging.annotations.Channel;
import io.smallrye.reactive.messaging.annotations.Emitter;

import javax.inject.Inject;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.MediaType;

@Path("/prices")
public class PriceResource {

    @Inject @Channel("price-create") Emitter<Double> priceEmitter;

    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public void addPrice(Double price) {
        priceEmitter.send(price);
    }
}
```

I wanted something similar the vanilla Kafka library, that gives the option to handle the callback of each record requested to send.

```java
ProducerRecord<String, String> record = new ProducerRecord<>("topic-name", key, value);

producer.send(record, new Callback() {
    @Override
    public void onCompletion(RecordMetadata metadata, Exception exception) {
        logger.info(record.toString());

        if (exception != null) {
            logger.error("Producer exception", exception);
        }
    }
});
```

Tks

**Comment by cescoffier** [comment]
The master branch contains a new Emitter that provides a CompletionStage as result.

**Comment by tcsantosdev** [comment]
> The master branch contains a new Emitter that provides a CompletionStage as result.
> […](#)
> On 31 Jan 2020 at 20:47 +0100, tcsantos ***@***.***>, wrote: How can i handle exception on streaming processing with quarkus + kafka + smallrye? My code is very similar to the imperative producer example on quarkus guide (https://quarkus.io/guides/kafka#imperative-usage) import io.smallrye.reactive.messaging.annotations.Channel; import io.smallrye.reactive.messaging.annotations.Emitter; import javax.inject.Inject; import javax.ws.rs.POST; import javax.ws.rs.Path; import javax.ws.rs.Consumes; import javax.ws.rs.core.MediaType; @path("/prices") public class PriceResource { @Inject @channel("price-create") Emitter<Double> priceEmitter; @post @Consumes(MediaType.TEXT_PLAIN) public void addPrice(Double price) { priceEmitter.send(price); } } I wanted something similar the vanilla Kafka library, that gives the option to handle the callback of each record requested to send. ProducerRecord<String, String> record = new ProducerRecord<>("topic-name", key, value); producer.send(record, new Callback() { @override public void onCompletion(RecordMetadata metadata, Exception exception) { logger.info(record.toString()); if (exception != null) { logger.error("Producer exception", exception); } } }); Tks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Tks, that perfect!!

Im using the latest Quarkus realease, but sadly it doesn't  contains this new emitter.

**Comment by cescoffier** [comment]
Yes, I have been delayed by the ‘huge’ metadata propagation work. There is still a few things to include in this release, but the next Quarkus version should have an updated reactive messaging version.

**Comment by tcsantosdev** [comment]
Thanks again, I imagine the hard work necessary to implement these new features.

I'm looking forward to new releases from Quarkus / Smallrye!!!
