### ISSUE TITLE
Assets not getting published to maven central

### ISSUE THREAD

**Issue by mbroz2** [smallrye/smallrye-reactive-messaging#411]
Only the .pom and its checksums are getting published on maven central repo.  For example, in the latest version
 https://repo1.maven.org/maven2/io/smallrye/reactive/smallrye-reactive-messaging/1.1.0/
the jar, source, and javadocs are missing.

**Comment by cescoffier** [comment]
Here it is: https://repo1.maven.org/maven2/io/smallrye/reactive/smallrye-reactive-messaging-provider/1.1.0/

You are looking for the `-provider` artifacts.

**Comment by mbroz2** [comment]
Thanks; in case it wasn't done on purpose, just an fyi that reactive messaging seems to follow a different URL scheme from all the other smallrye components regarding where their artifacts are published as all other components have them alongside the pom. For example:
https://repo1.maven.org/maven2/io/smallrye/reactive/smallrye-reactive-streams-operators/1.0.10/
https://repo1.maven.org/maven2/io/smallrye/smallrye-context-propagation/1.0.11/
https://repo1.maven.org/maven2/io/smallrye/smallrye-opentracing/1.3.2/
