### ISSUE TITLE
Split-package errors with embedded MicroProfile API

### ISSUE THREAD

**Issue by acoburn** [smallrye/smallrye-reactive-messaging#420]
With the 1.1.0 release of `smallrye-reactive-messaging`, the MicroProfile API is embedded in the published smallrye JAR. This makes it considerably harder to use this in a Java11 module context if the `microprofile-reactive-messaging-api` is also on the module path (since both export the same namespace). This may also present challenges for OSGi. The experimental interfaces are interesting to use, but would it be possible to move those to an `io.smallrye.reactive.messaging.*` namespace rather than exporting the `org.eclipse.microprofile.reactive.messaging` package in this JAR?

**Comment by kenfinnigan** [comment]
The experimental interfaces are in `io.smallrye.reactive` package.

The problem is that it also requires modifying classes from the `org.eclipse.microprofile.reactive.messaging` namespace

**Comment by acoburn** [comment]
So if I am not mistaken, the best approach for Java11 support will be to wait for the next release of microprofile-reactive-messaging-api along with the corresponding smallrye-reactive-messaging artifact, correct?

**Comment by cescoffier** [comment]
As @kenfinnigan said, the features we have added requires modifying the `org.eclipse.microprofile.reactive.messaging`. Unfortunately, there are no other solutions. I would recommend to just use the API module and not depend on the original reactive messaging artifact.

**Comment by kenfinnigan** [comment]
@acoburn We don't know how long it might be before the API changes we make in SmallRye are proposed back to the specification. We want to ensure we get changes right before proposing them.

The best solution right now is to not include the MP Reactive Messaging API as a dependency.

**Comment by acoburn** [comment]
@kenfinnigan thanks for the background and explanation. I should be able to work around this in my own code, so I'll close this issue.
