### ISSUE TITLE
Switch to Mutiny

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#437]
This issue is an _epic_ that covers the introduction of Mutiny in Reactive Messaging Provider as well as in some connectors.

* [x] - Switch test to use the Mutiny based implementation of Reactive Streams Operators
* [x] - Update documentation to use the Mutiny based implementation of Reactive Streams Operators
* [x] - Allow injecting `@Channel("xxx") Multi<T>` and `@Channel("xxx") Multi<Message<T>>`
* [X] - Allow methods annotated with `@Outgoing` to return a `Multi`
* [X] - Allow methods annotated with `@Incoming` to consume a `Multi`
* [x] - Allows methods annotate with `@Outgoing` to return a `Uni<T>` or `Uni<Message<T>>` (async production)
* [x] - Allows methods annotate with `@Incoming` to return a `Uni<T>` or `Uni<Message<T>>` (subscriber case)
* [x] - Migrate the Event bus connector
* [x] - Migrate the AMQP connector
* [x] - Migrate the MQTT connector
* [x] - Migrate the MQTT server connector
* [x] - Migrate the Kafka connector
* [x] - Replace Axle clients by Mutiny clients in connectors

**Comment by cescoffier** [comment]
CC @kenfinnigan

**Comment by kenfinnigan** [comment]
This can be closed now right?

**Comment by cescoffier** [comment]
yes, thanks!
