### ISSUE TITLE
ProcessorMediator missing POST_PROCESSING acknowledgement

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-reactive-messaging#480]
https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/ProcessorMediator.java#L236 doesn't have the necessary POST_PROCESSING acknowledgment handling present.

**Comment by cescoffier** [comment]
My bad the spec is clear about that. However, the doc must be updated to reflect this limitation.

**Comment by cescoffier** [comment]
Documentation updated.
