### ISSUE TITLE
Something is messed up with the Mutiny API

### ISSUE THREAD

**Issue by vankofalcon** [smallrye/smallrye-reactive-messaging#489]
I have a kafka consumer that works just fine when I use the CompletionStage API like this:

```
@Incoming("topic")
public CompletionStage<Void> consume1(String base) {
        System.out.println(String.format("received event %d", base.hashCode()));
        Uni<Void> uni = Uni.createFrom().item(base)
                .map(event -> {
                    System.out.println("in map");
                    return null;
                });
        return uni.subscribeAsCompletionStage();
    }
```

I can see all the logs in the console: 

```
received event -829123098
in map
received event -1075588554
in map
received event -407164692
in map
received event -249963325

.....

```
But when I've migrated this to the Mutiny API:

```
@Incoming("topic")
public Uni<Void> consume2(String base) {
        System.out.println(String.format("received event %d", base.hashCode()));
        return Uni.createFrom().item(base)
                .map(event -> {
                    System.out.println("in map");
                    return null;
                });
    }

```
I see only one of the logs:

```
received event -159893947
received event 1551771067
received event -2102496827
....
```

I can see that the messages are getting ack because they keep coming but these logs are not printed in the output. Can someone please explain what is happening here?

**Comment by cescoffier** [comment]
It might be a bug and someone (me :-)) forgot to subscribe to the returned Uni.


How did you use it? In Quarkus? In that case it makes sense as Mutiny support came with SmallRye Reactive Messaging 2.0, which is not yet in Quarkus (work in progress). That would explain the behavior as it would simply ignore the returned object.

Clement

**Comment by vankofalcon** [comment]
@cescoffier Yes, that makes sense. I'm on Quarkus 1.3.2.Final and I was so excited that you have updated your documentation https://smallrye.io/smallrye-reactive-messaging. It's a little misleading because these are the official docs for the messaging and they don't match with the quarkus messaging guide https://quarkus.io/guides/kafka. You can find the link at the end of the guide:

> If you want to go further check the documentation of SmallRye Reactive Messaging, the implementation used in Quarkus.

**Comment by cescoffier** [comment]
We hope to be able to integrate just before Quarkus 1.4 (depending how much delay get this release). In any case, it will be in Quarkus 1.5.
