### ISSUE TITLE
Extend AMQP metadata and outbound AMQP message to be exhaustive

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#492]
A few sections are missing:

* header
* trailer
* application properties may not be totally correct (using JsonObject to represent them)
* sequence metadata...

**Comment by obbyK** [comment]
Has there been any update? How would one go about adding properties to the outgoing Message. I'm trying to set the property `_AMQ_SCHED_DELIVERY`

**Comment by cescoffier** [comment]
It's on the roadmap but not yet planned. In which AMQP section are the properties you want to set?

**Comment by obbyK** [comment]
It's an AMQP `message annotation` with name `x-opt-delivery-time`.

It's documented [here](https://activemq.apache.org/components/artemis/documentation/2.3.0/protocols-interoperability.html) under AMQP scheduling message delivery

**Comment by cescoffier** [comment]
Thanks! I will prioritize the addition of the annotation support.

**Comment by cescoffier** [comment]
I started working on it.
