### ISSUE TITLE
Exception thrown from connector during startup discarded by provider with cause thrown instead

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-reactive-messaging#515]
If an exception occurs when a connector creates its subscriber or producer, if that exception has a cause, the exception itself is discarded and the cause is reported as a deployment error.

This happens here: https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ReactiveMessagingExtension.java#L135

This was unhelpful in my connector, because the exception that was discarded contained the information about which channel the connector failed for.

**Comment by Azquelt** [comment]
Not sure what the intention of this bit of code is, but it _might_ just be left over from an older revision where initialization was done asynchronously and any exception thrown would have been wrapped in an `ExecutionException`.

https://github.com/smallrye/smallrye-reactive-messaging/blob/688a381659dfa0589f1b4c8958249938a117f953/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ReactiveMessagingExtension.java#L83

**Comment by cescoffier** [comment]
To be honest, I have no idea why there is this conditional. Shouldn't we always report with the parent exception?

**Comment by Azquelt** [comment]
Yes, I think here we should now always be calling `addDeploymentProblem(e)` rather than `addDeploymnetProblem(e.getCause())`
