### ISSUE TITLE
Having trouble running examples

### ISSUE THREAD

**Issue by Shogan** [smallrye/smallrye-reactive-messaging#519]
I've been experimenting with the examples and have trouble running most. I'm not sure if it's a local java issue on my machine, or if it is related to the structure of git repository.

1. Executing `mvn package exec:java` in the example directories generally doesn't work. There is always an issue with the artifacts from io.smallrye.reactive. Changing the version number from `2.1.0-SNAPSHOT` to something like `2.0.1` fixes this one.

My IDE shows errors like the below for the dependency (and this is not just the Kafka example, but others too).

> Missing artifact io.smallrye.reactive:smallrye-reactive-messaging-kafka:jar:2.1.0-SNAPSHOT

2. Executing `mvn package exec:java` after fixing versions on dependencies then tends to fail with exceptions... E.g.

> Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.reactive.streams.operators.SubscriberBuilder

the result of the `mvn package exec:java` command is:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project reactive-messaging-quickstart: An exception occured while executing the Java class. org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder: org.eclipse.microprofile.reactive.streams.operators.PublisherBuilder -> [Help 1]

I've tried the above on the basic examples/quickstart sample with the same results. I've also tried doing `mvn clean install` in the main cloned repository with the root pom.xml file. This builds everything and runs tests, but there are ocassional failures and exceptions during that process.

Am I running the samples incorrectly?

My environment details:

Bare metal

Maven:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

Java:
```
Matching Java Virtual Machines (1):
    14, x86_64:	"Java SE 14"	/Library/Java/JavaVirtualMachines/jdk-14.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk-14.jdk/Contents/Home
```

**Comment by kenfinnigan** [comment]
Have you run `mvn clean install` from the project root before running the examples?

**Comment by Shogan** [comment]
> Have you run `mvn clean install` from the project root before running the examples?

Hi @kenfinnigan,

Yes that was the first thing that I did. There are some tests that fail on that run though. From what I can tell the parent's parent directory of the samples refers to this, so I assume a clean build is required for the samples to work correctly?

**Comment by kenfinnigan** [comment]
Probably, maybe try with `-DskipTests`

**Comment by Shogan** [comment]
That helped somewhat thanks @kenfinnigan. (It puts me back to the same result as having manually specified version 2.0.1 which pulled it down instead of referencing the 2.1.0-SNAPSHOT local version).

So the same resulting error persists:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project reactive-messaging-quickstart: An exception occured while executing the Java class. org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder: org.eclipse.microprofile.reactive.streams.operators.PublisherBuilder -> [Help 1]
```

I'm very new to Java/Maven but from what I can tell this is something to do with the way the Main class is being launched with maven that is the issue.

To clarify, I am in the **smallrye-reactive-messaging/examples/quickstart** directory and am executing: `mvn exec:java` from there.

I've also tried specifying the fully qualified name of acme.Main too. i.e. `mvn exec:java -Dexec.mainClass=acme.Main`.

Am I missing something obvious here?


Is this correct?

**Comment by cescoffier** [comment]
It looks like you don't have MicroPRofile Reactive Streams Operators in your classpath, try adding:

```
<dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>mutiny-reactive-streams-operators</artifactId>
      <version>0.4.4</version>
</dependency>
```

In the `pom.xml` file.

Also for the quickstart, check https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/getting-started.html. The examples from the source repository are a bit outdated.

**Comment by phillip-kruger** [comment]
If you add `<classpathScope>compile</classpathScope>` to the `exec-maven-plugin` plugin configuration this works. 

I'll update the document and the examples. Seems like `exec-maven-plugin` changed the default from compile to runtime in the recent version.
