### ISSUE TITLE
About Vert.x

### ISSUE THREAD

**Issue by anhldbk** [smallrye/smallrye-reactive-messaging#528]
Hi guys,

Currently in the section [Built with](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/README.md#built-with), we have:

```
    Apache Vert.x
    RX Java 2
    SmallRye Reactive Stream Operators (any implementation would work)
    Weld (any implementation would work)
```

IMHO, Vert.x is not an Apache project. Actually it's an Eclipse one.

Should I make a PR addressing this issue?

**Comment by cescoffier** [comment]
Definitely a mistake!

PRs are always welcome. Also, RX Java 2 is not the base anymore it's SmallRye Mutiny and instead of `SmallRye Reactive Stream Operators (any implementation would work)` we now use an implementation based on Mutiny (but any implementation would work).

**Comment by anhldbk** [comment]
@cescoffier Thanks for letting me know. Here's the PR: https://github.com/smallrye/smallrye-reactive-messaging/pull/531
