### ISSUE TITLE
The Javadoc for @Blocking#ordered is a bit missleading if you are not familiar with Vert.x

### ISSUE THREAD

**Issue by hutchig** [smallrye/smallrye-reactive-messaging#565]
I was looking into how @Blocking methods are run in Vert.x.

If you are not familiar with Vert.x, the current javadoc for io.smallrye.reactive.messaging.annotations.Blocking#ordered [here](https://github.com/smallrye/smallrye-reactive-messaging/blob/5cf72f6715786790fce6159235a9c8eb61b44499/api/src/main/java/io/smallrye/reactive/messaging/annotations/Blocking.java#L35)
leaves an important issue hanging and might be missleading.

The problem is that one may think the ordering refers to one of the enqueing
or subsequent commencement of the work or the emission of the
results. The problem is the text that is used to differentiate the two cases: 
   
"the results are emitted in the same order as the input"
or
"results are emitted as soon as the blocking computation has terminated"

but actually, for both options, 
results are always emitted as soon as the blocking computation finishes
(i.e there is no buffering/sorting of results in either case), the SmallRye code uses '.subscribeAsCompletionStage().thenApply.

As I am sure you know already, what is going on is this [here](https://github.com/vietj/advanced-vertx-guide/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc#worker-context) for ordered or 
[this](https://github.com/vietj/advanced-vertx-guide/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc#multi-threaded-worker-context) for not ordered.

The main difference is that ordered will execute the Blocking tasks sequencially
(thus maintaining the relative order of events in to events out) with at most one task active at a time and no need to use locking between the tasks **of one Vert.x context**. Whereas ordered=false will neither maintain the order of emissions matching the order of events
**nor the synchronized{}/1-at-a-time** semantics. 

The one-at-a-time meaning (not needing to synchronize) is really useful and should be in the javadoc, but it is possible in Vert.x to have more than one Context sharing a pool and
so the scope of the one-at-a-time effect is not clear from the outside (and to be honest
is a bit opaque even reading the code)

For SmallRye reactive messaging, for a ordered=true, does the only-one-of-these-run-at-a-time apply to
1 - just that method in that stream
2 - all Blocking methods in the stream
3 - Blocking methods downstream of the nearest upstream ordered=false
x something else?

I am happy to do a PR with some text but would love an OK first as per
CONTRIBUTING.md  and clarification of the scope
of the synchronized{ ... } one-at-a-timeness so I can include it.

Actually I am happy to do a PR with some strawman text where you can
tighten the wording on the synchronized{ } effect, but it's best to have an
issue discussion first regardless.

**Comment by kenfinnigan** [comment]
@hutchig, PR with proposed text changes would be appreciated.

As for your question. `@Blocking` and it's semantics, such as ordering, apply to the specific method on which `@Blocking` is present. It doesn't impact subsequent methods in the stream that also might have `@Blocking` present on them.

Does that answer your question?

**Comment by hutchig** [comment]
I think that does answer my question Ken, but I will check with an assertion:
If I have multiple methods annotated with @Blocking(ordered=true) then there will
be at most one invokation of each one of these methods being called by SRM at any 
one time in the process, but there may be multiple distinct @Blocking(ordered=true) 
methods being invoked at any one time, even in the Outgoing/Incoming ends of a 
single channel.

**Comment by kenfinnigan** [comment]
Correct

**Comment by hutchig** [comment]
Ok, thanks.  If the ability to get as much parallelism changes unexpectedly in the future then maybe this link might be useful: https://github.com/eclipse-vertx/vert.x/pull/3431 https://groups.google.com/d/msg/vertx-dev/v7sxXbzOjVc/wCMCtHqJAAAJ

**Comment by cescoffier** [comment]
Fixed by #579
