### ISSUE TITLE
Mark default strategy in "signatures" chapter in some other way

### ISSUE THREAD

**Issue by zeljkot** [smallrye/smallrye-reactive-messaging#571]
The default strategy is marked with a yellow background. When I search for "POST_PROCESSING", for example, the browser highlights results in a same way so I cannot distinguish the default strategy from the search results.

Please use some other way to mark default strategy.

https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/signatures/signatures.html

**Comment by cescoffier** [comment]
This is an Antora thing. I would like to avoid "bold".

**Comment by zeljkot** [comment]
This looks like review remarks, I would rather go for bold.

**Comment by cescoffier** [comment]
What about using a different color, like light blue? Would it be ok?

Le mar. 2 juin 2020 à 00:18, Željko Trogrlić <notifications@github.com> a
écrit :

**Comment by cescoffier** [comment]
Fixed with the new documentation.
