### ISSUE TITLE
Open Tracing support

### ISSUE THREAD

**Issue by iabughosh** [smallrye/smallrye-reactive-messaging#587]
Is there a plan for including open Tracing support - like Jaeger/Kafka instruments - into reactive messaging.

**Comment by cescoffier** [comment]
We are starting integrating open telemetry.

**Comment by kenfinnigan** [comment]
Closing as duplicate of #562

**Comment by iabughosh** [comment]
Sorry for opening duplicate issue. I didn't now about OpenTelemetry before today :).

**Comment by kenfinnigan** [comment]
Not a problem, just an issue cleanup
