### ISSUE TITLE
Make using Kafka keys simpler

### ISSUE THREAD

**Issue by zeljkot** [smallrye/smallrye-reactive-messaging#588]
Most annotated methods can work with two kinds of types: payload and message. Messages provide more flexibility but are more complicated to use because they:
* cannot be automatically acknowledged POST_PROCESSING 
* cannot be marked as @Blocking

With Kafka, it is quite common to ask for message key, but then methods must work with messages rather than payloads, so all those ease of use features cannot be utilized.

Please provide a way to get Kafka keys and still be able to use simpler reactive API.

In the meantime, here is a workaround:

```java
@Incoming("some-topic")
@Outgoing("some-topic-internal")
public Message<Tuple2<String, byte[]>> onMessage(KafkaRecord<String, byte[]> message) {
  return message.withPayload(Tuple2.of(message.getKey(), message.getPayload()));
}

@Incoming("some-topic-internal")
@Blocking
public void onMessage(Tuple2<String, byte[]> tuple) {
  doSomething(tuple.getItem1(), tuple.getItem2());
}
```

**Comment by cescoffier** [comment]
Forgot to close this issue. It's been addressed in 2.5 with the support of `Record`.
