### ISSUE TITLE
Add readiness probe to the Kafka connector

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#591]
The probe would verify that the Kafka client is connected.

**Comment by vietk** [comment]
Just for information, maybe you want to unify the kafka experience towards extensions in Quarkus : the kafka-stream extension readiness probe is checking for the presence of topics on which the application is [supposed to be connected to](https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/health/KafkaStreamsTopicsHealthCheck.java).
