### ISSUE TITLE
Manual acknowledgement is not working properly on kafka

### ISSUE THREAD

**Issue by iischwuerfl** [smallrye/smallrye-reactive-messaging#595]
**Description**
The @Acknowledgement(Strategy.MANUAL) should prevent quarkus from automatic ACK the message.

**Actual Behaviour**
The message is dequed after processed

**Expected behaviour**
The message should not be dequed

**GIT**
I created a git repo demonstrating the problem
[GIT Repo](https://github.com/iischwuerfl/quarkus-kafka-ack-manual)

Configuration
Quarkus version: 1.5.0.Final
Quarkus Plugins:
quarkus-smallrye-reactive-messaging-kafka

I have 122 messages in the prices-topic.  As you can see below,  even tough I do not acknowledge a single message - the offset for this consumer  is set to the  latest message in the  topic.

```
$ ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group my-group-id

GROUP           TOPIC   PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                       HOST            CLIENT-ID
my-group-id    prices   0          122             122             0               my-client-id-d5d6f0d3-9370-416a-af90-f2d7aa5b88d7 /172.18.0.1     my-client-id

```
```
    @Incoming("prices")
    @Acknowledgment(value = Acknowledgment.Strategy.MANUAL)
    public CompletionStage<Void> receive(Message<String> message) {
        counter++;
        System.out.println("message with count " + counter + " processed.");
        return CompletableFuture.runAsync(() -> {
            //do nothing
        });
    }
```

**Comment by cescoffier** [comment]
Can you try setting `enable.auto.commit` to `false`? 

```
mp.messaging.incoming.prices.enable.auto.commit=false
```

**Comment by iischwuerfl** [comment]
Jepp, that's it. Now it works as expected, thanks.

Is it possible to mention this in the [documentation](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/acknowledgement/acknowledgement.html)?

**Comment by cescoffier** [comment]
Yes, please keep this issue opened. I will add it to the documentation.
