### ISSUE TITLE
amqp-quickstart : @Outgoing method with params not supported

### ISSUE THREAD

**Issue by survivant** [smallrye/smallrye-reactive-messaging#603]
I'm looking at this example
https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/advanced/broadcast.html

looks like it's possible to have parameters in methods

so I modify the class Sender.java  to have a String

@Outgoing("data")
    @Broadcast
    public CompletionStage<AmqpMessage> send(String xxx) {
        CompletableFuture<AmqpMessage> future = new CompletableFuture<>();
        delay(() -> {
            String message = "hello from sender";
            System.out.println("Sending (data): " + message);
            future.complete(AmqpMessage.builder().withBody(message).build());
        });
        return future;
    }

I try with version 2.0.4 and 2.1.0-SNAPSHOT

but I always get this error

javax.enterprise.inject.spi.DefinitionException: SRMSG00053: Invalid method annotated with @Outgoing: acme.Sender#send - no parameters expected
    at io.smallrye.reactive.messaging.MediatorConfigurationSupport.validatePublisher (MediatorConfigurationSupport.java:203)
    at io.smallrye.reactive.messaging.MediatorConfigurationSupport.validate (MediatorConfigurationSupport.java:84)
    at io.smallrye.reactive.messaging.DefaultMediatorConfiguration.compute (DefaultMediatorConfiguration.java:132)
    at io.smallrye.reactive.messaging.extension.CollectedMediatorMetadata.createMediatorConfiguration (CollectedMediatorMetadata.java:39)
    at io.smallrye.reactive.messaging.extension.CollectedMediatorMetadata.add (CollectedMediatorMetadata.java:24)
    at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$analyze$0 (MediatorManager.java:116)

**Comment by survivant** [comment]
my usecase it something like this

```
@Path("/messages")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class MessageResource {

    @POST
    @Path("/operation")
    @Outgoing("codec")
    @Broadcast
    public String sendOperation(String operation) {
        System.out.println("MessageResource sendOperation = " + operation);
        return "hello";
    }

    @Incoming("codec")
    public void handleMessage(String message){
        System.out.println("MessageResource received " + message);
    }

}
```

**Comment by cescoffier** [comment]
You cannot call Reactive Messaging methods directly.
You need to use an `Emitter`:

```java

@Inject @Channel("codec") Emitter<String> emitter;


@POST
public String sendOperation(String operation) {
  System.out.println("MessageResource sendOperation = " + operation);
  emitter.send(operation);
  return "hello";
}
```

In the current release, emitters cannot use `@Broadcast` (this has been contributed). The workaround, until the next version, is simple - just add a method passing the incoming message and annotate it with `@Broadcast`:

```java
@Incoming("codec")
@Outgoing("ops")
public String dispatch(String op) { return op; }
```
