### ISSUE TITLE
Is there any way to send data to external broker (mqtt,kafka,...) using @Outgoing ?

### ISSUE THREAD

**Issue by famartinrh** [smallrye/smallrye-reactive-messaging#61]
Given the microprofile-reactive-messaging specification seems reasonable to have code like this 

```java
@Outgoing(value="topic1")
public String sendUpperCase(String text) {
    return text;
}
@Incoming(value="topic1")
public void receive(String text) {
    System.out.println("Received " + text);
}
```

and be able to have messages send and received throught an external messaging broker or even a local vertx even bus, but after trying some configurations I'm not able to get this functionality.
Probably this is not suppported yet or just I didn't understand the docs correctly.

**Comment by cescoffier** [comment]
@famartinrh yes it's just not written yet. 
For instance, it would look at http://www.smallrye.io/smallrye-reactive-messaging/#_interacting_with_apache_kafka you can get an idea of how it would look like.

**Comment by famartinrh** [comment]
@cescoffier do you have any plans on how to implement this? I would like to help if possible

**Comment by cescoffier** [comment]
it's more about writing the TCK for connectors (Kafka, MQTT...). 

For implementations, it should be closed to the link I sent (which is a bit ahead of the spec).

**Comment by cescoffier** [comment]
Fixed now.
