### ISSUE TITLE
MQTT subscription topic wildcard stopped working in smallrye-reactive-messaging 2.0.3 (and still does not work in 2.1.0)

### ISSUE THREAD

**Issue by buehren** [smallrye/smallrye-reactive-messaging#615]
When subscribing to an MQTT topic, ```+``` and ```#``` can be used as wildcards ([more details](https://mosquitto.org/man/mqtt-7.html)).

Example: ```smallrye.messaging.source.my-topic.topic=#```

I tried Quarkus and found that wildcards no longer work in their latest versions ([Quarkus ticket](https://github.com/quarkusio/quarkus/issues/9769)). Then I tried smallrye-reactive-messaging without Quarkus.

Wildcards still work with smallrye-reactive-messaging 2.0.2 but stop working when switching to 2.0.3 or 2.0.4. It still fails in 2.1.0.

I have created an example project to reproduce the error (and to see it working in 2.0.2):
https://github.com/buehren/smallrye-reactive-messaging-mqtt-wildcard-problem

**Comment by cescoffier** [comment]
That's probably an unfortunate bug introduced when we implemented connection sharing.
