### ISSUE TITLE
Processing message with manual acknowledgement and @Blocking

### ISSUE THREAD

**Issue by flo-ryan** [smallrye/smallrye-reactive-messaging#628]
I'm faily new to reactive messaging and Kafka, so please excuse my potentially dumb question:

I'd like to consume messages/records from a Kafka topic and store them in a database. I need to make sure that the message was stored in the database successfully, before commiting the Kafka offset. 
To my understanding I can do this by using `@Acknowledgment(Acknowledgment.Strategy.MANUAL)` and returning a CompletableFuture via `return message.ack()`. In case I run into an error I would throw an exception and hence the offset wouldn't be committed.
Since I need to store the messages in the database, I read that I also need the `@Blocking` annotation, resulting in this:

```
    @Incoming("mychannel")
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    @Blocking
    @Transactional
    public CompletionStage<Void> consumeMessage(Message<MyMessageDto> message)
    {
        // store message in database here

        // throw exception here in error case

        return message.ack();
    }
```
This however gives me the following error:
```
Caused by: javax.enterprise.inject.spi.DefinitionException: Invalid method annotated with @Blocking:
com.text.MyConsumer#consumeMessage - The @Blocking annotation is only supported for methods returning an individual Message or a payload
```

Am I missing something here, maybe with how to (or not to) acknowledge a message, or this my scenario simply not possible (yet)?
Thanks a lot!

[I'm on version 2.0.3.]

----
EDIT:
I figured out, that this should do what I want to do:
```
    @Incoming("mychannel")
    @Acknowledgment(Acknowledgment.Strategy.POST_PROCESSING)
    @Blocking
    @Transactional
    public void consumeMessage(MyMessageDto message)
    {
        // store message in database here
        // throw exception here in error case
    }
```
Am I correct in that assumption?
With this option however I don't have access to the message's metadata. Is there a way to make this work using a message as input parameter?

**Comment by kenfinnigan** [comment]
Was going to say to just return a void.

I don't think you need the `@Acknowledgement` as post processing is the default for `@Incoming` that returns void.

**Comment by flo-ryan** [comment]
Yes, thank you. The second approach seems to work regarding the blocking and acknowledgement (which were my main concerns), however it only seems work with a payload as input param. 
Is there a way to make with work with a message (e.g. IncomingKafkaRecord) too?

**Comment by kenfinnigan** [comment]
What from the metadata do you need to access?

I don't recall the reasoning, but `@Blocking` and `@Incoming` with a `Message` type as the parameter is not supported. @cescoffier might recall why

**Comment by flo-ryan** [comment]
I'd like to access some Kafka metadata like the offset, partition, etc if possible - mostly for debugging.

**Comment by kenfinnigan** [comment]
Would tracing being present that sets that kind of information remove the need for accessing the metadata?

**Comment by cescoffier** [comment]
One possibility if you need the metadata is to create a structure containing the payload and your metadata:

```java
public class MyStructure<T> {

     private final T payload;
     private final IncomingKafkaMetadata metadata;

     public MyStructure(Message<T> msg) {
        this.payload = msg.getPayload();
        this.metadata = msg.getMetadata(IncomingKafkaMetadata.class).orElse(null);
     }
    // ... getters
}
```


Then just create this object in a method forwarding to the 


```java
@Incoming("a")
@Outgoing("b)
public Message<MyStructure<T>> wrap(Message<T> msg) {
    return msg.withPayload(new MyStructure(msg));
}

@Incoming("b")
@Blocking
public void process(MyStructure<T> structure) {
// ...
}
```

The message will be acknowledged when the processing completes.

**Comment by flo-ryan** [comment]
> Would tracing being present that sets that kind of information remove the need for accessing the metadata?

I'm afraid I don't understand. What would tracing be in that context?

> One possibility if you need the metadata is to create a structure containing the payload and your metadata:

Ah okay, I hadn't thought about something like that - that's a smart workaround, thanks!
