### ISSUE TITLE
@Blocking prevents exception from being logged

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-reactive-messaging#629]
With a method such as:

```
@Incoming("kafka-something")
@Blocking
public void onMessage(byte[] message) {
    throw new RuntimeException("Fakeception");
}
```

The exception results in the appropriate failure processing, but the actual exception isn't logged anywhere for subsequent investigation.

See https://github.com/quarkusio/quarkus/issues/10253 for full details

**Comment by zeljkot** [comment]
Additional issues is that message is acknowledged although an exception is thrown.

**Comment by kenfinnigan** [comment]
@zeljkot does this fix the issue?

**Comment by zeljkot** [comment]
@kenfinnigan Is it in some snapshot repo? How can I get it?

**Comment by cescoffier** [comment]
@zeljkot No, you would need to build it (`mvn clean install -DskipTests`).
