### ISSUE TITLE
Improve Documentation 

### ISSUE THREAD

**Issue by obbyK** [smallrye/smallrye-reactive-messaging#642]
I was searching for a solution to an error I was getting while using the amqp connector. After some googling of the error message `SRMSG00200: The method com.example.OutgoingTicketConsumer#processOutgoing has thrown an exception: java.lang.ClassCastException: class io.vertx.core.json.JsonObject cannot be cast to class com.example.models.Ticket (io.vertx.core.json.JsonObject and com.example.models.Ticket are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4b88ca8e). ` I ended up finding the answer [here](https://github.com/smallrye/smallrye-reactive-messaging/blob/26b7b01b992bd1e7518fc82b0c7d94d28d1afef6/documentation/src/main/doc/modules/amqp/pages/inbound.adoc), whereas the main documentation website (https://smallrye.io/smallrye-reactive-messaging/) didn't have it. It would be a very good learning experience to find most of what is required in the main website.

**Comment by cescoffier** [comment]
Would be updated during the next release.

Antora tends to link on the old (2) version instead of (2.1).

**Comment by chris-aeviator** [comment]
@obbyK how did you solve the issue? I'm facing the same with kafka + avro

**Comment by cescoffier** [comment]
@chris-aeviator can you provide the signature of the method?

**Comment by chris-aeviator** [comment]
@cescoffier thanks for your fast reply.

I'm seriously confused and overwhelmed by the amount of complexity and possibilities. 

the error is 
`2020-10-19 20:15:11,624 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00200: The method org.myzel.projectPlanner.ProjectInfoToPublishedProjectsMessageConsumer_7#consume has thrown an exception: java.lang.ClassCastException: class org.myzel.projectPlanner.domain.projectInfo cannot be cast to class java.lang.String (org.myzel.projectPlanner.domain.projectInfo is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @d400943; java.lang.String is in module java.base of loader 'bootstrap')
	at org.myzel.projectPlanner.ProjectInfoToPublishedProjectsMessageConsumer_7_SmallRyeMessagingInvoker_consume_a793a9cc76abe8ea0eedf6d7f2db6d132889e355.invoke(ProjectInfoToPublishedProjectsMessageConsumer_7_SmallRyeMessagingInvoker_consume_a793a9cc76abe8ea0eedf6d7f2db6d132889e355.zig:46)`

I'm using 
- smallrye-reactive-messaging
- on quarkus
- with a bpmn file defining the process (message start event `projectInfo`) via kogito
- avro schema via `maven-avro-plugin`

According to https://quarkus.io/blog/kafka-avro/ I've setup `avro-maven-plugin` to do 

```
        <outputDirectory>${project.build.directory}/generated-sources</outputDirectory>

**Comment by chris-aeviator** [comment]
by the way the consumer is crashing successfully on a consumed message only :0

**Comment by chris-aeviator** [comment]
I can see the record successfully being deserialized with the appropriate avro scheme before the error get's thrown

![grafik](https://user-images.githubusercontent.com/11522213/96499075-37a0d100-124d-11eb-9f85-2e9bd1d4094f.png)

my avro scheme
```
{
  "type": "record",
  "name": "projectInfo",
  "namespace": "org.myzel.projectPlanner.domain",
  "fields": [
    {
      "name": "title",
      "type": "string"
    },
    {
      "name": "project",
      "type": "string"
    },
    {
        "name": "description",
        "type": "string"
    }
  ]
}


```

**Comment by cescoffier** [comment]
Can you give me the signature of the method receiving (or expecting to receive) the message? 
String key should be fine, but the signature of the method should be something like:

```java
@Incoming(...)
public void consume(projectInfo info) {
 // ...
}
```

BTW, the `projectInfo` class not using the Java convention, it should be `ProjectInfo`. I don't believe it's the issue here, but something you may want to fix at some point.

**Comment by chris-aeviator** [comment]
@cescoffier 

I don't use ` @incoming` since I'm working with kogito here. My code (& "wiring" via the `bmpn` file) follows https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-quickstart-quarkus which does also not have `@incoming` annotations. It allows though to pass the data from a reactive messaging message ("travellers") to be passed into a function defined also in the `bpmn` file.

![image](https://user-images.githubusercontent.com/11522213/96547872-1e2f7180-12ad-11eb-9773-8c14f3ee2c86.png)

**Comment by cescoffier** [comment]
From the error message, Kogito expects a String and not a ProjectInfo. I don't know anything about Kogito. The Kafka / Reactive Messaging parts is ok (it does get the message, and deserialize them correctly).

**Comment by chris-aeviator** [comment]
It seems you've pointed me into the right direction.

When changing to capital `ProjectInfo`, telling `avro-maven` to generate into `/src/main/java` and remove my Handmade `ProjectInfo.java` it makes much more sense. Currently fiddling with the drools part but I will write an update whenever I solve this.

Thanks for your explanation of what's happening.

**Comment by chris-aeviator** [comment]
I'm ending up with the exact same Issue...

**Comment by chris-aeviator** [comment]
In the generated sources I can now see

```
    @org.eclipse.microprofile.reactive.messaging.Incoming("projectInfo")
    public void consume(String payload) {
        eventConsumerFactory.get(event -> {
            ProjectInfoToPublishedProjectsModel model = new ProjectInfoToPublishedProjectsModel();
            model.setProjectInfo(event);
            return model;
        }, org.myzel.projectPlanner.domain.ProjectInfo.class, ProjectInfoToPublishedProjectsMessageDataEvent_7.class, useCloudEvents).consume(application, process, payload, "projectInfo");
    }

```

**Comment by cescoffier** [comment]
So, it expects a String. Is there anything you can configure to use another type? (is it something you can configure).

You may want to bring this issue to Zulip where the Kogito team can help.

**Comment by chris-aeviator** [comment]
It is set to take `com.myzel.projectPlann.ProjectInfo` as in the example Repo - I'll try to chat with them, thanks

**Comment by chris-aeviator** [comment]
@cescoffier this is indeed an issue with kogito, they have their own deserilization for events in between and thus the bean vs. string issue. They have an issue on https://issues.redhat.com/browse/KOGITO-2866 that should deal with it for anybody interested.

**Comment by chris-aeviator** [comment]
I solved this by adding a consumer as `ProjectInfoConsumer` that consumes the avro message and forwards it as a string in an reactive message

```
    @Incoming("ProjectInfo")
    @Outgoing("projectInfo")
    public String consume(ProjectInfo projectInfo) {
        logger.info("received projectinfo on consumer");
        return projectInfo.toString();
    }
```

whereas `ProjectInfo` is the avro-enabled kafka message coming in and `projectInfo` is the message that's passed internally, now everything is working as expected. Kogito team was really cool and they added avro support to their feature timeline (https://issues.redhat.com/browse/KOGITO-3647)
