### ISSUE TITLE
Nacked message never gets redelivered or goes into infinite redelivery when using Artemis ActiveMQ

### ISSUE THREAD

**Issue by vbuitoni** [smallrye/smallrye-reactive-messaging#673]
I've been experimenting with the new fault-tolerance model implemented in SmallRye Reactive Messaging.

Certainly there's been an improvement, since now I am able to continue message reception after a failure, but it still does not work as I expected.

If I configure the failure-strategy to "release", the message goes back to the queue and will enter an infinite loop of redeliveries, until the failure is resolved (or if the failure is unresolvable the message will be redelivered forever).

If I configure the failure-strategy to "reject", the message goes directly to the DLQ right on the first failure, never allowing for it to be retried.

What I wanted is to use the Artemis ActiveMQ redelivery mechanism, in which after a failure the message will be redelivered a configurable X number of times, with a configured interval between retries, and after X redeliveries the message goes into the DLQ.

I am able to trigger this intended behavior using the Qpid JMS connector, but not with Reactive Messaging.

**Comment by cescoffier** [comment]
How is this configured from the receiver side?

**Comment by vbuitoni** [comment]
Configuration:

mp.messaging.incoming.bcbp-boarding.connector=smallrye-amqp
mp.messaging.incoming.bcbp-boarding.address=bcbp-boarding
mp.messaging.incoming.bcbp-boarding.container-id=bcbp-boarding
mp.messaging.incoming.bcbp-boarding.failure-strategy=release

Receiver code:

`	@Incoming("bcbp-boarding")`
`	@Blocking`
`	@Acknowledgment(POST_PROCESSING)`
`	@Transactional`
`	public String processData(String data) {`
`}`

Not sure if that's what you asked. Please let me know if you need more information.

**Comment by cescoffier** [comment]
I meant how can I trigger this behavior? Is it something set in the broker, in the consumer, or in the sender? It seems to me that it's a broker behavior (that would be based on an "attribute" set in the dispatched message.

**Comment by vbuitoni** [comment]
I guess that the message needs to be marked as "redelivered".

Using the QPid JMS Client, I call the method JMSContext.recover(), in order to trigger this behaviour.

From the JMSContext.recover() API:

`Restarting a session causes it to take the following actions:`

`Stop message delivery`
**Mark all messages that might have been delivered but not acknowledged as "redelivered"**
`Restart the delivery sequence including all unacknowledged messages that had been previously delivered.` 
`Redelivered messages do not have to be delivered in exactly their original delivery order.`

For more information about this redelivery mechanism in the broker:
https://activemq.apache.org/components/artemis/documentation/latest/undelivered-messages.html

**Comment by cescoffier** [comment]
I still don't see how this feature is triggered. The documentation seems to indicate that it's something to be enabled in the broker, and not in the client/message.

**Comment by cescoffier** [comment]
@gemmellr any idea?

**Comment by gemmellr** [comment]
Releasing is explicitly saying 'message hasnt been processed, make it available again, dont increment the delivery count'.

Rejecting is explicitly saying 'message is invalid, burn it, i.e. dont make it available again, do increment the delivery count'.

The _modified_ disposition can be used to indicate a delivery failure and whether it shouldnt be sent to this consumer again (still in play for other consumers), and incremement the delivery-count field of the message.

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#section-distribution-nodes
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#section-delivery-state

The Qpid JMS comparison isnt as clear cut as it might seem. Its nuanced in that the typical recover() operation is performed locally within the client, without sending anything to the broker. However, there are points when a consumer is closed and/or a session is closed or recovered, where messages that have been recover()'ed at some point but not delivered again and acknowledged can have a modified(delivery-failed) disposition sent, bumping their delivery-count (which tracks failed deliveries) for future dispatches to consumers.

**Comment by vbuitoni** [comment]
@gemmellr You're correct.

What I do with the Qpid JMS is the recover() operation followed by a consumer close().

It seems that to trigger the expected behaviour we need exactly what you said, the modified outcome, with the delivery-failed flag set to true.
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-modified

**Comment by cescoffier** [comment]
So we need to provide 2 more "nack strategies":

* _modified_ with `delivery-failed` flag set to `true` - proposed name: modified-as-failed
* _modified_ with `undeliverable-here` flag set to `true` - proposed name: modified-as-undeliverable

In the first case, the delivery will be re-attempted.
In the second case, it won't be re-attempted on this node (but maybe elsewhere).

@gemmellr Does that make sense?

**Comment by gemmellr** [comment]
Just being sure: the second should have both flags set.

I'd suggest modified-failed and modified-failed-undeliverable-here for names.

**Comment by cescoffier** [comment]
Thanks @gemmellr! Makes sense, and I prefer your names.

**Comment by cescoffier** [comment]
Opened a PR providing the 2 new nack strategies: #703
