### ISSUE TITLE
Quarkus authentification problem for MQTT

### ISSUE THREAD

**Issue by Tockra** [smallrye/smallrye-reactive-messaging#679]
Hi Folks,

I'm new in the quarkus cosmos. 
I'm using your mqtt client, but I struggling with adding my ca.crt.
I see no way to configure the ca.crt (trusted key store). 
I just see the possibility to trust all certificates, what isn't a good idea: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/mqtt-server/mqtt-server.html .

Is there a different way? 

T

**Comment by cescoffier** [comment]
It would require #693.

**Comment by ozangunalp** [comment]
It is possible now to customize the mqtt client and it integrates with the Quarkus TLS registry.
