### ISSUE TITLE
Cannot configure dead letter queue value serializer

### ISSUE THREAD

**Issue by ivangreene** [smallrye/smallrye-reactive-messaging#681]
When using Kafka `dead-letter-queue` failure strategy, adding a `dead-letter-queue.value.serializer` has no impact, and the name deduced from the `value.deserializer` is still used. See [KafkaDeadLetterQueue lines 41-42](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/fault/KafkaDeadLetterQueue.java#L41-L42), it is using the key serializer config rather than value deserializer

**Comment by cescoffier** [comment]
Thanks for reporting! Definitely a bug.
