### ISSUE TITLE
Health creates duplicate entries for the Kafka topics

### ISSUE THREAD

**Issue by zeljkot** [smallrye/smallrye-reactive-messaging#690]
Health is both in UP and DOWN state for the Kafka topics (Quarkus 1.7 / messaging 2.2.1):

```
{
	"status": "DOWN",
	"checks": [
		{
			"name": "SmallRye Reactive Messaging",
			"status": "UP",
			"data": {
				"topic1": "[OK]",
				"topic2": "[OK]",
				"topic3": "[OK]"
			}
		},
		{
			"name": "Database connections health check",
			"status": "UP"
		},
		{
			"name": "SmallRye Reactive Messaging",
			"status": "DOWN",
			"data": {
				"topic1": "[OK]",
				"topic2": "[OK]",
				"topic3": "[KO] - Unable to find topic(s): some_topic_3"
			}
		},
		{
			"name": "Kafka connection health check",
			"status": "UP",
			"data": {
				"nodes": "kafka1:9092,kafka2:9092"
			}
		}
	]
}
```

**Comment by kenfinnigan** [comment]
Is this the situation immediately upon startup?

**Comment by zeljkot** [comment]
No, it also happens later, too.

**Comment by cescoffier** [comment]
Definitely a bug... 
I would have expected the implementation to use a Map, not a list of entries...

**Comment by cescoffier** [comment]
@zeljkot Are you requesting `/health`? If so, you got both the liveness and readiness checks. 

@xstefank can you tell me what `/health` should contain? Should it contain all checks or only readiness/liveness?

**Comment by cescoffier** [comment]
@zeljkot In your output, it is likely possible that you got both readiness and liveness:

```
{
	"status": "DOWN",
	"checks": [
		{
			"name": "SmallRye Reactive Messaging",   <---- liveness, we were able to connect to Kafka
			"status": "UP",
			"data": {
				"topic1": "[OK]",
				"topic2": "[OK]",
				"topic3": "[OK]"
			}
		},
		{
			"name": "Database connections health check",
			"status": "UP"
		},
		{
			"name": "SmallRye Reactive Messaging",    <------ readiness, some topics are not (yet) created
			"status": "DOWN",
			"data": {
				"topic1": "[OK]",
				"topic2": "[OK]",
				"topic3": "[KO] - Unable to find topic(s): some_topic_3"
			}
		},
		{
			"name": "Kafka connection health check",
			"status": "UP",
			"data": {
				"nodes": "kafka1:9092,kafka2:9092"
			}
		}
	]
}
```

**Comment by cescoffier** [comment]
@zeljkot Try to check `/health/live` and `/health/ready`

**Comment by xstefank** [comment]
@cescoffier right, `/health` should contain both liveness and readiness.

**Comment by cescoffier** [comment]
Thanks @xstefank, in this case, should we add a hint in the `name` to distinguish both? Like:

- "name": "SmallRye Reactive Messaging - liveness check"
- "name": "SmallRye Reactive Messaging - readiness check"

What are the recommendations if you provide both?

**Comment by kenfinnigan** [comment]
Probably makes sense to have different names, as they are indicating different things

**Comment by cescoffier** [comment]
@kenfinnigan Are the names proposed in my previous comment ok?

**Comment by kenfinnigan** [comment]
I think so yeah.

We can always adjust later if needed

**Comment by cescoffier** [comment]
I've opened #701.

**Comment by zeljkot** [comment]
Aha, so I should use "live" instead of "health".

BTW having "ready" false if a topic is not created could be misleading as topic could be automatically created. As topics should be created in production and readiness is not relevant for dev, this behavior is OK.

In any case, cause should be reported:

```
responseBuilder.down()
                    .withData("error", e.getMessage()); // pass the exception message
```

**Comment by zeljkot** [comment]
You were right, the issue was caused by calling "health" without "live".
