### ISSUE TITLE
Channel name with dot is not supported

### ISSUE THREAD

**Issue by marcelorubim** [smallrye/smallrye-reactive-messaging#695]
I'm trying to use the AMQP connector to consume a channel. 

But the channel was created with several dots in the name and I didn't find a way to make it work.

Looking at the code seems that it won't really work in the current implementation, as it removes the part before the first dot in the name. Any reason why?

```java
    static Map<String, ConnectorConfig> extractConfigurationFor(String prefix, Config root) {
        Iterable<String> names = root.getPropertyNames();
        Map<String, ConnectorConfig> configs = new HashMap<>();
        names.forEach(key -> {
            // $prefix$name.key=value (the prefix ends with a .)
            if (key.startsWith(prefix)) {
                // Extract the name
                String name = key.substring(prefix.length());
                if (name.contains(".")) { // We must remove the part after the first dot
                    String tmp = name;
                    name = tmp.substring(0, tmp.indexOf('.'));
                    configs.put(name, new ConnectorConfig(prefix, root, name));
                } else {
                    configs.put(name, new ConnectorConfig(prefix, root, name));
                }
            }
        });
        return configs;
    }
```

I would gladly try to contribute with a PR to make this possible.

**Comment by kenfinnigan** [comment]
Dots are a separator between parts of a config key.

I'm not aware of a way to escape the dots so it can be processed for your case

**Comment by marcelorubim** [comment]
In Quarkus is possible to put a key with dots surrounded by double quotes.

I think it's a really good approach

**Comment by kenfinnigan** [comment]
Honestly I don't know.

You can try it and see what happens.

Either way, we need to think about an approach for making it work if it doesn't already

**Comment by cescoffier** [comment]
Any update (sorry just back from PTO)

If it does not work, can you provide a reproducer with the expected "double-quote" format?

**Comment by marcelorubim** [comment]
I've just sent the PR with this change.

Please review it and let me know if I can improve anything.

**Comment by eriknyk** [comment]
Hello I'm using v2.4 but still facing an issue: 
https://github.com/smallrye/smallrye-reactive-messaging/pull/699#issuecomment-782731167

Regards.
