### ISSUE TITLE
CDI qualifiers are ignored in MediatorManager#initializeAndRun()

### ISSUE THREAD

**Issue by mkouba** [smallrye/smallrye-reactive-messaging#7]
As a result, if you declare a subscriber/publisher/processor on a bean with a qualifier the bean is not found and you get `UnsatisfiedResolutionException` when trying to initialize a mediator.

Steps to reproduce:
```java
@Foo
@ApplicationScoped
public class QuickStart {

  public static void main(String[] args) {
    SeContainerInitializer.newInstance().initialize();
  }


  @Outgoing("source")
  public PublisherBuilder<String> source() {
    return ReactiveStreams.of("hello", "with", "SmallRye", "reactive", "message");
  }

  @Incoming("source")
  @Outgoing("processed-a")
  public String toUpperCase(String payload) {
    return payload.toUpperCase();
  }

  @Incoming("processed-a")
  @Outgoing("processed-b")
  public PublisherBuilder<String> filter(PublisherBuilder<String> input) {
    return input.filter(item -> item.length() > 4);
  }

  @Incoming("processed-b")
  public void sink(String word) {
    System.out.println(">> " + word);
  }

  @Qualifier
  @Retention(RetentionPolicy.RUNTIME)
  @Target({ElementType.TYPE})
  public @interface Foo {}

}
```

**Comment by cescoffier** [comment]
Of course, I can work around the issue using:

```
 mediator.initialize(instance.select(mediator.getConfiguration().getBeanClass(),
    Any.Literal.INSTANCE).get());
```

But, I'm not sure it's the right approach. Is there a way to know the qualifier applied on a bean class?

**Comment by mkouba** [comment]
It's definitely not correct ;-). Well, you can try to observe `ProcessBean` instead of `ProcessAnnotatedType`, analyze its `ProcessBean.getAnnotated()` and then use `ProcessBean.getBean().getQualifiers()`.

**Comment by cescoffier** [comment]
Yes, that's what I was looking for. I also believe I need to change the `StreamRegistry` to take into account the qualifiers. A method qualified with `@Foo` should only consume items from a producer also qualified with `@Foo`.

**Comment by mkouba** [comment]
> I need to change the StreamRegistry to take into account the qualifiers. A method qualified with `@Foo` should only consume items from a producer also qualified with `@Foo`.

Hm, in CDI, qualifiers are only used to distinguish beans. For mediators I think that ids coming from `Incoming#value()` and `Outgoing#value()` are enough.

By the way, what happens if I declare e.g. multiple processors annotated with `@Incoming("processed-a") @Outgoing("processed-b")`? I suppose that both processors are invoked but the ordering is undefined, or?

**Comment by cescoffier** [comment]
Thanks for your feedback on the qualifiers. It's going to make my code much simpler! 

About your question, can I answer "it depends" :-).

* Case 1 - multiple subscribers, 1 publisher

```
@Ougoing("foo") publisher

@Incoming("foo") subscriber1
@Incoming("foo") subscriber2
```

By default, only a single _subscriber_ will get the data. Which one is undefined. In practice, if you want to broadcast a message to several _subscribers_, use the `@Broadcast` annotation. However, the ordering is undefined and please use an immutable structure as you have visibility to changes made by the other subscribers. `@Broadcast` dispatches the messages to all subscribers. I'm thinking about adding a _round robin_ annotation that implements a non-strict round robin. 

Case 2 - multiple publishers, 1 subscriber

```
@Ougoing("foo") publisher1
@Ougoing("foo") publisher2

@Incoming("foo") subscriber
```

Again, by default, the subscriber is connected to a single publisher. Which one is undefined. So collect from all, use the `@Merge` annotation. `@Merge` has several policies:

- merge - take the data from all publishers as they come
- one - same behavior than without the annotation
- concat - take the data from all publishers, but waits for the completion of a stream before taking the data from the stream. Order is unspecified

The set of policy may evolve, typically, the concept of `zip` is often requested.

**Comment by mkouba** [comment]
Case 1 - you mean `io.smallrye.reactive.messaging.annotations.Multicast`? I'd say that if it's not used then it should be a deployment error.
Case 2 - Ok. Again, if `@Merge` is not declared the deployment should fail.

I was talking about multiple processors which would be case 3 - one subscriber, one publisher, multiple processors. All processors are invoked in undefined order, right?

**Comment by cescoffier** [comment]
Case 1 - Update your working copy :-) It's been renamed, one or two days ago.

About failing the deployment, I was wondering and wanted to discuss with CDI experts about the "regular" approach. I'm all for failing the deployment.

**Comment by mkouba** [comment]
Yep, deployment failure is "regular" ;-)

**Comment by cescoffier** [comment]
I've opened https://github.com/smallrye/smallrye-reactive-messaging/issues/13.

I've also opened a PR about the initial issue.
