### ISSUE TITLE
AMQP sender do not reconnect after disconnection

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#704]
Related to https://github.com/quarkusio/quarkus/issues/11160

The AMQP sender to not reconnect or attempt to reconnect.
All messages that should be sent to AMQP are nacked.

**Comment by gsmet** [comment]
@cescoffier any chance we could have this fix in time for Quarkus 1.7.1.Final (that I plan to release on Wednesday so we would need the Quarkus PR on Tuesday latest)?

**Comment by cescoffier** [comment]
Yes, should be ok.
