### ISSUE TITLE
Add support for @Blocking and @Incoming to have CompletionStage and Uni return types

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-reactive-messaging#718]
Currently, any `@Incoming` method annotated with `@Blocking` does not allow a return type of either `Uni` or `CompletionStage`.

We should add support for this

**Comment by kenfinnigan** [comment]
@cescoffier starting to look at this.

Am I correct in thinking that returning `Uni<Void>` is ok, but `Uni<String>` is not because then it's no longer a subscriber? And likewise for `CompletionStage`.

**Comment by cescoffier** [comment]
Yes.

You can also drop the emitted item, but I think it’s better to make the
user aware that it won’t send the item anywhere, and so fail.
