### ISSUE TITLE
TTL conf property not working in AMQP connector

### ISSUE THREAD

**Issue by rrubiomysphera** [smallrye/smallrye-reactive-messaging#723]
Hello,

The TTL attribute seems to be not working when is set in the configuration file (mp.messaging.outgoing._channel-name_.ttl), but works properly when setting it in the message metadata. Maybe some kind of regression in the following code?

https://github.com/smallrye/smallrye-reactive-messaging/blob/2dc15eb8952429331d91fe73c1141d665e7d1567/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpMessageConverter.java#L46-L50

Regards,

**Comment by cescoffier** [comment]
Oh yes... definitely a bug, it sets the TTL to 0.

**Comment by cescoffier** [comment]
See https://github.com/smallrye/smallrye-reactive-messaging/pull/725
