### ISSUE TITLE
Allow a SmallRye Reactive Messaging Integrator to 'wrap' @Blocking methods.

### ISSUE THREAD

**Issue by hutchig** [smallrye/smallrye-reactive-messaging#731]
In integrating SmallRye reactive messaging into the OpenLiberty in CICS environment the Vert.x code used
in the implementation will use a VertxThread to run the `@Blocking` method. 
We want `@Blocking` methods to be able to make CICS API calls and currently those can only be made
from 'CICS capable' threads. 
So in that set up there are two software components that want to be the thread factory!

We would like the ability to 'wrap' the `@Blocking` method's code (by using something like an SPI or config/bean
rather than an API) so that we can run the system provided wrapper on the VertxThread 
(as if IT is the `@Blocking` method) but then asynchronously kick of the
@Blocking method via our 'native' executor on a CICS capable thread.

This issue follows on from
https://groups.google.com/g/smallrye/c/1yXvPj9fOkg
and is written as a issue for a PR which I will write as a means
to discuss the proposal concretely.

It is important that what gets wrapped is just the user's code as, as we control
what is on the user's classpath, we can make sure the thread and context are suitable
for our particular environment and do not have contradictory requirements due to Vertx/SmallRye etc
code being inside what gets wrapped.

**Comment by hutchig** [comment]
I though of this when I read https://github.com/quarkusio/quarkus/issues/11801#issuecomment-686263141

**Comment by cescoffier** [comment]
Not really, `@Blocking` is already about off-loading, but it comes with strict rules and settings. Some signatures have not been implemented in the initial development, but we are resisting this and @kenfinnigan is working on the missing ones.

**Comment by hutchig** [comment]
I have been doing further work on the z/OS side and talking to various CICS architects about CICS (and DB2) and threading on z/OS. I believe that wrapping the reactive messaging @Blocking calls and doing a thread hop is not going to be a good solution.  So the plan is to progress/advocate a ServiceLoad'able Executor for Vert.x via the existing PR for executeBlocking underneath. So I will close the issue. Thanks again for your help in considering it.
