### ISSUE TITLE
Multi-Tenant Kafka streams

### ISSUE THREAD

**Issue by mostafacs** [smallrye/smallrye-reactive-messaging#739]
Hi, 

I have a project with a multi-tenant and I want to stream process data for each tenant.
Every tenant will have its own topic per task.

Do you support runtime creation of consumer and subscriber without or with @Incoming, @Outcoming annotations?
Or @Incoming and @Outcoming can support patterns for example all topics started with `products` and away to refresh when creating new topics at runtime.

**Comment by cescoffier** [comment]
On the incoming side, you should use "patterns".
One channel receives records from multiple topics. 
You can check the topic by looking inside the attached Kafka incoming metadata (https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/kafka/kafka.html#_inbound_metadata).

On the outgoing side, you can use outbound metadata (https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/kafka/kafka.html#_outbound_metadata) to configure in which topic the record must be written.

The _refresh_ is something managed by Kafka itself. You need to configure the `metadata.max.age.ms` attribute indicating how often the metadata are retrieved.
