### ISSUE TITLE
Reactive messaging health check fails if no topic name is specified

### ISSUE THREAD

**Issue by andreas-eberle** [smallrye/smallrye-reactive-messaging#768]
I'm using smallrye reactive messaging with kafka and have a connection configured without a topic name. This is because I want to send messages to dynamic topics at runtime. My config looks like this

```
quarkus.kafka.health.enabled=true
kafka.bootstrap.servers=${KAFKA_SERVER:localhost:9092}
mp.messaging.outgoing.events.connector=smallrye-kafka
mp.messaging.outgoing.events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
``` 

and I send messages with an `Emitter` by adding an `OutgoingKafkaRecordMetadata` object with the desired topic name.

I now wanted to use the kafka health checks and noticed that the "events" connector is shown as `DOWN` because its topic cannot be found. However, I never specified a topic.

```

{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "UP",
            "data": {
                "events": "[OK]"
            }
        },
        {
            "name": "Kafka connection health check",
            "status": "UP",
            "data": {
                "nodes": "host.docker.internal:9092"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "events": "[KO] - Unable to find topic events"
            }
        }
    ]
}
```

I think this check shouldn't/cannot be done if no topic name is set.

**Comment by cescoffier** [comment]
Unfortunately, the default topic is the channel name. So it means that I can't distinguish this case.
However, I can add a specific attribute to disable the readiness health check. Would it be ok?

**Comment by cescoffier** [comment]
@andreas-eberle I've opened the following PR #771.

**Comment by andreas-eberle** [comment]
Yes, that is fine for me.

**Comment by andreas-eberle** [comment]
Just to be sure, the connection health check will still be enabled, correct?

**Comment by cescoffier** [comment]
Yes, only the readiness will be disabled (per channel).

Le mer. 23 sept. 2020 à 14:12, Andreas Eberle <notifications@github.com> a
écrit :

**Comment by cescoffier** [comment]
I will revisit a bit the PR, and basically it's #771.
