### ISSUE TITLE
Add support for @Blocking

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#79]
`@Blocking` indicates that the method is blocking and must be called on a worker thread.

The `@Blocking` annotation can indicate the max level of concurrency (`concurrency` attribute, defaulting to 1.

**Comment by barata0** [comment]
Hi,

Any news on this?

**Comment by cescoffier** [comment]
Not yet. 

PR are welcome BTW :-)

**Comment by barata0** [comment]
I'll try but I need some light!

On (https://github.com/vert-x3/vertx-amqp-client/blob/e603ecb517c28eab6212e264ac30025a307176f9/src/main/java/io/vertx/amqp/impl/AmqpReceiverImpl.java) there is a piece of code:


```
    // Disable auto-accept and automated prefetch, we manage disposition and credit
    // manually to allow for delayed handler registration and pause/resume functionality.
    this.receiver
      .setAutoAccept(false)
      .setPrefetch(0);
```

This prefetch option should be configurable? And this configuration should be set by smallrye? 

This configuration should be defined in the @Blocking annotation or in the application.properties file?

**Comment by cescoffier** [comment]
@barata0 no, this is fine.

The `@Blocking` annotation indicates that a method is blocking:

```
@Incoming("in")
@Outgoing("out")
@Blocking
public String process(String in) {
    Thread.sleep(1000); // Blocking :-)
     return in;
}
```

In this case, the execution of this method must be offloaded to a worker thread pool.
Now, what's not clear is how, once the method has processed the message, we go back to the previous thread. This is where Vert.x was incredibly useful.

**Comment by barata0** [comment]
OK,

Using the **CompletableStage** method signature runs in a **different worker thread** right? Do you expect the same behaviour?

If yes its just the case of wrapping the method call on it?

```
  @Incoming
  public CompletionStage<Void> consume(Message<String> message) {
    return CompletableFuture.runAsync(new DummyWorker(input));
  }
 
```

**Comment by cescoffier** [comment]
Yes and no,

Yes, it would be a different thread pool (fork join) but we want to have control on this pool (so it should be configurable - number of threads, and so on).

**Comment by Emily-Jiang** [comment]
It seems this issue is related #423 .  I noticed this also introduces the dependencies on Vert.x. In preparing for the investigation on whether Open Liberty can cope with the Ver.x dependency , we would like to have a view on what level of Vert.x dependency this PR brings in. I have a couple of questions:

1. Is the above commit ready to be pulled and start prototype within? 

1. Are there going to be additional dependencies on Vert.x when addressing #423 ?

**Comment by kenfinnigan** [comment]
It wasn't originally related, but when discussing it we realized a dependency on Vert.x simplifies the implementation of `@Blocking` significantly.

I will likely be submitting the PR this afternoon, I'm currently working on some additional tests.

I believe the dependencies for #423 are basically the same, right now. That's not to say in 6 months something different is required, but that's hard to predict

**Comment by Emily-Jiang** [comment]
Thanks @kenfinnigan ! From the roadmap of [SmallRye 2.0](https://github.com/smallrye/smallrye-reactive-messaging/milestone/7), it seems #423 is not in scope for 2.0 release, but this one is. Right?

**Comment by kenfinnigan** [comment]
That was an omission, both of them should be
