### ISSUE TITLE
Add support for Emitter

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#80]
An `Emitter` is an injected instance allowing the user to send messages to a stream. 

```
@Inject @Stream("my-stream")
Emitter<String> emitter;

@Inject @Stream("my-stream-2")
Emitter<Message<String>> emitter2;

// ...

emitter.send("hello");
emitter.fail(new Exception(e));
emitter.complete();
```

_Implementation details_

The `Emitter` is _produced_ by the _Stream Manager_. 
On production:
1. Search the stream (SubscriberBuilder)
2. Creates the emitter
3. Creates a Publisher from the Emitter (buffer required)
4. Connect the streams

**Comment by haraldatbmw** [comment]
Is the Emitter defined in the MicroProfile Reactive Messaging specification or is this a proprietary feature of smallrye implementation?

**Comment by cescoffier** [comment]
At the moment it’s a proprietary extension. As it seems to be widely used and bridge the ‘imperative’ and ‘reactive´worlds, I plan to propose to the next version of the spec.

While not perfect, it also allows to implement ‘forks’ (route messages to different channels).

**Comment by haraldatbmw** [comment]
I'm using it from a REST resource class to produce a kafka event on a specific HTTP request. So I'm wondering this is not part of the spec already. Is there a spec supported way to produce an event from a REST resource? If not I highly recomment to propose it to the next version!
