### ISSUE TITLE
Support subscribing with Multi<Message<>> with reactive messaging handling the acks.

### ISSUE THREAD

**Issue by andreas-eberle** [smallrye/smallrye-reactive-messaging#804]
Currently, it is not possible to subscribe to a topic and get use the `Multi<Message<<>>` parameter type. This can e.g. be helpful when you want to subscribe to events and batch them before you process them further.

A workaround at the moment is to produce an internal topic that handles the acks separately (see code sample, Kotlin).

```
    @Incoming("events")
    @Outgoing("events-persisted")
    fun persistEvents(messages: Multi<Message<Event>>): Multi<Message<Event>>? {
        return messages
                .groupItems().intoLists().of(256)
                .emitOn(Infrastructure.getDefaultWorkerPool())
                .flatMap { messagesBatch ->
                    persistBatch(messagesBatch)
                    Multi.createFrom().items(messagesBatch.stream())
                }
                .emitOn(Infrastructure.getDefaultExecutor())
    }

    @Incoming("events-persisted")
    fun messageAcknowledging(message: Message<EpcisEventMetadataDto>): Uni<Void> {
        return Uni.createFrom().completionStage(message.ack())
    }
```

It would be perfect, if we could define only the method `persistEvents` from the example above without the `@Outgoing` annotation and having reactive messaging automatically handle the acks for us.

**Comment by cescoffier** [comment]
In the case of a Multi to Multi, we can't manage (post) acknowledgment automatically, as the transformation may produce multiple messages from a single incoming one. So we cannot track the successful processing.

However, pre-ack and manual are supported. 
I believe manual (which is the default) is the best in this case, and so you can ack the message individually when the `persistBatch` has completed its work.
