### ISSUE TITLE
Remove hard dependency on Vertx

### ISSUE THREAD

**Issue by tevans78** [smallrye/smallrye-reactive-messaging#81]
Hi @cescoffier,

We would like to use `smallrye-reactive-messaging-provider` without Vertx. At the moment there are some hardcoded dependencies which make this difficult. For example in the ReactiveMessagingExtension...

https://github.com/smallrye/smallrye-reactive-messaging/blob/1bda1671bf9da538fff6c1503412473bca49e68e/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ReactiveMessagingExtension.java#L67

In the short term, to make this work without Vertx on the classpath, I have had to fork this class and comment out the call to `registerVertxBeanIfNeeded`.

Also, in ConfigurationHelper there is a dependency on the vertx json parser. It might be a good idea to use json-p instead since that is also in MicroProfile.

https://github.com/smallrye/smallrye-reactive-messaging/blob/1bda1671bf9da538fff6c1503412473bca49e68e/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/spi/ConfigurationHelper.java#L3

**Comment by cescoffier** [comment]
The `ConfigurationHelper` is something that needs to go away very soon. If you see my commits from yesterday, I had to slightly change it and it's not very reliable. So this part can be actually moved in the "connector" that need it and improve there.

The Bean registration could also be moved into the connectors that need Vert.x (Kafka, AMQP, MQTT, HTTP). Alternatively, we could try to load the Vert.x class and if not there, not register it. (@mkouba would that work?)

**Comment by Emily-Jiang** [comment]
@cescoffier @mkouba any update? Can you guys remove the dependency so that we can consume this jar?

**Comment by mkouba** [comment]
> Alternatively, we could try to load the Vert.x class and if not there, not register it. (@mkouba would that work?)

Both approaches should work. However, I'd prefer less reflection magic ;-). So we could create a separate maven module with a CDI extension that would register the Vertx bean if needed.

**Comment by cescoffier** [comment]
Fixed it using `Instance<Vertx>` and checking if it's satisfied.
