### ISSUE TITLE
Emitter wrongly implements EmitterBehavior

### ISSUE THREAD

**Issue by kabir** [smallrye/smallrye-reactive-messaging#830]
org.eclipse.microprofile.reactive.messaging.Emitter extends io.smallrye.reactive.messaging.EmitterBehavior.

This differs from the upstream spec version of Emitter

**Comment by kenfinnigan** [comment]
It's one of these, innovating the spec pieces.

Otherwise it requires duplicating a tonne of identical code

**Comment by cescoffier** [comment]
Yes, we need to see how we can avoid duplications.
