### ISSUE TITLE
How to set up ssl options (certificates/jks) for secure connections in mqtt library?

### ISSUE THREAD

**Issue by ustari28** [smallrye/smallrye-reactive-messaging#846]
Hello,

I want to set up a TLS connection with smallrye-mqtt but when you see mqttoption there is no available options for doing this kind of connections.

Could you tell me how I can set up?

Best regards!

**Comment by cescoffier** [comment]
Unfortunately, this is not yet possible.
There is an open issue about this: https://github.com/smallrye/smallrye-reactive-messaging/issues/693.

**Comment by cescoffier** [comment]
(Closed as duplicate)
