### ISSUE TITLE
docs: "Edit this Page" is broken

### ISSUE THREAD

**Issue by lorenzleutgeb** [smallrye/smallrye-reactive-messaging#850]
In the docs at https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2 the link with link text "Edit this Page" in the top right area of the page is broken. The corresponding `<a>` tag has `href=""` when this should probably be `href="https://..."`.

**Comment by cescoffier** [comment]
My Antora skills are inexistent. I've tried multiple times to remove that link...

**Comment by cescoffier** [comment]
I was finally able to remove it: https://github.com/smallrye/smallrye-reactive-messaging/pull/852 (same PR as the merge doc improvement)

**Comment by lorenzleutgeb** [comment]
As a side note: I would have tried to provide a fix for #851 if the "Edit this Page" link would have worked. My hope and intention was that someone would fix it, in the sense that it the link would lead to the corresponding file on GitHub, making it easier for outsiders to contribute. Now I feel somewhat sad that you removed the link altogether, but of course you are the primary contributor so this is your choice.

**Comment by cescoffier** [comment]
I don't believe we can compute the right adoc file containing the page to edit. There are many modules, pages are the concatenation of multiple adoc files and some parts of the documentation are generated. See https://github.com/smallrye/smallrye-reactive-messaging/tree/master/documentation for details. 

I had to wrap Antora with some maven stuff to reach the level of generation and filtering I wanted. 

If you want to give it a shot, that would be awesome.
