### ISSUE TITLE
docs: "Merge" is unclear

### ISSUE THREAD

**Issue by lorenzleutgeb** [smallrye/smallrye-reactive-messaging#851]
Referring to https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/advanced/merge.html

  1. In the table of contents, the reference is "Merging" while the header of the page is "Merge". I'd expect that they would match.
  1. The page says that "`@Merge` must be used with `@Merge`". Maybe something else was meant?

**Comment by cescoffier** [comment]
Oh yes! The second `@Merge` should be `@Incoming`!

**Comment by cescoffier** [comment]
I've opened a PR: https://github.com/smallrye/smallrye-reactive-messaging/pull/852
