### ISSUE TITLE
How can I send a "tombstone" null message to a compacted Kafka topic?

### ISSUE THREAD

**Issue by FrancescoPessina** [smallrye/smallrye-reactive-messaging#864]
Hello everyone ✋ 
Kafka lets you specify "compacted" topic, i.e. topic in which there is only one entry for each message key.
Kafka lets you delete a key from a "compacted" topic sending a message with `null` as payload and the key set as the key to delete.
**How can I achieve this with this library?**

I would do this in this way:
```
String key = "myKeyToDelete";
Message<V> message = Message.of(null);
    OutgoingKafkaRecordMetadata<K> metadata = OutgoingKafkaRecordMetadata.<K>builder()
        .withKey(key)
        .build();
    return message.addMetadata(metadata);
```

But this is forbidden because a `Message` cannot be instantiated with a key (metadata) and payload null, and generates the `payload must not be null` error.

How can I solve this?

**Comment by cescoffier** [comment]
Starting Reactive Messaging 2.4 (Quarkus 1.9) you can do:

```java
@Incoming(...)
@Outgoing(...)
public Record<K, V> process(Record<K, V> rec) {
  
   return Record.of(null, null);

}
```

see https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.5/kafka/kafka.html#_sending_keyvalue_pairs.

**Comment by FrancescoPessina** [comment]
@cescoffier Thank you for the rapid response :) 
But, how can I send this `Record`? `send()` method only supports `Message<T>` as parameter.
Is possible to add headers to this `Record`?

**Comment by cescoffier** [comment]
Which 'send' method?

You can use something like:

   @ApplicationScoped
    public static class BeanProducingKafkaRecordNoKey {

        @Incoming("data")
        @Outgoing("output-record")
        public Record<Integer, String> process(int input) {
            return Record.of(null, "value-" + (input + 1));
        }

        @Outgoing("data")
        public Publisher<Integer> source() {
            return Multi.createFrom().range(0, 10);
        }

    }

**Comment by cescoffier** [comment]
Just to clarify, Record is a payload type, not a Message subclass. The Kafka connector recognizes it and handle it properly.

**Comment by cescoffier** [comment]
Maybe you can give the kind of code you are using (that needs to set the value to null) and I can show you.

**Comment by FrancescoPessina** [comment]
No, my fault, I made it work :)
I can close the issue, thanks a lot @cescoffier
