### ISSUE TITLE
Mediator gets discovered twice, leading to WeavingException

### ISSUE THREAD

**Issue by lorenzleutgeb** [smallrye/smallrye-reactive-messaging#879]
This is on version 2.0.4. I am not sure whether what I am seeing is a bug or I am doing something wrong. I am getting

```
io.smallrye.reactive.messaging.WeavingException: Synchronous error caught during the subscription of [...]
	at io.smallrye.reactive.messaging.SubscriberMediator.run(SubscriberMediator.java:125)
	...
Caused by: java.lang.IllegalStateException: Already subscribed
	...
```

So I started investigating. By adding a breakpoint to the lambda in `MediatorManager#analyze` that adds objects to `#collected`. It is called twice, the two methods being:

```
[BackedAnnotatedMethod] @Incoming @Blocking @Merge public volatile com.example.Foo.onMessage(Object)
[BackedAnnotatedMethod] @Incoming @Blocking @Merge public          com.example.Foo.onMessage(MyMessageType)
```

I have no clue where that `volatile` method that takes an `Object` comes from. The declaring type is the same (reference) for both. Any clues?

**Comment by cescoffier** [comment]
It looks like you have an overloaded method (same name, different signature). Can you try to change one of the method names to check if that's the issue?

**Comment by lorenzleutgeb** [comment]
Hmm, my `Foo` class implements an interface. If I remove that, it works. It goes like this:

```
@ApplicationScoped
class Foo implements MyMessageTypeListener {
  @Override
  @Multi
  @Blocking
  @Incoming(...)
  public void onMessage(MyMessageType message) { ... }
}

interface MyMessageTypeListener implements SimpleListener<MyMessageType> {}

@FunctionalInterface
interface SimpleListener<T> extends Listener<T> {
  void onMessage(T message);
}
```

**Comment by cescoffier** [comment]
Can you try removing the type <T> from your listener. That may be the real issue. I need to check how we find and identify the method.

**Comment by lorenzleutgeb** [comment]
> Can you try removing the type from your listener. That may be the real issue. I need to check how we find and identify the method.

You mean the generic type argument `T` in `Listener`? No, not really. We use this as a "marker" interface. We have many beans that have `@Incoming` methods (all with different responsibilities). By using that interface we force them all to have a uniform name (`onMessage`) and if we want to list them we can just look up all implementations of that interface. If I remove the generic type argument, then we cannot do all of that.

**Comment by cescoffier** [comment]
That was just to pinpoint the issue - not a workaround.

**Comment by lorenzleutgeb** [comment]
Right. So this works:

```java
@ApplicationScoped
class Foo implements MyMessageTypeListener {
  @Override
  @Multi
  @Blocking
  @Incoming(...)
  public void onMessage(MyMessageType message) { ... }
}

interface MyMessageTypeListener {
  void onMessage(MyMessageType message);
}
```

I just removed the top interface from the hierarchy and added `onMessage` in the more concrete one. The generic type argument is gone, and so is the `WeavingException`.

**Comment by cescoffier** [comment]
Thanks! With this I can build a test reproducing the issue and fix it!

**Comment by cescoffier** [comment]
Forgot to ask, from where comes `@Multi`?

**Comment by cescoffier** [comment]
Can you spot the difference with my code:

```java
    @Test
    public void test() {
        addBeanClass(Foo.class);
        initialize();

        Foo foo = get(Foo.class);
        foo.emit();

        assertThat(foo.list())
            .hasSize(1)
            .allSatisfy(m -> assertThat(m.content).isEqualTo("hello"));
    }

    @ApplicationScoped
    static class Foo implements MyMessageTypeListener {
        private final List<MyMessageType> list = new ArrayList<>();

        @Override
        @Incoming("in")
        public void onMessage(MyMessageType message) {
            list.add(message);
        }

        @Inject @Channel("in")
        Emitter<MyMessageType> emitter;


        public void emit() {
            emitter.send(new MyMessageType("hello"));
        }

        public List<MyMessageType> list() {
            return list;
        }
    }

    interface MyMessageTypeListener extends SimpleListener<MyMessageType> {

    }

    @FunctionalInterface
    interface SimpleListener<T> {
        void onMessage(T message);
    }

    private static class MyMessageType {

        String content;


        public MyMessageType(String content) {
            this.content = content;
        }
    }
```

This test passes.

**Comment by lorenzleutgeb** [comment]
> Forgot to ask, from where comes `@Multi`?

Hmm, I think that I made a mistake here when copying. That should have been `@Merge`. Sorry for the confusion.

**Comment by cescoffier** [comment]
@lorenzleutgeb Is the super method annotated with `@Incoming`? The @Incoming annotation does not support inheritance.

**Comment by lorenzleutgeb** [comment]
> @lorenzleutgeb Is the super method annotated with `@Incoming`? The @Incoming annotation does not support inheritance.

No, it's not.

**Comment by cescoffier** [comment]
I just tried the code I've given above in Quarkus and it's working. Any idea of the difference? 

PS: I've also tried with `@Merge`

**Comment by cescoffier** [comment]
Hum... I was able to get a failed test using the new wiring algorithm.

**Comment by cescoffier** [comment]
Ok, found the issue (I don;'t get while it only happens on the new wiring, but anyway). I will provide a fix with the new wiring.
