### ISSUE TITLE
Does InMemoryConnector support broadcasting?

### ISSUE THREAD

**Issue by lorenzleutgeb** [smallrye/smallrye-reactive-messaging#881]
Suppose I have an application that uses the Kafka connector in production, with one incoming channel [marked as broadcast by setting the appropriate property](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/kafka/kafka.html#_configuration_reference) and that this application further has two `@Incoming` methods for this channel, which should both receive messages.

For testing, I want to avoid starting up Kafka, but instead use the in-memory channel implementation, [which I enable via `InMemoryConnector#switchIncomingChannelsToInMemory`](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/testing/testing.html).

This leads to a `WeavingException` because apparently the in-memory connector does not set up the channel as broadcast.

Am I doing something wrong here, or does the in-memory connector not support this? If so, it'd be nice to say so in it's docs.

---

I am aware  that this is an issue tracker, and not a QA board, so I it's okay if you close this and tell me to ask somewhere else.

**Comment by cescoffier** [comment]
You are right the _in-memory connector_ does not support broadcast. We should add this.

**Comment by lorenzleutgeb** [comment]
It [seems that 6 connectors](https://github.com/search?q=broadcast+repo%3Asmallrye%2Fsmallrye-reactive-messaging+path%3A%2Fdocumentation%2Fsrc%2Fmain%2Fdoc%2Fmodules%2Fconnectors%2Fpartials%2FMETA-INF%2Fconnector&type=Code&l=&l=) support broadcast, so it's quite likely that other users will be as surprised as I was...

**Comment by cescoffier** [comment]
Even worse, the new wiring algorithm I'm working on at the moment suppose that broadcast is somewhat supported. So, it needs to be fixed.
