### ISSUE TITLE
Message negative-ack function is never call in case of a non-retriable Kafka Producer Exception

### ISSUE THREAD

**Issue by vgallet** [smallrye/smallrye-reactive-messaging#883]
Hello,

when producing a message using Kafka connector, the negative-ack function is never call when a Kafka non-retriable Exception is thrown.

I have changed the Kafka quickstart project to illustrated this issue. The code is available [here](https://github.com/quarkusio/quarkus-quickstarts/commit/0fcfb9ec9862b6ee9fc9b42adf9ad6506c072043).

The component versions are from the quickstart project. It uses smallrye-reactive-messaging 2.5.0, kafka-clients 2.5.0. 
Thank you.

**Comment by cescoffier** [comment]
Thanks for the reproducer.

The nack is actually get called, after a LOT of retries. 
If you configure retries to a low number (like 5), you will get the nack call in a _timely_ fashion.

I guess it's time to start the list of unrecoverable issues.
