### ISSUE TITLE
Support multiplee kafka brokers

### ISSUE THREAD

**Issue by ferencbeutel4711** [smallrye/smallrye-reactive-messaging#897]
Hello there,

right now, it seems as if I can only configure the kafka brokers per application and not per channel - this would be incredibly useful in a multi-team setup where each team has its own kafka cluster. So there needs to be a way to configure a relationship between a topic and a kafka cluster.

Thanks!

**Comment by cescoffier** [comment]
You can configure the broker per channel using:

```
mp.messaging.incoming.your-channel.bootstrap.servers=...
```

Same for outgoing.

**Comment by ferencbeutel4711** [comment]
oh that is great to hear! sorry, did not find this documented anywhere, the only thing I've always seen was 'bootstrap.servers'
