### ISSUE TITLE
AMQP messages are not acknowledged when using a MessageConverter

### ISSUE THREAD

**Issue by languitar** [smallrye/smallrye-reactive-messaging#903]
https://github.com/languitar/amqp-ack-test-kotin contains a test quarkus kotlin project that exhibits missing ACKs for AMQP messages. In essence, the important code is:

```kotlin
class DummyData

@ApplicationScoped
class DummyDataConverter : MessageConverter {
    override fun canConvert(`in`: Message<*>, target: Type): Boolean = true

    override fun convert(`in`: Message<*>, target: Type): Message<*> {
        println("Converting $`in`")
        return `in`.withPayload(DummyData())
    }
}

@ApplicationScoped
@Path("/hello-resteasy")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello() = "Hello RESTEasy"

    @Incoming("test")
    fun process(data: DummyData) {
        println("Processing $data")
    }
}
```

Without the message converter incoming messages are acknowledged as expected. With this message converter, the ack is not sent, which I could also verify when tracing the communication with the broker (ActiveMQ Artemis) using wireshark. The `disposition` messages are not sent from the client to the broker once the message converter is installed. So, restarting the project simply reprocesses old messages. This doesn't happen when the converter is removed and the handler method is changed to

```kotlin
    @Incoming("test")
    fun process(data: ByteArray) {
        println("Processing $data")
    }
```

**Comment by languitar** [comment]
I also tried to use explicit ACKs by receiving a `Message<DummyData>` instance. Same issue here.

**Comment by languitar** [comment]
Thanks for quickly preparing a fix. Is there any way I can get this working in a current quarkus project?

**Comment by cescoffier** [comment]
You can build from the PR and add the dependency in your Quarkus
application.

I will cut the 2.6 release tomorrow.

Le lun. 14 déc. 2020 à 10:53, Johannes Wienke <notifications@github.com> a
écrit :

**Comment by languitar** [comment]
Regarding the 2.6 release: will that automatically propagate into quarkus-universe-bom or how is the process here?

**Comment by cescoffier** [comment]
No, that would only happen in January. In the meantime, you will need to declare the dependency on the connector in your pom.xml file.

**Comment by languitar** [comment]
Ok, but that would leave other Quarkus users unaware of this bug and the fix until, right? What is the idea of the release process here? Why is no 2.5.1 bugfix release planned for such a thing?

**Comment by cescoffier** [comment]
Quarkus release schedule is already defined. In general, we release SmallRye Reactive Messaging 1 week before Quarkus first release candidate so we have time to integrate properly in Quarkus. This one is a bit special because of the end-of-year break, so we will release Reactive Messaging a bit earlier. In general, we do one release every month, 1 week ahead of quarkus.

**Comment by languitar** [comment]
Thanks for the explanations!

That means there are no updates for bugfixes within the released quarkus versions in general?

**Comment by cescoffier** [comment]
It happened, but it depends on our bandwidth.

**Comment by languitar** [comment]
Alright, but it would be safe for me to simply upgrade this one dependency version outside of what the universe bom provides? Do I have to upgrade all reactive-messaging dependencies or which one is required to be bumped to 2.6?

**Comment by cescoffier** [comment]
It should be fine to just add a dependency on the AMQP connector. Don't update the main module as we need to update the Quarkus side.

**Comment by languitar** [comment]
Alright. Thanks again for the explanations and quick fix!
