### ISSUE TITLE
Kafka Connector : TooManyMessagesWithoutAckException for a processor with Message based method signature

### ISSUE THREAD

**Issue by loicmathieu** [smallrye/smallrye-reactive-messaging#914]
I'm facing TooManyMessagesWithoutAckException exceptions for a processor method with Message based methods signature.
This exception occurs even with a few messages.

```
    @Incoming("masterprice-in")
    @Outgoing("masterprice-out")
    public Message<OutputV3> processMasterPrice(KafkaRecord<String, OutputV3> event) throws JsonProcessingException {
        LOGGER.info("Receive a masterprice message");
        OutgoingKafkaRecordMetadata<String> outgoingMetadata = buildDefaultMetadata(event);
        return Message.of(event.getPayload(), Metadata.of(outgoingMetadata));
    }
```

Manually acking the incomming message before returning the outgoing one fix the issue.

More info on this Zulip chat: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Kafka.20processor.20-.20.20TooManyMessagesWithoutAckException

I'll try to provide a reproducer.

**Comment by cescoffier** [comment]
The problem comes from the _cut_ message chain in your code.

You need to use `event.addMetadata(outgoingMetadata));`

I've opened a PR adding a bit more content about that in the documentation.
