### ISSUE TITLE
Not Able To Send Message On Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by kd-eng** [smallrye/smallrye-reactive-messaging#917]
Hi, 
I am not facing any error with [gcp-pubsub-quickstart](https://github.com/smallrye/smallrye-reactive-messaging/tree/master/examples/gcp-pubsub-quickstart) example but not able to see the my message over the my Topic on GCP.

here the my configration properties file:
````
gcp-pubsub-project-id=testing-gcp

# Google Cloud Pub/Sub sink (we write to it)
smallrye.messaging.sink.my-channel.connector=smallrye-gcp-pubsub
smallrye.messaging.sink.my-channel.topic=micro-testing

# Google Cloud Pub/Sub source (we read from it)
smallrye.messaging.source.my-topic.connector=smallrye-gcp-pubsub
smallrye.messaging.source.my-topic.topic=micro-testing
smallrye.messaging.source.my-topic.subscription=micro-worker
````
What else I am missing here? And I have configured my service account as enviromant veriable.
Can you please help us to overcome this problem?

**Comment by cescoffier** [comment]
@loicmathieu did some experiments recently.

**Comment by loicmathieu** [comment]
Yes, I have a working prototype for Quarkus here: https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/55

But it's not merged as the corresponding component on smallrye seems to not be actively maintained, if it changed, I'll merge it.

**Comment by cescoffier** [comment]
The pub/sub connector is no more maintained. Closing as won't fix.

**Comment by HasseNasse** [comment]
@cescoffier Is there any alternative connector for those still wanting to use GCP pubsub? Or are there no plans to support pubsub further down the line?

**Comment by loicmathieu** [comment]
@HasseNasse On Quarkus, there is PubSub support thanks to this extension: https://quarkiverse.github.io/quarkiverse-docs/quarkus-google-cloud-services/main/

@meltsufin maybe your team may be able to help contributing reactive messaging support for PubSub.

**Comment by HasseNasse** [comment]
@cescoffier what would the necessary procedure be to start contributing with a pubsub connector? I can see that we already have something started here: [smallrye-reactive-messaging-gcp-pubsub](https://github.com/smallrye/smallrye-reactive-messaging/tree/main/smallrye-reactive-messaging-gcp-pubsub)?
