### ISSUE TITLE
Add Support for apache pulsar

### ISSUE THREAD

**Issue by aahmed-se** [smallrye/smallrye-reactive-messaging#918]
Add Soucre and Sink support for the Apache pulsar pub sub. https://pulsar.apache.org/

**Comment by cescoffier** [comment]
Agreed, It would be awesome!

**Comment by seseso** [comment]
I found that some work was already done (https://github.com/smallrye/smallrye-reactive-messaging/pull/478) on this topic.

It would be a great addition to the project!

**Comment by liangyuanpeng** [comment]
FYI,   pulsar community begin working for A pulsar client of reactive https://github.com/apache/pulsar-client-reactive

**Comment by cescoffier** [comment]
We won't use a client using Reactor. The model is quite different from what we want here. This will just create complexity and confusion.

**Comment by cescoffier** [comment]
@ozangunalp is going to have a look.

**Comment by ozangunalp** [comment]
Closed by #2002
