### ISSUE TITLE
@Broadcast clarification

### ISSUE THREAD

**Issue by kabir** [smallrye/smallrye-reactive-messaging#928]
I have a test in my WildFly reactive feature pack that has both an `@Incoming("source")` and a `@Channel("source")` listening to the same `@Outgoing("source")` channel. This passed with 2.5.0.

Now I am in the process of updating both my WildFly feature branch and my feature pack (which enables non-spec stuff that we don't want in WildFly) to 2.7.1. It now gives me an exception, telling me to add `@Broadcast` to my `@Outgoing` method.

I've tried that, but it still does not seem to receive messages on both like it used to. Should it?

I have updated the quickstart in my https://github.com/kabir/smallrye-reactive-messaging/blob/2.7.1-reproducer/examples/quickstart/src/main/java/acme/Main.java to show the presumed problem.

In summary I have this:
```
@ApplicationScoped
public class Main {

    public static void main(String[] args) throws Exception {
        SeContainer container = SeContainerInitializer.newInstance().initialize();
        container.getBeanManager().createInstance().select(Main.class).get().consume();
        container.close();
    }

    @Broadcast
    @Outgoing("source")
    public PublisherBuilder<String> source() {
        return ReactiveStreams.of("hello", "with", "SmallRye", "reactive", "message");
    }

    // 1
    @Incoming("source")
    public void sink(String word) {
        System.out.println("Incoming >> " + word);
    }

    // 2
    @Incoming("source")
    public void sink2(String word) {
        System.out.println("Incoming(2) >> " + word);
    }

    // 3
    @Inject
    @Channel("source")
    Flowable<Message<String>> sourceStream;

    public List<String> consume() {
        return Flowable.fromPublisher(sourceStream)
                .map(Message::getPayload)
                .map(m -> {
                    System.out.println("Incoming >> " + m);
                    return m;
                })
                .toList()
                .blockingGet();
    }

}
```
Only one of 1, 2 or 3 receive the message, the others don't. I've tried commenting these out to try various combinations, but it seems that only one wins.

**Comment by cescoffier** [comment]
The topology was not legal, and lead to invalid wiring.

Try with @Broadcast(2) waiting for 2 subscribers before emitting.

**Comment by kabir** [comment]
Thanks it works
