### ISSUE TITLE
Missing AMQP documentation

### ISSUE THREAD

**Issue by yazidaqel** [smallrye/smallrye-reactive-messaging#94]
AMQP documentation is not available

**Comment by cescoffier** [comment]
Yes, this is almost on purpose ;-) 

The AMQP connector is going to be rewritten using the new Vert.x AMQP Client (https://vertx.io/docs/vertx-amqp-client/java/). Waiting for Vert.x 3.7.1 to start working on the rewrite.

**Comment by yazidaqel** [comment]
Okay sounds good. 
I think this will also add support of AMQP to Quarkus same way as Kafka

**Comment by cescoffier** [comment]
@yazidaqel Yes, exactly. The good news is that I've started thinking about the rewrite. So should land soon.

**Comment by cescoffier** [comment]
Fixed in master.
