### ISSUE TITLE
High Availability - Multiple Cluster

### ISSUE THREAD

**Issue by vvavepacket** [smallrye/smallrye-reactive-messaging#967]
I'm currently using this library together with Quarkus to consume messages from a single cluster. Now let's say I have two different clusters. Currently for me to listen to both of these clusters, I need to specify two channels in the properties file and that means I also need to create 2 listeners: 

```
  @Incoming("source1")
  public void listener1(String payload) {
    doSomething()
  }

  @Incoming("source2")
  public void listener2(String payload) {
    doSomething()
  }
```

But the problem is this library currently relies on `kafka.bootstrap.servers` (which just support a single cluster) in the properties file. How can I configure the properties file so that they are configured per channel meaning different cluster per channel  (`source1` and `source2`) instead of globally?

```
kafka.bootstrap.servers=kafka:9092      

mp.messaging.incoming.prices.connector=smallrye-kafka       
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.DoubleDeserializer    
```

**Comment by cescoffier** [comment]
Just configure the bootstrap servers per channel:

```
mp.messaging.incoming.prices.bootstrap.servers=...
mp.messaging.incoming.another.bootstrap.servers=...
```
