### ISSUE TITLE
StreamFactoryImpl - incorrect bean definition

### ISSUE THREAD

**Issue by mkouba** [smallrye/smallrye-reactive-messaging#97]
Normal scoped beans must declare a no-args constructor.

**Comment by cescoffier** [comment]
What do you call _normal_ ?

**Comment by mkouba** [comment]
Normal scope - a scope for which a client proxy is created, i.e. scope annotations annotated with `@NormalScope`, such as `@ApplicationScoped` and `@RequestScoped`. See http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#normal_scope.

**Comment by cescoffier** [comment]
Ah ok, thanks! 

When you say declare it means specifically "declared" or the default constructor (when none are declared) is enough?

Note to myself - the spec should also mention this constraint on application _mediator_ (because of the extension calling `newInstance` on the class)

**Comment by mkouba** [comment]
> When you say declare it means specifically "declared" or the default constructor (when none are declared) is enough?

If a bean class declares an `@Inject` constructor you have to add a no-args constructor and possibly initialize the final fields. If it does not declare any constructor the default no-args constructor is added by the compiler and we're fine.

**Comment by gsmet** [comment]
@cescoffier any chance you could release a new version and update the version used in Quarkus for Monday's release?

**Comment by cescoffier** [comment]
@gsmet Yes, planned for Today. I will also open a PR to bump the version used in Quarkus.

**Comment by cescoffier** [comment]
@gsmet https://github.com/quarkusio/quarkus/pull/2407.
