### ISSUE TITLE
Allow @Incoming with Multi argument

### ISSUE THREAD

**Issue by andreas-eberle** [smallrye/smallrye-reactive-messaging#979]
At the moment, it is not possible to just receive an Multi in a method annotated with `@Incoming`. Therefore, if you want to process the stream of incoming messages (e.g. batch the incoming messages), you have produce another multi and add `@Outgoing` to then reconsume those messages (see source below).

Instead, it would be much cleaner to be able to consume a multi in a method annotated only with `@Incoming`. 

Current workaround: 

```
    @Incoming("events-incoming")
    @Outgoing("events-incoming-for-ack")
    fun receiveEvents(messages: Multi<Message<String>>): Multi<Message<String>> {
        return messages
            .groupItems().intoLists().of(batchSize, maximumMessageBatchDelay)

            .emitOn(Infrastructure.getDefaultWorkerPool())
            .onItem().invoke(Consumer { doSomethingWithBatch(it) })
            .emitOn(Infrastructure.getDefaultExecutor())

            .onItem().disjoint()
    }

    @Incoming("events-incoming-for-ack")
    fun ackMessages(message: Message<String>): CompletionStage<Void> {
        return message.ack()
    }
```

**Comment by cescoffier** [comment]
After having thought about this issue a lot, I don't believe it makes sense to add support for Multi injection in the @Incoming method (and no @Outgoing). 

@Incoming indicates that it's a managed stream. Reactive Messaging manages the stream on your behalf, primarily the subscription and request protocol. On the other side, @Channel indicates a non-managed stream, in the sense that the user must subscribe and request.

With this feature, it would break that distinction. You would end up with an unmanaged stream injected in a method annotated with @Incoming.  

At the same time, @Channel injection already provides a similar feature and preserves the distinction between managed and unmanaged streams. 

For example, you can use the following code:

```java
public void subscribe(@Observes StartupEvent e, @Channel("quotes") Multi<Quote> quotes) {
   // ...
}
```

Constructor injection can also be used.
