### ISSUE TITLE
Request for Synchronous KafkaResponse 

### ISSUE THREAD

**Issue by thomasandre84** [smallrye/smallrye-reactive-messaging#988]
With Message Communication we want to prevent direct communication between the services.
Sometimes there is the case where we need inforamtion from a service and need to continue working on with the response.

Would sth. similar to the KafkaReplyTemplate be an option to be part of Smallrye Reactive Messaging?

**Comment by cescoffier** [comment]
I believe it could be done. I've started to look at that a long time ago, but priorities changed.

**Comment by thomasandre84** [comment]
I could provide my protytype for this, if it helps. It's not nice code. I just made it working.

**Comment by cescoffier** [comment]
Yes please!

**Comment by thomasandre84** [comment]
https://github.com/thomasandre84/quarkus-tryouts/blob/master/quarkus-kafka/src/main/java/org/acme/commandmode/ProdConsService.java 

I've put it all in one package: https://github.com/thomasandre84/quarkus-tryouts/tree/master/quarkus-kafka/src/main/java/org/acme/commandmode

**Comment by cescoffier** [comment]
Thanks!

**Comment by thomasandre84** [comment]
Hello,
I've improved the readability a bit: https://github.com/thomasandre84/quarkus-tryouts/tree/feature/kafka-response/quarkus-kafka
