### ISSUE TITLE
When using CooperativeStickyAssignor in kafka getting unhealthy on non fatal RebalanceInProgressException

### ISSUE THREAD

**Issue by pcasaes** [smallrye/smallrye-reactive-messaging#992]
According to the docs this exception is NON FATAL

https://kafka.apache.org/documentation/#upgrade_250_notable

> When RebalanceProtocol#COOPERATIVE is used, Consumer#poll can still return data while it is in the middle of a rebalance for those partitions still owned by the consumer; in addition Consumer#commitSync now may throw a non-fatal RebalanceInProgressException to notify users of such an event, in order to distinguish from the fatal CommitFailedException and allow users to complete the ongoing rebalance and then reattempt committing offsets for those still-owned partitions.

I can definitely work on this. I'm thinking we can create a configurable list of exceptions that won't mark liveness unhealthy.

**Comment by cescoffier** [comment]
That would be great!

**Comment by pcasaes** [comment]
Looks like this was already fixed on 2.7.1
https://github.com/smallrye/smallrye-reactive-messaging/blob/2ccf50ce788572e8af78e822a96de45bca6ecc50/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaSource.java#L279

**Comment by cescoffier** [comment]
Yes, but that's only for this type of exception.

On the sender side, we have a list of unrecoverable exceptions:

```
private static final Set<Class<? extends Throwable>> NOT_RECOVERABLE = new HashSet<>(Arrays.asList(
            InvalidTopicException.class,
            OffsetMetadataTooLarge.class,
            RecordBatchTooLargeException.class,
            RecordTooLargeException.class,
            UnknownServerException.class,
            SerializationException.class));
```

No need to retry when you see these, it's not going to work.

**Comment by cescoffier** [comment]
Closing.
